### ISSUE TITLE
[pdcontrol] get current patch filename

### ISSUE THREAD

**Issue by macumbista** [pure-data/pure-data#1026]
Could you please add the function to get the current patch filename with [pdcontrol]? It seems easy since it can already get the current directory. Thank you!

**Comment by umlaeute** [comment]
why do you need this?

this seems to be a re-boot of #794 for all the same wrong reasons.

**Comment by macumbista** [comment]
OK I don't feel like revisiting the same argumentation that I skimmed over in that thread. It's really long and convoluted.

**Comment by Spacechild1** [comment]
TL;DR: https://github.com/pure-data/pure-data/issues/794#issuecomment-558315192

**Comment by porres** [comment]
This came from a facebook discussion and was for a whole different reason. It was also for a very special case and I don't know if this was the best solution in the end.

@macumbista has a txt file generated by https://github.com/m---w/kollabs (which seems to be a project that was supervised by @umlaeute ). These are preset files that saved "$0" arguments that got expanded, so when loading them, they were useless and had to be replaced by "$0" again.

One of the possible ideas was to load the patch name as the unique name instead of "$0", but that would need to be passed as an argument to an abstraction, hence maybe adding this to [pdcontrol] wouldn't work.

It's my idea you can just save text files with literal "\$0", but somehow kollabs didn't manage to do that... so I don't know how we can try and solve this problem by making a feature request, seems more like an issue to the development of kollabs.

But maybe we can discuss the possibility of a built in preset saving system for Vanilla as something out of this...

**Comment by umlaeute** [comment]
- if you think there's a bug in kollabs, you should report a bug in kollabs
- if you want to discuss the possibility of a built-in preset saving system, go ahead but
  - remember that this is an issue tracker, not a forum
  - please don't hijack *this* issue, which is clearly about something totally different
