### ISSUE TITLE
[find error] cannot open GOP windows

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#1052]
When an error originates from a normal subcanvas (or abstraction), right-clicking the error in the Pd console or calling `Find / Find Last Error` opens the subcanvas window (or brings it back to front).

But if the subcanvas (or the abstraction) is a graph-on-parent, then the window isn't opened. Only the first non-GOP parent window is opened, or brought to foreground.

![Capture du 2020-06-04 00-19-49](https://user-images.githubusercontent.com/3748246/83695410-479b7980-a5fa-11ea-8b61-885c0e097cca.png)

**Comment by php4fan** [comment]
This is not fixed. Tested in 0.55-2.

I first reported this bug in 2008 btw.

**Comment by umlaeute** [comment]
I also tested with Pd-0.55-2, and it works for me.

here's my test-patch (which is basically what Ant1r screenhotted):
```
#N canvas 119 252 450 300 12;
#X msg 90 79 error;
#N canvas 164 161 450 300 gop 0;
#X obj 37 37 inlet;
#X obj 37 62 f;
#X connect 0 0 1 0;
#X coords 0 -1 1 1 85 60 1 100 100;
#X restore 90 104 pd gop;
#N canvas 624 431 450 300 error 0;
#X obj 37 37 inlet;
#X obj 37 62 f;
#X connect 0 0 1 0;
#X coords 0 300 1 299 85 60 0;
#X restore 190 104 pd error;
#X connect 0 0 1 0;
#X connect 0 0 2 0;
```

@php4fan how are you testing?

**Comment by php4fan** [comment]
Whops sorry my bad, it does work.

It doesn't scroll so that the selected object (the one with the error) is in view, but I guess it never did that in any case and that would be a separate and minor issue.
Because of that, I saw the red rectangle of the GOP area and mistakenly thought that was a selected GOP object highlighted in red seen from outside.
