### ISSUE TITLE
[log] truncation error since pd-0.51?

### ISSUE THREAD

**Issue by solipd** [pure-data/pure-data#1091]
in pd-0.51 [log] is misbehaving:
![log_pd-051](https://user-images.githubusercontent.com/42847992/87851843-d7705b00-c8fc-11ea-9e9c-f40d59bc834a.png)

same test in pd-0.50.2 outputs no errors:
![log_pd-0502](https://user-images.githubusercontent.com/42847992/87851869-20c0aa80-c8fd-11ea-8f9b-00ca75c41ee9.png)

**Comment by umlaeute** [comment]
it would be much appreciated to post the actual patch rather than a screenshot (you can of course post both)

**Comment by umlaeute** [comment]
what is the actual error (as in: how big is it)?

but yea, the code changed to consistently use single-precision calculations internally if Pd is compiled for single-precision calculations (previously it was using single-precision for some calculations (e.g. `exp`) and double-precision for other calculations (e.g. `pow`; or `log`).

in general using exact equality comparision (like `[sel]`) after doing heavy math (`pow`, `log`,...) is bound to be problematic.

i'm not sure this is worth fixing.

**Comment by solipd** [comment]
ok, that makes sense.

I was relying on the double precision in [log 2] to check if an user applied argument is a power of 2 in some abstractions. It's a minor feature though and I can live without it.  

here is the test-patch from above:
[logtest.zip](https://github.com/pure-data/pure-data/files/4942420/logtest.zip)

**Comment by Spacechild1** [comment]
there are other ways to check for power of 2:

`[expr (($f1-1) & $f1) == 0]`

Add an `[abs]` in the beginning if you want to support negative numbers. It's also a good idea to filter 0s with `[sel 0]` to avoid false positives.

This doesn't work for numbers greater than 2^23, but such numbers can't be represented exactly in Pd anyway because of limited floating point precision (after all, Pd doesn't have a real integer type).

**Comment by matthewbrandi** [comment]
On 18/07/2020 22:34, Christof Ressi wrote:
> there are other ways to check for power of 2:
> |[expr (($f1-1) & $f1) == 0]|
> Add an |[abs]| in the beginning if you want to support negative numbers. It's also 
> a good idea to filter 0s with |[sel 0]| to avoid false positives.
> This doesn't work for numbers greater than 2^23

Dear Christof

I am about to expose my ignorance, but here goes …

Am I right in thinking that this is supposed to yield true if and only if the
absolute value of the argument is 2 raised to a non-negative integer power? If so,
doesn’t one need to add at least one more test to rule out false positives?

Otherwise — assuming I have rendered your idea faithfully — one will get some odd
results (try the patch attached). I get true for 2^2.32 but false for 2^2.33, for
example.

For double-precision pd, can one do better than 2^23?

All the best

m

-- 
matthew brandi


#N canvas 518 82 764 462 12;
#X floatatom 152 186 12 0 0 0 argument - -;
#X obj 152 215 select 0;
#X obj 205 244 abs;
#X obj 205 269 expr (($f1-1) & $f1) == 0;
#X floatatom 152 307 5 0 0 0 truth_value - -;
#X msg 152 241 0;
#X floatatom 152 82 12 0 0 0 power - -;
#X obj 152 133 f 2;
#X obj 152 159 pow;
#X obj 152 107 trigger b f;
#X text 200 308 1 if argument is a power of 2 \, 0 otherwise, f 30
;
#X text 500 295 Pd version 0.51.0 (double-precision \, if I have compiled
it correctly) \, Linux, f 20;
#X text 500 80 test values of power \; -------------------- \; -1022
--> true \; -1022.01 --> false \; -1021.99 --> true \; 0.25 --> true
\; 0.5 --> true \; 2.32 --> true \; 2.33 --> false \; 23 --> true \;
31 --> true \; 32 --> false;
#X connect 0 0 1 0;
#X connect 1 0 5 0;
#X connect 1 1 2 0;
#X connect 2 0 3 0;
#X connect 3 0 4 0;
#X connect 5 0 4 0;
#X connect 6 0 9 0;
#X connect 7 0 8 0;
#X connect 8 0 0 0;
#X connect 9 0 7 0;
#X connect 9 1 8 1;

**Comment by Spacechild1** [comment]
Sorry, my example assumes that the input will be integers.
```
2^2.32 = 4.99332 -> 4 -> true
2^2.33 = 5.02805 -> 5 -> false
```
If you expect the input to be floating point numbers, you have to filter out all numbers with a fractional part, e.g. by checking if `[wrap]` yields 0.

**Comment by matthewbrandi** [comment]
On 19/07/2020 18:11, Christof Ressi wrote:

> If you expect the input to be floating point numbers, you have to filter out all 
> numbers with a fractional part, e.g. by checking if |[wrap]| yields 0.


Thanks, Christof.

m

-- 
matthew brandi

**Comment by umlaeute** [comment]
closing this, as it seems the current behaviour is somewhat expected, and likely to never get fixed.
