### ISSUE TITLE
Headphones are ignored on macOS Catalina

### ISSUE THREAD

**Issue by Koosmann** [pure-data/pure-data#1094]
Hi guys - I'm having a blast learning to use Pd, the only issue I've run into is that the headphone jack seems to be ignored altogether; sounds are still played through the speakers while headphones are plugged in (note: other apps like Spotify will use the headphones as expected).  I'm on MacOS Catalina 10.15.6 Beta running Pd 0.50-2.

Is this possibly a bug? Or is there a setting related to this that I'm missing?

Thank you!

**Comment by Spacechild1** [comment]
Go to the microphone section in the privacy settings and check if you find Pd in the list of apps. If yes, make sure that Pd has permission to use the microphone.

**Comment by Koosmann** [comment]
Hi @Spacechild1 ! Just took a look at this and everything looks good to go - Pd is listed and checked under microphone access.

**Comment by Spacechild1** [comment]
I actually terribly misread your issue... :-/ thought it was about microphone input (which is a common issue).

it's strange that Pd wouldn't play to your headphones while plugged in. which output devices are listed in the Pd audio settings?

**Comment by porres** [comment]
you might need to choose the headphones in the audio settings, I only get "bult-in output" in mojave

**Comment by Koosmann** [comment]
@Spacechild1 No worries!  Things are working now after getting headphones selected in the audio settings (thanks @porres !).

I ran into some quirks along the way though:
- I can see the headphones in the outputs list of the audio settings, but only if I plug them in before starting Pd.   
- Also, when headphones are present in the output list, if 'Macbook Air Speakers' is selected, the computer's master volume is ignored (it just plays at full volume through the speakers). 

Note: when the headphones are selected as the output, things work as expected; if headphones are **not** present in the output list and 'Macbook Air Speakers' is selected, things also work as expected.

**Comment by danomatika** [comment]
Pd uses the Portaudio on macOS which does not handle hot plugging of devices. This means if the device is not present when Pd is started, you won't be able to use a device you plug in later. You need to restart Pd in order for the device to be included in the list.

Usually, macOS presents all available output devices including both speakers and headphones. I've noticed in some newer devices, like the 2019 mac Mini, the headphone output only appears if it's plugged in and is not present otherwise. If this trend continues, we will probably have to update either Portaudio or write a CoreAudio backend for Pd which handles hot plugging.

**Comment by danomatika** [comment]
I'm closing this for now.
