### ISSUE TITLE
s_utf8.h missing in linux/windows application source folder

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1108]
I'm using s_utf8.h for cyclone/comment and it compiles fine on mac because it is available in the sources folder. But I don't see this available in windows/linux so I can't compile it.

**Comment by Spacechild1** [comment]
Well, `s_utf8.h` is not really a public header and the functions are not properly exported, either. This happens to work now because Pd exports all symbols, but it will fail once it only exports `EXTERN` functions (which already happens when you compile Pd with MSVC).

I think the cleanest way is to ship your own copy of the UTF8 library (including `s_utf8.c`!). If you really want to use functions that are (accidentally) exported by Pd, you can simply forward declare them in your code.

I think the actual "bug" is that Pd is not consistent in deciding which header files it ships with the application. I think it should only ship those with `EXTERN` functions - which would rule out `s_net.h`, for example. But this should really be a different issue.

**Comment by porres** [comment]
> I think it should only ship those with EXTERN functions - which would rule out s_net.h, for example. But this should really be a different issue.

Could you go ahead and work on that one then? 

Thanks for the answer
