### ISSUE TITLE
'fast-forward' doesn't work with [pd~]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1126]
"sched_fastforward" is only used in the polling
scheduler. This means "fast-forward" has no effect in the callback
scheduler or in a plugin scheduler (e.g. the one used by the [pd~]
subprocess).

**Comment by umlaeute** [comment]
what is not working?
please provide a minimal example that shows the buggy behaviour.

**Comment by Spacechild1** [comment]
> what is not working?

As the issue discription says: 

> This means "fast-forward" has no effect in the callback scheduler or in a plugin scheduler (e.g. the one used by the [pd~] subprocess).

Here's the relevant part of the code: https://github.com/pure-data/pure-data/blob/2af4b5ddc7479b73f45360f88548efc963e64ae8/src/m_sched.c#L475

Search for `sched_fastforward` and you'll see it is only used in the polling scheduler.

> please provide a minimal example that shows the buggy behaviour.

I simply doesn't work at all, see above.

**Comment by umlaeute** [comment]
what does not work?
seriously, i'm not asking about the relevant code (that is easy enough to find).

what do you do? what happens? what did you expect?

**Comment by Spacechild1** [comment]
> what do you do?

send `[fast-forward(`.

> what happens?

nothing

> what did you expect?

The same behavior as for sending `[fast-forward(` in the polling scheduler.

---

I think the fix could be simply to move the loop around `sched_fastforward` *inside* `sched_tick()`. Then there's no need to repeat this code for every scheduler...

**Comment by umlaeute** [comment]
> > what do you do?
> 
> send `[fast-forward(`.

where to?

if I send `[; pd fast-forward 1000(` in the host-application, both the host and the child-process (aks `[pd~]`) get fast-forwarded.

closing this as works-for-me.

**Comment by umlaeute** [comment]
or put otherwise:

the `[pd~]` process is synched to the the parent process (the host).
if the parent-process advances time, so does the child-process.
the child-process cannot change the advancement of time of the parent-process.

it *seems* that you want to advance time in the child-process without advancing it in the parent-process. if we want to maintain the synchronicity between the parent and the child (and i think we do want this), then i don't see how we can at the same time become out-of-sync.

probably we should be closing this as not-a-bug/expected-behaviour.

**Comment by umlaeute** [comment]
(reverting the "Close" as this was mainly triggered by lack of self-control together with super-cow-powers; i still think that the report lacks a clear explanation/objective resp. that the current behaviour is intended)

**Comment by porres** [comment]
My first idea was to work separately on a different core and not choke the audio on the "main" patch - but this seems impossible for what I'm learning...

**Comment by Spacechild1** [comment]
> i still think that the report lacks a clear explanation/objective resp. that the current behaviour is intended)

I don't see a reason why the `fast-forward` message shouldn't work in the callback scheduler. I also don't see why it shouldn't work for *any* scheduler.

> the child-process cannot change the advancement of time of the parent-process.

why not?

> it seems that you want to advance time in the child-process without advancing it in the parent-process.

yes.

> if we want to maintain the synchronicity between the parent and the child (and i think we do want this), then i don't see how we can at the same time become out-of-sync.

I've first thought so myself, but actually there isn't much synchronicity except for the audio input/output which is piped between the processes. It is totally valid for the child process to run the scheduler multiple times. The only thing that happens is that `[adc~]` will see repeated blocks of audio and the outlets of `[pd~]` will only see the last block of the child's `[dac~]`.

In fact, doing `fast-forward` in child processes might even be useful because you can batch-process specific parts of your project.

At the very least, I don't see a reason why `fast-forward` shouldn't work in a child process.

**Comment by porres** [comment]
> In fact, doing fast-forward in child processes might even be useful because you can batch-process specific parts of your project.

that was my idea, but I also hoped for no audio chokes and, just to be 100% clear, that's impossible, right?

**Comment by Spacechild1** [comment]
> that's impossible, right?

right :-)

**Comment by porres** [comment]
@Spacechild1 , this has been fixed, right?

**Comment by Spacechild1** [comment]
Yes!
