### ISSUE TITLE
request: have # as part of interface without interfering with Pd code

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1144]
hi,

I believe # is not allowed as it interferes with the "#X" (new line command for Pd code). it would be nice if there was a way to include it for graphical objects - e.g. toggle labels - by removing it from the code:

e.g. when typed like so: /#/

if I have missed the fact there is already a way to do this I do apologise and would like to know.

thanks

**Comment by Spacechild1** [comment]
> I believe # is not allowed

*where* is it not allowed? 

> as it interferes with the "#X"

Certainly not. You must not send messages to `#X`, but you can definitely send messages to `#Y`.  Pd doesn't look for leading characters in a symbol.

I'm not sure what problem you are actually experiencing, but since you mentioned toggle labels, could this be duplicate of https://github.com/pure-data/pure-data/issues/558?

**Comment by porres** [comment]
> could this be duplicate of #558?

it is

**Comment by HenriAugusto** [comment]
And we already have proposal for fixes in #953 and #948

**Comment by umlaeute** [comment]
how do we know that this is a dupe of #558? (i guess it is, but i really want to have feedback from @AydinHumphries before doing anything else)

**Comment by porres** [comment]
This was first reported to the facebook group and it seemed clearer then. There was also a long youtube video about it - see: https://www.youtube.com/watch?v=0KUmxHc_mqg

Then I said it was best to do issue reports here, but also that it wasn't needed for this case as it had been reported and that we already have fixes as well. 

I could be wrong, but I just can't see it.

**Comment by umlaeute** [comment]
ah well, if you have information from side-channels, then it's probably safe to assume you are right.
closing this for now (we can always reopen)

**Comment by AydinHumphries** [comment]
I notice this request was closed before I had a chance. by the way I would have appreciated it if Alex would have simply commented what solutions there were already available for this issue on facebook rather than pointing me here just to be told it's a duplicate (since he already had to invest energy to do that anyway). I mean, I don't want to waste developer's time - he said I should post "these kinds" of issues over here so I thought perhaps a post would be appreciated even if it was a duplicate. I mean there is a search function but it's not the easiest thing and surely a duplicate of a problem can be useful if that issue has only been in part resolved or not resolved at all. 

https://github.com/pure-data/pure-data/search?q=%23&unscoped_q=%23

https://github.com/pure-data/pure-data/search?q=%24&unscoped_q=%24

https://github.com/pure-data/pure-data/search?q=%24&unscoped_q=%24

in fact on the subject of duplicate issues and search functions in general, surely it's actually easier to find answers to questions you have on problems if there is not just one solitary question buried by hundreds of other results in the search algorithms.

anyway, umlaeute asked if this is a duplicate, of the other topic. well since looking at the other issue I can point at least one thing related to this issue that isn't mentioned in 558:

1. # is not just a problem for coding gui labels. it can be an issue for sending/receiving messages. I have a patch where I had to change [s #20] to to [s s20] because the toggle with the encoded [r s20] was not receiving it. ok fine, I can just change # to s, it's not a big deal. but maybe people should just be able to type [s #20], assuming it's possible to do that without creating a major bug or backwards compatibility issue.

there are a bunch of issues related as well but not exactly the same, like $ converting to # (I had a send message in a toggle that was something like $0-message$1 that got converted to $0-message#1). I didn't need that $1 as it turns out abstractions with $0 will return unique values even with different instances of the same abstractions (or so I'm told) but my point is this can be problematic.

by the way, I also I don't have internet connection at the moment and can only get it when I go to bars or cafes so it is harder to search these issues. I'm still relatively inexperienced with Pd and of course there will be mistakes in my questions or things I knew but overlooked. the threads linked to are especially difficult to interpret compared to a simple answer for this subject.

as for the solutions suggested from those topics:

- in 953, neither \$ nor $/# create # (I don't know if that was being suggested or not I'm just mentioning that in case)
- in 558, x_\$0 does not create a # (again this is based on my interpretation of the thread - the user may have been referring to something completely different)

**Comment by porres** [comment]
well, I was just saying issue/bug reports are better dealt here, so it was a general hint.

And about your issue, I did say **"these are long known issues (...) and there's already proposed changes to deal with them"**, sorry if it wasn't clear.

**Comment by porres** [comment]
> there are a bunch of issues related as well but not exactly the same, like $ converting to # (I had a send message in a toggle that was something like $0-message$1 that got converted to $0-message#1).

this is definitely reported and part of https://github.com/pure-data/pure-data/issues/558  - because iemguis use "#" to represent "$".

> hashtag is not just a problem for coding gui labels. it can be an issue for sending/receiving messages.

yeah, but you're talking about send/receive symbols in iemguis, this is also part of the same issue described in https://github.com/pure-data/pure-data/issues/558 - which is not at all only about labels.

> there are a bunch of issues related as well but not exactly the same, like $ converting to # (I had a send message in a toggle that was something like $0-message$1 that got converted to $0-message#1). 

How is this different than what you just said about "$ converting to #"? Again, also part of https://github.com/pure-data/pure-data/issues/558

> as for the solutions suggested from those topics:
> 
> in 953, neither $ nor $/# create # (I don't know if that was being suggested or not I'm just mentioning that in case)

There's no "solution" (at least nothing straight forward, just very dirty hacks) you can try on your own to deal with this. In short, this is a bug, a flaw, and we need to make changes to Pd so it works. 953 is a "PR" (Pull Request), with changes to the Pd code. They haven't been incorporated into Pd yet, though. I don't know what you mean, have you tried compiling the branch with the changes and tested?

> in 558, x_$0 does not create a # (again this is based on my interpretation of the thread - the user may have been referring to something completely different)

no, it does not, so what? Does it create for you? I doubt it. You mentioned how $1 becomes #1... not $0

anyway, I know this is very confusing, and you need a better understanding of Pd's source code to understand what's going on - but we're on it, and we've been working on this already, and I have tested the PR https://github.com/pure-data/pure-data/pull/953 and it does solve all the issues you've mentioned and others more.

But please don't feel bad about posting duplicate issues. It's fine. You should not prevent yourself from posting an issue just because you don't know if it's been done before. It's ok for us to check if it's a duplicate and close it, no hassle... and it's good for you to know if a fix has already been proposed or not. In this case, there's a fix you can expect to be part of the next releases.

**Comment by porres** [comment]
> there are a bunch of issues related as well but not exactly the same, like $ converting to # (I had a send message in a toggle that was something like $0-message$1 that got converted to $0-message#1).

this is definitely reported and part of https://github.com/pure-data/pure-data/issues/558  - because iemguis use "#" to represent "$".

> hashtag is not just a problem for coding gui labels. it can be an issue for sending/receiving messages.

yeah, but you're talking about send/receive symbols in iemguis, this is also part of the same issue described in https://github.com/pure-data/pure-data/issues/558 - which is not at all only about labels.

> as for the solutions suggested from those topics:
> 
> in 953, neither $ nor $/# create # (I don't know if that was being suggested or not I'm just mentioning that in case)

There's no "solution" (at least nothing straight forward, just very dirty hacks) you can try on your own to deal with this. In short, this is a bug, a flaw, and we need to make changes to Pd so it works. 953 is a "PR" (Pull Request), with changes to the Pd code. They haven't been incorporated into Pd yet, though. I don't know what you mean, have you tried compiling the branch with the changes and tested?

> in 558, x_$0 does not create a # (again this is based on my interpretation of the thread - the user may have been referring to something completely different)

no, it does not, so what? Does it create for you? I doubt it. You mentioned how $1 becomes #1... not $0

anyway, I know this is very confusing, and you need a better understanding of Pd's source code to understand what's going on - but we're on it, and we've been working on this already, and I have tested the PR https://github.com/pure-data/pure-data/pull/953 and it does solve all the issues you've mentioned and others more.

But please don't feel bad about posting duplicate issues. It's fine. You should not prevent yourself from posting an issue just because you don't know if it's been done before. It's ok for us to check if it's a duplicate and close it, no hassle... and it's good for you to know if a fix has already been proposed or not. In this case, there's a fix you can expect to be part of the next releases.

**Comment by AydinHumphries** [comment]
> well, I was just saying issue/bug reports are better dealt here, so it was a general hint.
> 
> And about your issue, I did say **"these are long known issues (...) and there's already proposed changes to deal with them"**, sorry if it wasn't clear.

it was a general hint, sure but I don't think I've ever posted an issue on facebook that wasn't a duplicate, so I'm not sure what posts I made that would be a general hint about. (I don't think there are many issues in general that aren't a duplicate of something).

but you also said:

> But please don't feel bad about posting duplicate issues. It's fine. You should not prevent yourself from posting an issue just because you don't know if it's been done before. It's ok for us to check if it's a duplicate and close it, no hassle... and it's good for you to know if a fix has already been proposed or not. In this case, there's a fix you can expect to be part of the next releases.

so we're all cool.

> no, it does not, so what? Does it create for you?

well people were mentioning solutions had already been found for what I was mentioning as a duplicate issue. I was just pointing out - while it was entirely possible I had missed something - I never noticed any solutions. so I'm not sure what kind of feedback I'm supposed to take away from this, if any. I did feel a little bit frustrated when I read the responses here as I kind of had already predicted this would happen if I posted on github. 

I think personally, a purely mechanical approach like this isn't necessarily the best approach to issues that aren't just about technicality but user friendliness, seeing help files in nice bold big bright colours and large font, etc., etc. so being purely mechanical about coding and people's "duplicate" issues raised isn't always the most useful thing but I'm not a coder so I wouldn't know, it's just what I can see from bird's eye view.

> I don't know what you mean, have you tried compiling the branch with the changes and tested?

honestly, I wouldn't be confident enough to approach that. I'd just risk screwing with the tried and tested version of Pd I'm currently running with. dirty hacks sound like a double edged sword.

> There's no "solution" (at least nothing straight forward, just very dirty hacks) you can try on your own to deal with this.

so you see this is what I mean about posting duplicates. dirty hacks don't sound like the best solution available to this issue which can be problematic. close my issue I don't take offence, I'm just saying that might not be the best course of action if we could reopen a "cold case" so to speak. in that instance, duplicate issues can be useful to remind developers about old problems.

but your tone is warm so again, no offence taken. I'm just not sure what value a poster like me would bring to github, I am better to stay on facebook or pd mailing list, perhaps. not to say you're doing this but I don't want to be pushed away what I feel are the best places with optimal solutions for my coding problems. if a developer or someone like yourself reads something I put on facebook useful feel free to bring it to developer's attention here all the same.

**Comment by Spacechild1** [comment]
> well people were mentioning solutions had already been found for what I was mentioning as a duplicate issue. I was just pointing out - while it was entirely possible I had missed something - I never noticed any solutions.

The solutions are implemented as pull/merge request, meaning that they haven't been integrated into Pd yet. But they exist and might be available soon.

**Comment by umlaeute** [comment]
btw, i still would suggest to *not* use send/receive labels that start with `#` in your patches, as there **is** a chance that they might interfere with Pd's patching system.

i think this is similar to using macros that start with `_` or (god forbid) `__` in C/C++: you *can* define and create your own macros starting with `_`, but you *should not*.


Similar to [Programming in C++, Rule#15](http://www.doc.ic.ac.uk/lab/cplus/c++.rules/chap5.html), i therefore state:

> In order to avoid collisions, do not begin an identifier with a hash.
