### ISSUE TITLE
request: sending objects to the main patch versus sending them to a sub-patch with dynamic patching

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1149]
**context:**
from the longer thread (I was requested to post each issue seperately): https://github.com/pure-data/pure-data/issues/1147

**description:**
I have found that Pd can be inconsistent whether it allows you to send objects to the main patch versus whether it allows you to send them to a subpatch. an example could be, you create a patch called "mainpatch.pd" and then send an object - a bang - to the white space you get when you open "mainpatch.pd". you could do this by clicking the message [;
pd-mainpatch.pd obj 100 100 bng;{ to create a bang somewhere in the top left corner of the patch. if you create a subpatch, "pd subpatch", then the message would be [;pd-subpatch obj 100 100 bng;{. the latter command will most likely work. the former command seems to be working in my patch at the moment but it can be inconsistent whether it creates a bang or not. sometimes it will simply say "pd-mainpatch.pd: no such object". I'm quite certain this happened to me with an earlier project but it was a long time ago. it let me create objects that way for about a week or so then one day, it just stopped. it is difficult to prove though unless I can find a screenshot of a subpatch where it works and then find one where it just doesn't. I have saved here a screenshot of it working though until I can find one where it does not.

![image](https://user-images.githubusercontent.com/48067862/94045778-c72a9f80-fdc7-11ea-97a6-e4e2f16763c9.png)

**Comment by umlaeute** [comment]
(i've started an answer to your post, but then deleted it again; i think we really should establish a common grounds on how we are going to communicate first. else this will become an energy-drain for everybody.)


please use a meaningful title: "part 1" is *not* very meaningful.

the title should be an indication about what the actual problem (or feature-request, or...) is.
in it's current form, i'm having a hard time to understand what your actual problem is (and a proper title might have helped).

try to summarize the problem in one sentence. this would be a good title.

then try to summarize the problem in one paragraph; this would be a good start for the description.

then go into detail, explaining how you encounter the problem in real live (probably accompanying the problem with patches).
if the problem appeared in a larger patch, please try to trim down the patch until you have a *minimal verifiable example*.
this will help others tremendously when trying to understand and verify your problem.

remember: we can only fix problems that we understand.
we can only make sure that we have fixed a problem, if we can verify that it no longer exists.

please don't link to largish resources on external sites.
don't expect anybody to dig through all your compositions from the past years, in order to understand a problem with dynamic voice allocation.
don't expect anybody to wait for some external provider to finish their site-maintenance, in order to be able to get the material required to understand your problem.

keep in mind, that the people here are all volunteers.
using the issue-tracker in a concise way, will make both your and our experience much more delightful.

in case, you haven't written that many bug-reports before, here's a howto: https://outcry.io/2020/07/06/bug-report/ (this just came up after a quick websearch; there are ton's of advice how to write a good bug-report; there's probably also some documents available on how to write good feature requests).


having said all that, i don't know whether this issue-board is actually the right place for your cause.
we don't use github for general discussion, documentation or user-help.
there's the mailinglist, the chat, the forum,... for these things.
we do use the github issue tracker for "things" that are (more or less) well defined problems and can be solved by writing/bending code.

**Comment by porres** [comment]
"a minimal verifiable example" +1

btw, for sending messages to the parent patch, you can use [iemguts/sendcanvas] or [else/canvas.setname], this last one is like [namecanvas] with the ability to also name a parent (see https://github.com/pure-data/pure-data/pull/837 for a proposal to include this in vanilla)

**Comment by AydinHumphries** [comment]
> please use a meaningful title: "part 1" is _not_ very meaningful.

yes, I have updated.
 
> then try to summarize the problem in one paragraph; this would be a good start for the description.

I have done this and evidenced an example where the feature described in OP works. I am also trying to find a patch where this feature does not work to prove it can be inconsistent. I don't mind if you close the issue until I have found it. keep in mind in the former thread for general dynamic patching issues, I did manage to include two screenshots for a different issue - one where a feature works and one where it doesn't. I don't believe this issue is different to that one.

> then go into detail, explaining how you encounter the problem in real live (probably accompanying the problem with patches).

I rewrote and then decided just to get rid of the "extra details" section. I will put it back if requested though.

> in case, you haven't written that many bug-reports before, here's a howto: https://outcry.io/2020/07/06/bug-report/ (this just came up after a quick websearch; there are ton's of advice how to write a good bug-report; there's probably also some documents available on how to write good feature requests).

ok.

> we do use the github issue tracker for "things" that are (more or less) well defined problems and can be solved by writing/bending code.

I know we are not discussing the other thread but there are quite a few things linked to in #1147 which are defined issues like this: the black dots when you clear multiple objects in dynamic patching, GUI affecting processing speed on patches when creating or clearing multiple objects on screen, inconsistency with an object that gets successfully cleared versus "consistency check failed: editor". the final issue is the only one that is perhaps a problem with the else library rather than vanilla - but it is not clear.

**Comment by AydinHumphries** [comment]
> "a minimal verifiable example" +1
> 
> For sending messages to the parent patch, you can use [iemguts/sendcanvas] or [else/canvas.setname], this last one is like [namecanvas] with the ability to also name a parent.
> 
> btw, see #837, which a proposal to include this in vanilla that I think takes care of your issue.

I appreciate the suggestions but does referring someone to an externals library resolve an issue if it's for things that people would like to be able to do with vanilla and no inconsistencies sending messages to the main patch?

**Comment by porres** [comment]
externals are suggested when there's no way to do it in vanilla.

as for the vanilla solution, again, it envolves changes to the code and I also pointed to the PR that takes care of this (#837)

**Comment by porres** [comment]
ok, I see you edited your description and is now clearer.

> I have saved here a screenshot of it working though until I can find one where it does not.

yeah, it would be good if you could send us a patch with a reproducible fail.

anyway, it seems you can just use [namecanvas $0-patch] in your patches to name your patch, which seems better and more reliable to me, and you don't seem to need the depth argument yet (I guess).

**Comment by AydinHumphries** [comment]
> anyway, it seems you can just use [namecanvas $0-patch] in your patches to name your patch, which seems better and more reliable to me, and you don't seem to need the depth argument yet (I guess).

this is what I read from the [namecanvas] help file:

_"its use in making self-editing patches is dangerous since if you use it to edit the namecanvas itself away you can cause Pd to crash"_

then the solution it proposes is:

[;
pd-namecanvas-help.pd msg 280 80 this is safer but only possible if you know the name of the canvas in advance.{

so, effectively the thing I said in OP might work inconsistently sometimes:

[;
pd-mainpatch.pd obj 100 100 bng;{

but I guess I will have to wait until I find a patch where doing this fails and returns an error:

"pd-mainpatch.pd: no such object"

until I find this, I will close this thread myself.

**Comment by porres** [comment]
the danger is only if you **edit the namecanvas itself away** - other than that, it's pretty safe and works better than depending on knowing your patch name before hand.

> but I guess I will have to wait until I find a patch where doing this fails and returns an error

definitely - personally, I've used dynamic patching all the time and never ran into a similar issue.

**Comment by AydinHumphries** [comment]
> > it let me create objects that way for about a week or so then one day, it just stopped
> 
> i'm pretty sure that this happens only if you - for whatever reason - rename your abstractions.
> e.g. while working on `mainpatch.pd` everything works, but once you save it as `mainpatch2.pd`, you effectively changed the receive-label, and thus can no longer send messages to it (aka: your patch stopped working).

I know what you mean but it was a mistake that meant I had to rework my whole patch, respell all my messages to create GUI objects in a subpatch rather than the parent patch/main patch/whatever it's called. I am notorious for making simple spelling issues and then having a hard time figuring out what went wrong with my code. but in this instance I am sure I would have checked and double-/triple-checked to make sure there was no simple spelling error from renaming my abstraction rather than completely reworking the patch when there was an easier solution. and I have noticed other issues and inconsistencies with dynamic patching which I'm about to post about.
