### ISSUE TITLE
loadbang doesn't trigger when an abstraction is created via dynamic patching

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1155]
Abstractions that rely on [loadbang] to initialize parameters (like else/display) don't work via dynamic patching because [loadbang] does not trigger a bang when the object is created (this was first brought up in https://github.com/pure-data/pure-data/issues/1147 ).

Check the provided test patch => [test.zip](https://github.com/pure-data/pure-data/files/5284205/test.zip)

Open test.pd, it creates the [abstraction] object with a loadbang that isn't triggered.

**Comment by umlaeute** [comment]
that's been discussed to death, and is expected behaviour.

to recap: a `[loadbang]` fires when the patch is complete. esp. a `[loadbang]` in an abstraction/subpatch fires only after the abstraction/subpatch is fully connected on the parent patch (and all ancestor patches).

with dynamic patching, Pd has no way of knowing when the parent patch (resp. the ancestor patches) are finished, so it doesn't fire any `[loadbang]`s.

instead the user (who initiates the dynamic patching), is responsible for sending the `[loadbang(` message to the dynamically-patched canvas (which will in turn fire the `[loadbang]`s).

alternatively, you could use `[initbang]` (which has other semantics of firing, and therefore doesn't need the ancestor patches to be connected).

**Comment by porres** [comment]
> alternatively, you could use [initbang]

that's what will work for me in the case of else/display, thanks!

**Comment by AydinHumphries** [comment]
> alternatively, you could use `[initbang]` (which has other semantics of firing, and therefore doesn't need the ancestor patches to be connected).

so is it possible to edit this into the else/display somehow, or do I have to wait for the else library to be updated?

**Comment by porres** [comment]
I already fixed it in the else library, check the issue you opened there
