### ISSUE TITLE
resizing a pd patch vertically shifts GOP subpacthes up/down

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1168]
if you go into edit mode and select the lower end of the patch window to resize it, objects will get shifted vertically if you have a GOP abstraction.

test => [test.pd.zip](https://github.com/pure-data/pure-data/files/5308889/test.pd.zip)

using macOS mojave/Pd 0.51-2

**Comment by umlaeute** [comment]
the patch seems to be broken, as it contains bogus `coord` information.
the last line reads:

~~~
#X coords 0 613 1 612 238 60 0;
~~~

what is it supposed to do? where does it come from?

if you remove the offending last line, everything works as expected.
if you create the patch from scratch, the last line will not be there. so:

i *think* this is a leftover from some failed dynamic patching. (and it's preserved because there obviously *is* some valid use-case for a `coords`-setup like that).

if you waddle into dynamic patching, you are on your own.

closing this as not-a-bug.

**Comment by porres** [comment]
> what is it supposed to do? where does it come from?

no idea

> i think this is a leftover from some failed dynamic patching. (and it's preserved because there obviously is some valid use-case for a coords-setup like that).

how is this invalid? what is the proper message I have to use and which ones do I need to avoid? I need to go over my patches and see where this is coming from

**Comment by umlaeute** [comment]
>>  it's preserved because there obviously is some valid use-case

> how is this invalid? 

?? i just said that there a *valid* use-cases for it.
mabye ones that require the object-positions to scale with the window size. but i don't really know, and i don't think i want to touch this before i do know what the current code is for.

> what is the proper message I have to use

the proper message for *what*?
afaict, it's unclear why the message is there in the first place; so far, the only purpose it has is to cause havoc.
it does this quite will, so i guess it *is* the "proper" message for this job. :stuck_out_tongue: 

> and which ones do I need to avoid?

i think it's best to avoid all messages that you don't fully understand.
