### ISSUE TITLE
changing iemgui parameters via messages doesn't make Pd ask if you want to save changes

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1171]
Say you change, for instance, a label on a slider or something, then Pd will ask you if you want to save changes. But if you make the same change via the "label" message, Pd shuts down without asking that. It seems to me it should behave the same way though.

**Comment by umlaeute** [comment]
this is common and intended behaviour in Pd: if you change the state of the patch programmatically (aka; through messages), then this is not recorded as user-interaction and thus does not warrant any "undo" or "do you want to save, because your patch has changed?" action.

this includes (but is not limited to):
- "float" messages sent to `[metro]`
- "label" messages sent to iemguis
- "set" messages sent to msgboxes
- "obj" messages sent to canvases
- any message sent to an abstraction that uses `[savestate]` to save it's state in the parent patch.

**Comment by porres** [comment]
> this is not recorded as user-interaction and thus does not warrant any "undo" 

changing via properties does not warrant it either yet, but I guess there's a PR to take care of this, right?

**Comment by umlaeute** [comment]
that would be #858

**Comment by porres** [comment]
will that work for externals?

**Comment by umlaeute** [comment]
not automatically.

**Comment by umlaeute** [comment]
not automatically. (though this is OT for the issue at hand)
