### ISSUE TITLE
documentation issue with [declare -path] (it has priority over patch's folder)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1177]
I think this is happening, I tested a couple of times :) 

say I have [declare -path else] and in my patch I have a "./object" that is an abstraction from the same folder as my patch that's also part of else, but I want to load this different one instead (for testing and stuff). The thing is that I'm never able to get this other/new one that's also in the same folder of my patch, it always gets the one from the else folder because of [declare]. Get it?

Now, I just wanna make sure this is what we want, cause I thought the priority was always the folder of the patch.

**Comment by umlaeute** [comment]
`[declare -path . -path else]`

**Comment by Spacechild1** [comment]
> cause I thought the priority was always the folder of the patch.

Huh, I thought so, too! This behavior is a bit unfortunate, but at least we have a workaround. Don't know if we could "fix" this without risking to break existing projects...

**Comment by porres** [comment]
even if it's not what we want but now it's what we have to deal with, we can just document it how [decclare] is super powerful and supersedes everything. The problem is that my documentation of how things go would be wrong in Pd's manual.

**Comment by Lucarda** [comment]
> The problem is that my documentation of how things go would be wrong in Pd's manual.

Where in the manual?
I have an open PR https://github.com/pure-data/pure-data/pull/1113 that can include that info.

**Comment by porres** [comment]
in the "4.externals" section (or something) I say the same folder ~ALWAYS~ has priority

**Comment by Lucarda** [comment]
Do you mean this in the manual: https://github.com/pure-data/pure-data/blob/a92ad87194a3a82998acc7af7f0d4cb3b4460d57/doc/1.manual/x3.htm#L693

>Regardless of path, Pd should look first in the directory containing the patch before searching down the path. Pd does not automatically look in the current directory however; to enable that, include "." in the path. The "extra" directory, if enabled, is searched last.


I couldn't find something like:
>I say the same folder ALWAYS has priority

in chapter4

**Comment by porres** [comment]
I was exaggerating :) 

but you have this

4.4. How externals are loaded
Once you make sure Pd can load an external, this is what happens when you create it. Whenever you type the name of an object (into an "object" text box) that Pd doesn't yet know about, Pd looks for a relocatable object file, named, for instance, "profile.pd_linux". **Pd looks first in the directory containing the patch**, then in directories listed as user added paths, then in the standard paths.

**Comment by porres** [comment]
anyway, it's just a matter of improving the documentation

**Comment by porres** [comment]
in "4.3.1. Using the [declare] object:"  we should add how [declare] forces priority over what's specified in preferences=>startup/path - and probably also in the help file of [declare]

**Comment by Spacechild1** [comment]
I made a simple test setup and checked with all Pd versions of the last few years. *It seems like this behavior has been introduced in Pd 0.49*. I'm not sure if this was intentional. To me it looks more like a regression, given that it contradicts the documentation and doesn't make too much sense.

So I would rather prefer to restore the original behavior, unless the change has been made on purpose (for compelling reasons)...

I'm too lazy right now to search the git history and find the actual commit...

**Comment by umlaeute** [comment]
~~~sh
$ cat /tmp/pd/MAIN.pd
#N canvas 1080 620 680 403 12;
#X declare -path foo;
#X obj 104 121 declare -path foo;
#X obj 412 282 myabs;
#X msg 412 253 bang;
#X obj 370 129 loadbang;
#X obj 370 208 t b b;
#X msg 308 263 \; pd quit;
#X connect 2 0 1 0;
#X connect 3 0 4 0;
#X connect 4 0 5 0;
#X connect 4 1 2 0;

$ cat /tmp/pd/myabs.pd 
#N canvas 694 558 450 300 12;
#X obj 106 84 inlet;
#X obj 106 109 print MAIN;
#X connect 0 0 1 0;

$ cat /tmp/pd/foo/myabs.pd 
#N canvas 694 558 450 300 12;
#X obj 106 84 inlet;
#X obj 106 109 print LIBRARY;
#X connect 0 0 1 0;

$ cat runme.sh
#!/bin/sh
make -j8 && git checkout po && ./build-linux/src/pd -noprefs -nogui -nrt -nosound -nomidi /tmp/pd/MAIN.pd 2>&1 | grep "$1"

$ ./runme.sh MAIN    >/dev/null 2>&1 && echo OK
$ ./runme.sh LIBRARY >/dev/null 2>&1 && echo OK
OK

$ git bisect start
$ git bisect bad
$ git bisect good 0.48-2
$ git bisect ./runme.sh MAIN
[...]
136a5d2c54f596ad5ada806cd6ea7bfb625a8d1a is the first bad commit
$
~~~

hmm, 136a5d2c54f596ad5ada806cd6ea7bfb625a8d1a is right after 0.48-2; and indeed, even 0.48-2 seems to load the abstraction from the `[declare -path]` before the the path besides the abstraction.
@Spacechild1 are you sure about 0.49 not showing the problem?

**Comment by Spacechild1** [comment]
> are you sure about 0.49 not showing the problem?

I wrote that 0.49 *introduced* the problem, since 0.48 has the old behavior. However, I did not check 0.48-1 or 0.48-2, so it might have been introduced there.

**Comment by Spacechild1** [comment]
Ok, now I see the problem. If the other patch is located in a *patch relative* directory "foo" (like in your test), then `[declare -path foo]` takes precedence over a patch of the same name in the same directory.

Indeed, this has always been the case (at least till Pd 0.45, I didn't check further). This is unexpected and contradicts the documentation, but I've never came across a situation where this has bitten me. But it's inconsistent nevertheless.

The actual issue at hand only manifests if the other patch is located in a standard path. In my test, I made a `[deg2rad]` abstraction next to my main patch. With `[declare -path zexy]`, it will always load the zexy version, although the documentation says otherwise. Now this behavior *has* changed with Pd 0.49, it didn't happen in Pd 0.48-2.

The question is: why has this changed and should we revert this?

**Comment by danomatika** [comment]
*sigh* This was something introduced purpose and involved quite a long discussion which included @porres as well as others. The original problem was trying to improve the workflow of downloading things on deken and having them found inside the Pd `Documents/externals` directory: #205
