### ISSUE TITLE
savestate : scope of messages emitted from left outlet should be explained in the documentation

### ISSUE THREAD

**Issue by jyg** [pure-data/pure-data#1201]
After the state of an abstraction has been saved in a calling (parent) patch, when the parent patch is reopened, the state-data are sent out the left outlet of the savestate object. This occurs at "initbang" time, before "loadbang" objects  are triggered.
From my experience, the data from left outlet can be widespread (at "initbang" time) everywhere in the abstraction, but not outside it. In particular, no outlet of the abstraction will transmit those data to outside world, nor any [send] object. Note that [send] / [receive] pairs work fine inside the scope of the abstraction.
I suggest that this behaviour should be mentioned somewhere in the documentation.

**Comment by umlaeute** [comment]
sidenote:

> nor any [send] object.

this is not exactly true.


i agree that it should be made clear, that absolutely *no assumptions* should be made about the availability of "connections" (neither explicit ones nor implicit ones like `[send]`/`[receive]`) outside of the abstraction itself.

**Comment by Ant1r** [comment]
> i agree that it should be made clear, that absolutely _no assumptions_ should be made about the availability of "connections"

would it be possible to fix this problem instead? Could `[savetate]` be triggered at `"loadbang"` time?

**Comment by Spacechild1** [comment]
The abstraction state is saved as a `#A saved <list>` message in the patch. `#A` is bound to the canvas. When the canvas receives the "saved" message, it immediately forwards it through the outlet of all `[savestate]` objects in this canvas (including subpatches). That's the reason why `[savestate]` fires at initbang time, and I'm not sure whether this is by design or mere a byproduct of the implementation.

It certainly would be possible for `[savestate]` to cache the lists and output them after receiving the "loadbang" message. The problem is that some patches might already - explicitly or implicitly - rely on the current ordering. On the other hand, it is easy to emulate by saving the lists in a `[text]` object and output them on loadbang. You could even use `[text sequence -g]` to automatically send messages to named receivers.

**Comment by Ant1r** [comment]
> it is easy to emulate by forwarding the lists to a `[text]`

Sure. And this could certainly be mentioned in the help patch.
Anyway probably [savestate] is often used to save values from inside of the abstraction, where this doesn't hurt.

I don't think the current behavior is very natural (from a user POV) though; but since, as you said, this might break existing patch, it's not worth it to look for a (real) fix...

**Comment by jyg** [comment]
In my use case, it's important that savestate triggers at a different 
time than loadbang time in order to decide wether the abstraction should 
load  default parameters or not.

**Comment by Spacechild1** [comment]
I think it would have been better if the user had to explicit bang `[savestate]` to get the saved state. That way it wouldn't fire at init bang time, but the user would still have control over the ordering. But it's too late for that :-)

**Comment by umlaeute** [comment]
> But it's too late for that

totally.

i think it is great that `[savestate]` allows one to create abstractions with a variable number of iolets without having to resort to externals like `[initbang]` (even though i still like the latter).

**Comment by Spacechild1** [comment]
I for one would would still prefer a proper `[initbang]` object in Pd vanilla instead of (ab)using `[savestate]`, but better than nothing I suppose.
