### ISSUE TITLE
Remove [soundfiler] "truncated" message for "read -maxframes"

### ISSUE THREAD

**Issue by jamshark70** [pure-data/pure-data#1233]
```
[read -resize -maxframes 1000 some_file.wav array(
|
[soundfiler]
```

The console will print "soundfiler_read: truncated to 1000 elements."

But... I *asked* for it to read only a certain number of elements -- so this is not an error condition that needs to be reported (in red!).

It would be tidier if "truncated" were reported only when the user requested to read to the end of the file, but the array couldn't be resized.

**Comment by umlaeute** [comment]
> I asked for it to read only a certain number of elements

no, you did not.
you asked to read *up to* a certain number of elements; and Pd is telling you, that it hit that wall.

i have no opinion about the redness of this report.

**Comment by jamshark70** [comment]
Reading a portion of a soundfile is not an exotic use case.

Pd reports it to the user as if it were a failure.

I don't think that's right.

**Comment by Spacechild1** [comment]
I agree with @jamshark70 that hitting the limit is not an error and shouldn't be reported as such. I think this should be an ordinary message, probably at log level 3 or higher.

**Comment by umlaeute** [comment]
> Reading a portion of a soundfile is not an exotic use case.

we are in total agreement here.

I'm just saying that the semantics of `-maxsize` (as it is correctly called) is not "read N frames" but "read *at most* N frames".

We probably should just add a `-nframes` option to the `[read(` message (as the `[write(` message already has), which tells the object how many frames to read, and if it succeeds, no error message should be output. OTOH if `[read -nframes 441000 ...(` only reads 1000 frames, then an error message should be emitted.

**Comment by jamshark70** [comment]
> I'm just saying that the semantics of -maxsize (as it is correctly called) is not "read N frames" but "read at most N frames".

A valid correction, but not relevant to the issue as logged. If you asked for "up to and including N frames" and it read exactly N frames, then the result falls within the bounds of the requested operation and there is no need for any notification. I don't see why it would be necessary to complicate the interface further.

It looks to me like the logic is to print a message if file reading stopped before the end of the file, for any reason (whether it met the user's request or not).

**Comment by Spacechild1** [comment]
> We probably should just add a -nframes option to the [read( message (as the [write( message already has), which tells the object how many frames to read, and if it succeeds, no error message should be output.

I think it is not necessary to print such a message for neither `-maxsize` or the imaginary `-nframes` flag, . After all, `[soundfiler]` outputs the number of samples read through the left outlet and the total number of samples through the right outlet, so the user can easily check themselves if they care. There's no need to always spam the console.

I think the reason for the error message is historical: until recently, Pd used to have a rather small default maxsize and therefore tried to warn the user that the file got truncated. Now that the default maxsize is huge, this isn't necessary anymore. So personally I would opt for removing the message alltogether.

**Comment by jamshark70** [comment]
For the sake of completeness, I thought I would test all 12 combinations of:

- 2x: Resize or not;
- 2x: Maxsize=200 or not;
- 3x: File has:
  - Not enough samples to satisfy maxsize;
  - Exactly enough samples to satisfy maxsize;
  - Enough samples to satisfy maxsize with some left over.

Also (for curiosity) comparing to SuperCollider. (Too much trouble? It's also a Pd programming exercise for me.)

In both environments, each test specifies an initial size of 50 samples, then issues the read request. (In SC, there's not a strict analog for "resize," so the logic is: for "no-resize," pre-allocate a buffer with 50 frames, and then read into it; for "resize," use the allocate-and-read method.)

Test | Pd frames | SC frames
-----|-----------|----------
FileHasNotEnough | 50 | 50
ResizeFileHasNotEnough | 100 | 100
MaxsizeFileHasNotEnough | 100 | 50
ResizeMaxsizeFileHasNotEnough | 100 | 100
FileHasExactly | 50 | 50
ResizeFileHasExactly | 200 | 200
MaxsizeFileHasExactly | 200 | 50
ResizeMaxsizeFileHasExactly | 200 | 200
FileHasLeftOver | 50 | 50
ResizeFileHasLeftOver | 1000 | 1000
MaxsizeFileHasLeftOver | 200 + message | 50
ResizeMaxsizeFileHasLeftOver | 200 + message | 200

The relevant finding is that Pd, in fact, does print the message only when you specify "up to n samples" and there are still contents in the file after that point.

Based on that, I'd tend to agree with Christof ("I think this should be an ordinary message, probably at log level 3 or higher"). It also raises the question of why excess content in the file was considered important enough to notify the user, while "file underflow" (running out of content) was not considered important enough -- Christof's suggestion (which I agree with) is that neither situation warrants a default warning.

And, a curious finding: `-maxsize` implies `-resize`. I'm unsure if that's deliberate.

Test specs:

- Sound file has 1000 samples.
- If `-maxsize` is included in the test, it's 200.
- "NotEnough" adds `-skip 900` so that 100 samples remain in the file.
- "HasExactly" adds `-skip 800` so that 200 samples remain in the file.
- "HasLeftOver" doesn't skip (1000 samples remain).

```
FileHasNotEnough read -skip 900 20-1204-1000-samples.wav t1;
ResizeFileHasNotEnough read -resize -skip 900 20-1204-1000-samples.wav t1;
MaxframesFileHasNotEnough read -maxsize 200 -skip 900 20-1204-1000-samples.wav t1;
ResizeMaxframesFileHasNotEnough read -resize -maxsize 200 -skip 900 20-1204-1000-samples.wav t1;
FileHasExactly read -skip 800 20-1204-1000-samples.wav t1;
ResizeFileHasExactly read -resize -skip 800 20-1204-1000-samples.wav t1;
MaxframesFileHasExactly read -maxsize 200 -skip 800 20-1204-1000-samples.wav t1;
ResizeMaxframesFileHasExactly read -resize -maxsize 200 -skip 800 20-1204-1000-samples.wav t1;
FileHasLeftOver read 20-1204-1000-samples.wav t1;
ResizeFileHasLeftOver read -resize 20-1204-1000-samples.wav t1;
MaxframesFileHasLeftOver read -maxsize 200 20-1204-1000-samples.wav t1;
ResizeMaxframesFileHasLeftOver read -resize -maxsize 200 20-1204-1000-samples.wav t1;
```

![pd-read-tests](https://user-images.githubusercontent.com/318301/101118436-fd846680-3623-11eb-8db9-81c90220958c.png)

```supercollider
(
var path = thisProcess.nowExecutingPath.dirname +/+ "20-1204-1000-samples.wav";

s.waitForBoot {
	var cond = Condition.new;
	12.do { |i|
		var desc;
		var args;
		var start = switch(i >> 2)
		{ 0 } {
			desc = desc ++ "FileHasNotEnough";
			900
		}
		{ 1 } {
			desc = desc ++ "FileHasExactly";
			800
		}
		{ 2 } {
			desc = desc ++ "FileHasLeftOver";
			0
		};
		var numFrames = if(i & 2 > 0) {
			desc = desc ++ "Maxframes";
			200
		} {
			-1
		};
		var buf;
		if(i & 1 > 0) {
			desc = desc ++ "Resize";
			buf = Buffer;
			args = [s, path, start, numFrames, { cond.unhang }];
		} {
			buf = Buffer.alloc(s, 50, 1);
			s.sync;
			args = [path, start, numFrames, 0, 0, { cond.unhang }];
		};
		"Testing %\n".postf(desc);
		buf = buf.read(*args);
		cond.hang;
		"buffer has % frames\n".postf(buf.numFrames);
		buf.free;
		s.sync;
	};
};
)
```

**Comment by Spacechild1** [comment]
>  It also raises the question of why excess content in the file was considered important enough to notify the user

See the second paragraph of https://github.com/pure-data/pure-data/issues/1233#issuecomment-737955651

**Comment by danomatika** [comment]
Whatever y'all decide, let me know and I can update #855.

**Comment by jamshark70** [comment]
My vote is to raise the log level so it's not displayed by default (Christof suggested 3).

In yesterday's class, I led the students through a soundfiler exercise, with maxsize. One student raised her hand: "there's a problem reading the file." It was the "truncated" message -- it does confuse inexperienced users.

**Comment by danomatika** [comment]
Looking at this in d_soundfile.c, I think the message is both incorrectly worded and doesn't require `pd_error`. It could simply be "soundfiler_read: resizing array1 to 1000 elements" which would be followed by a "resize failed" error if anything goes wrong.

I think the original intent is to let you know the target array is being resized for the desired -maxframes. At this point, it's established behavior and if it's well-documented enough, dropping the message altogether could make sense. Was this the original idea @millerpuckette?

**Comment by Spacechild1** [comment]
Just requoting myself:

> I think the reason for the error message is historical: until recently, Pd used to have a rather small default maxsize and therefore tried to warn the user that the file got truncated. Now that the default maxsize is huge, this isn't necessary anymore. So personally I would opt for removing the message alltogether.

But only @millerpuckette knows the true intent :-)

**Comment by porres** [comment]
Hi, like @danomatika, @Spacechild1 and @jamshark70  I think this error message must be dropped. This is now biting me as I'm using [soundfiler] to load a portion of the sound file and the errors are damn annoying and silly, cause I'm just asking it to load a specific number of samples and I don't want to be warned of an error. The object indeed outputs number of samples for us to see if the max number was reached.

I hope we can take the approaching end of the update window to squeeze this in. Seems like something "innocent" enough to go into the 'develop' branch. What do you think?

**Comment by porres** [comment]
And sure, I bet the error was for the fact that back in the day we had a quite small maximum table size by default (4 million points) and relatively lengthy  files would get truncated even with the '-resize' flag. When we increased the default limit, this error should have just been suppressed. The fact that it wasn't is arguably a bug.

For reference, see https://github.com/pure-data/pure-data/pull/366


I get the original purpose of this message was not to set the size of the array to read into and, by extendson, set  portion of the file to read into the array, but this is a quite useful feature and the original purpose (a limit safeguard*) is not actually pertinent nowadays.

* see Miller's comment on the referred PR for more details  in here https://github.com/pure-data/pure-data/pull/366#issuecomment-410372022

Let me quote "(the 4 million one was chosen back in days when memories were much smaller; today it seems much less likely you'd hose your computer by accident by loading a soundfile.)"

So, maxsize in the end, nowadays, should be mostly ignored, or used to define the length of a file as we're trying to do, but without running into annoying errors.

We could think of adding maybe a new message and stuff, but it's not necessary to overhaul the structure and syntax of this object, it is sufficient to just suppress the error and better explain this useful purpose in the help file.

Now, I have changed error messages in the past in my documentation PRs, but just imprving them and never suppressing them.. I did this once even in [soundfiler], see https://github.com/pure-data/pddp/issues/178 - I feel compelled to do this again and treat it as a documentation task, if it is alright with you, so I could do this as part of the documentation updates instead of develop. What do you say?

**Comment by millerpuckette** [comment]
I'm only fixing bugs and documentation now, not making other changes... will put this off for 0.56 :)

**Comment by porres** [comment]
> This would only set the max. number of frames to read. If you also want to resize, you would need to add -resize.

what would happen then, it would still clip to max. number with resize but no error would be given? So, just like -maxsize without an error?

btw, I like the -onset message, can you open a new issue for it?

Anyway, I had made changes to the help file and cleared things a bit more about the -maxsize flag and how it works and how it should just not really be used anymore

**Comment by porres** [comment]
I see, now, about using this together with -resize? What do you have in mind?

As I see it, -nframes shouldn't be used with '-resize' the way it works now, as -resize would "overwrite" and read as many samples as the file has and also resize the table to that size, be it smaller or bigger than '-nframes', huh? Otherwise it could be the same as using -maxsize with -resize, but without the truncation error (and that doens't seem useful).
 
Or maybe, and this makes more sense to me, using -nframes and -resize would resize the table to the number of given frames by -nframes! In the case there aren't as many samples as asked by -nframes, those extra points would be zeroed out.

Alongside with the other possible -onset message, -nframes and -resize would add the number of samples given by 'nframes' from the onset point and resize the table too.

Without -resize, if -nframes reaches the size limit of the array, it gets silently truncated, as this is how it kinda goes now anyway.

Am I making sense?

Anyway, if the idea is to add new methods, we can close this issue and leave things as is and open a new proper issue. But please, let's add this to 0.56 :) as it really sounds useful.

cheers

**Comment by Spacechild1** [comment]
> Or maybe, and this makes more sense to me, using -nframes and -resize would resize the table to the number of given frames by -nframes!

Yes, that's what I had in mind. I just assumed it was the only logical behavior.
