### ISSUE TITLE
feature request: gen style objects

### ISSUE THREAD

**Issue by theslyprofessor** [pure-data/pure-data#1264]
In the vein of gen, perhaps we could have objects like this:
+. -. del. *. etc.
All signal objects, that run on a sample-by-sample basis. 

fexpr~ could do something similar, but the syntax would be simpler to have it this way.

**Comment by porres** [comment]
This doesn't really make sense. All signal objects in Pd can run on a "sample-by-sample" basis, but you need to use [block~ 1] in a subpatch so this happens. The [fexpr~] object can perform things like one sample feedback and all, but it'll still output a block of 64 samples and there's nothing specisl about it, many other objects are able to perform one sample feedback in the same way, like [rpole~], [biquad~].

I guess you can close this as the request doesn't really make sense.

**Comment by sebshader** [comment]
@porres hypothetically there could be some kind of JIT compiler that would compile to machine code like [faustgen~] https://github.com/CICM/pd-faustgen, in which case it might be more efficient than even [fexpr~].
Whether that's something that someone is going to want to spend time implementing is another matter.. perhaps heavy https://github.com/enzienaudio/hvcc would be a good starting point.
This might also be possible in an external somehow

**Comment by porres** [comment]
I'd love the idea we could compile Pd patches as objects, which is what Gen~ does, I've actually suggested that around 5 years ago but I have no real idea what it involves... 

anyway, this is not what this issue/request is about.

**Comment by porres** [comment]
@sebshader , maybe you wanna open a request for that?

**Comment by sebshader** [comment]
@porres it seemed to me like it was requesting, since that's what gen~ does (& also there might be no need for [block~ 1] since you could compile the code into a regular loop that iterates over blocksize samples.)

I guess gen~ is translated into an intermediate language which is then compiled to machine code. It would be cool to be able to use faust for this natively anyways. (perhaps make a new kind of canvas with objects that correspond to faust modules and then create a graph using them, then it could be compiled into faust code which then could be compiled to native machine code at runtime using a fork of faustgen~. all of this might be able to be accomplished in an external anyways though..)

**Comment by porres** [comment]
> there might be no need for [block~ 1] 

I can't see that, if you need a one sample feedback loop, you gotta have this.

> all of this might be able to be accomplished in an external anyways though

yeah, but I guess the point is to have this working natively, kinda like compiling with something like "heavy". Having an external that could do that, I don't know, what's the difference than coding externals then?

> it seemed to me like it was requesting

well, it isn't, he wanted all signal objects to be created with something other then "~" so could run with a block of size 1 and that doesn't really makes much sense. We can open a new request to discuss ways of compiling Pd patches as objects though, I'm all up for that.

**Comment by theslyprofessor** [comment]
I am going to close this request. I think the concepts within this thread are really cool, and they deserve their own suggestion.

**Comment by sebshader** [comment]
@porres 
> I can't see that, if you need a one sample feedback loop, you gotta have this.
if we implemented a gen~ style subpatch it wouldn't be necessary, because the entire thing would be compiled and run at whatever blocksize the parent patch would be and single-sample delays would still work since the entire patch is compiled

if the patch is compiled then instead of every object working with an array of sound data and filling the entire array one at a time, each object can processes the 1st sample in the block, then every object processes the 2nd sample in the block, etc.

because you are taking the entire patch and transforming it into a format that can essentially be put inside the iteration over the block. I hope that makes sense..

example concept of how the code runs for pd objects with blocksize:
object 1:
`for(i = 0; i < blocksize; i++) {
    output[i] = process1(i);
}`
then in object 2 that is connected to the output of object 1:
`for(i = 0; i < blocksize; i++) {
    out2 = process2(input[i], i);
}`
where input holds the output samples from object 1. now, if both objects were compiled into the loop it could be this:
`for(i = 0; i < blocksize; i++) {
    out1 = process1(i);
    out2 = process2(out1, i);
}`
in the first case, all of object 1's samples are computed, and then all of object 2's are. In the 2nd, for each sample the first object outputs a sample and then the 2nd one uses that sample. Then the 1st object outputs its 2nd sample and the 2nd object uses that, etc.
This has the result that you can achieve 1-sample delay at any block size of the parent patch, since instead of a "block" the computation is happening inside every iteration of a block
