### ISSUE TITLE
tabwrite should act sensibly upon out of bound address

### ISSUE THREAD

**Issue by WilliamAHuston** [pure-data/pure-data#1281]
[tabwrite] produces unexpected behavior upon out of bounds addresses.

In this example 3 element array, 
the first element of the array responds to any address <= 0 (only 0 is expected)
the second element responds to address=1 (expected)
the third element responds to addresses >= 2 (only 2 is expected(

Thanks!
BH

![image](https://user-images.githubusercontent.com/13723662/110070755-a6884d80-7d48-11eb-95da-3e4663fe9aa2.png)

**Comment by porres** [comment]
Do you mean it should ignore out of bound addresses?

As I see, this is intentional and works like feeding your input into a [clip 0 2], so it is some safeguard. Not saying this is good or bad, just what it is and that maybe, being a design choice, it won't change. Nonetheless, if so, a clear or better statement on this behaviour should be given in the help file.

**Comment by Spacechild1** [comment]
Yep, this is by design and can't/won't change.

> Nonetheless, if so, a clear or better statement on this behaviour should be given in the help file.

+1

**Comment by WilliamAHuston** [comment]
Agreed that this should be documented. Thanks.

**Comment by jamshark70** [comment]
Understood that this is by design, but it would be nice to have a mode to ignore out-of-range addresses rather than always clipping.

Typical precedent for out-of-range 'put' in other environments is to throw an error rather than to mutate the array at a different index from the one that was provided. Pd doesn't have "throw" but it could perhaps at least have the option to ignore.
