### ISSUE TITLE
oscparse gives numbers as symbols

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1299]
This seems to annoy everyone and I don't know if it's intentional, but [oscparse] outputs lists containing numbers that are treated as symbols and that is very unusual for Pd.

It also makes it a pain to use [route] as it can't route a message that starts with "0" as a symbol.

I wonder if we can change this by making it check and output a float instead. For those afraid of compatibility breakage, we could have a flag for that purpose, what do you say?

**Comment by Spacechild1** [comment]
To be clear: this only happens for numbers which are part of the address pattern. For example, `/foo/1/bar` would output three symbols "foo", "1" and "bar".

I agree that this is behavior is very unintuitive and it has come up a few times. However, I'm not sure if we should just fix this and risk breaking some patches, or find another solution, like adding a flag to `[oscparse]`.

**Comment by porres** [comment]
>  I'm not sure if we should just fix this and risk breaking some patches, or find another solution, like adding a flag to [oscparse].

I'm sure we gotta do something as when this happens, it's a lot of trouble. Why would you oppose to a flag?

The options I see are:
- fix it;
- fix it and create a compatibility flag;
- create a flag to force floats ("-f"?)
- make route deal with floats as symbols

not sure what else to do, maybe some new object or function that converts this easily to floats?

**Comment by Spacechild1** [comment]
> Why would you oppose to a flag?

I never said I would...

> * fix it;
> * fix it and create a compatibility flag;
> * create a flag to force floats ("-f"?)
> * make route deal with floats as symbols

Nr. 1 and 4. are out of question.

**Comment by porres** [comment]
sorry, now I get you were not sure if we should fix it (and then implicitly create a compatibility flag) or add a flag. Well, I'd be happy in one way or another... but if I were to pick a dog in the fight, I'd go for the fix + compatibility flag

**Comment by umlaeute** [comment]
otoh, what if the OSC-address is `/foo/1.00/bar`?
it is unclear whether the 2nd element (`1.00`) is meant to be a number or some weird symbolic identifier (with a zero-padded 2nd-level value).

not that it would be esp. easy to properly route `1.00`.

i'm just mentioning this to point out that blindly converting everything that looks like a number within the address is probably not what we want.

**Comment by Spacechild1** [comment]
IMO, it might be ok to only convert integers because that's the common use case.

**Comment by umlaeute** [comment]
including `01`, i guess.

**Comment by Spacechild1** [comment]
> including 01, i guess.

Which of course is parsed as an octal number. No, just kidding :-)

**Comment by abreubacelar** [comment]
are there other options? like instead of converting to float, make oscparse prepend an "\" when the path starts with a number? this would promote the whole path to symbol without doubt and route would work, right?

may seem confusing, but since this forces the whole number to be a symbol, it would work for all cases (but would break other cases, which is bad...)

1 would be \1
1.00 would be \1.00
01 would be \01

but if you make a symbol starting with a number, it would also be appended

\127.0.0.1
\1foo
\2.0-bar

and if \ is nonsensical, maybe / ? since paths also use / 

my suggestion is ugly, i know, but i am just thinking if there is another feasible way, since 1 or 1.00 or 01 aren't good to be routed as we have now anyway...

**Comment by umlaeute** [comment]
yep. i think l `/` (forward-slash) makes much more sense, as it doesn't modify the actual address-component.

**Comment by Spacechild1** [comment]
> my suggestion is ugly, i know, but i am just thinking if there is another feasible way, since 1 or 1.00 or 01 aren't good to be routed as we have now anyway...

I would also agree that it's very ugly ;-) Outputting a number as a symbol is exactly what we're trying to avoid.

Of course, `[route /1 /2 /3]` works ok, but that's only the simplest case. I often route messages *dynamically*, for example by treating the number part as an instance number for `[clone]`:

`/peep/1/note 60 100` -> `[oscparse]` -> `[list peep 1 pitch 60 100(` -> `[route peep]` -> `1 pitch 60 100` -> `[clone foo 64]`.

In this case, prepending a slash buys me nothing. In fact, it even makes it worse, because I would first have to strip the leading slash before converting to a number...

---

Personally, I now think the best compromise would be to add a flag to `[oscparse]`, so that address pattern components that look like numbers are output as Pd floats. (In this case we probably wouldn't even have to make exceptions for things like `/foo/5.7/bar` and just use the same parsing logic as for Pd messages.) We also wouldn't have to worry about breaking backwards compatibility.

**Comment by reduzent** [comment]
Personally, I'd be much happier if Pd has an official and generic way to convert from symbolic number to floats rather than having solved the same issue again and again on a case-by-case basis. I am not sure there is an advantage of a flag specific to [oscparse] over a generic converter object.

**Comment by Spacechild1** [comment]
>  I'd be much happier if Pd has an official and generic way to convert from symbolic number to floats

`[float]` has a symbol method which does exactly that.

But in the case of `[oscparse]` it's awkward that we have to split the message, convert one or more elements and join it again before being able to route it. So we're really trying to fix a quirk in `[oscparse]` here.

**Comment by reduzent** [comment]
> > I'd be much happier if Pd has an official and generic way to convert from symbolic number to floats
> 
> `[float]` has a symbol method which does exactly that.

Duh! 

> But in the case of `[oscparse]` it's awkward that we have to split the message, convert one or more elements and join it again before being able to route it. So we're really trying to fix a quirk in `[oscparse]` here.

Ok, makes sense.

**Comment by porres** [comment]
I don;t know now how to make an example where this shows :) anybody help me? would like to go for a fix and I need a simlpe pd vanilla patch to test.

**Comment by porres** [comment]
I guess this does it 
![Screen Shot 2022-04-10 at 04 01 00](https://user-images.githubusercontent.com/5360142/162606475-d1dd84ed-a091-4d32-9a07-f4decb03736a.png)
