### ISSUE TITLE
[documentation improvement] add mention of cents to mtof helpfile

### ISSUE THREAD

**Issue by hwkcgn** [pure-data/pure-data#1345]
at the moment mtofs helpfile reads: You can specify microtonal pitches as in "69.5" (a quarter tone higher than 69).
suggestion would be to add: The decimals specify cents as in .01 = 1 cent.

allthough it can be deduced from 0.5. being a quartertone, that this is 500cents, i think with the increased interest in microtunings recently, an extra mention of cents would have its merits.

**Comment by porres** [comment]
> 0.5. being a quartertone, that this is 500cents

50 cents actually

**Comment by sebshader** [comment]
.. perhaps part of the solution is to make it clear that each successive integer midi note is a semitone.
Because "cents" by definition refers to a 1/100th of something (a semitone in the context of western music), maybe we could just say:
"You can specify microtonal pitches as in "69.5" (a quarter tone, or 50 cents, higher than 69)" or something

**Comment by hwkcgn** [comment]
hell yes, sorry! too tired already...

**Comment by hwkcgn** [comment]
i like that better :-)
> "You can specify microtonal pitches as in "69.5" (a quarter tone, or 50 cents, higher than 69)" or something

**Comment by porres** [comment]
I'm being very descriptive... 

<img width="507" alt="Screen Shot 2021-06-26 at 12 58 34" src="https://user-images.githubusercontent.com/5360142/123518867-482c0580-d67e-11eb-8e50-7a6b06508548.png">

**Comment by hwkcgn** [comment]
looks very good to me, thanks!

**Comment by hwkcgn** [comment]
thank you miller,
a big small interval step :-)
