### ISSUE TITLE
Segfault when compiled with jack support on Linux.

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#146]
When compiling Pd version 0.48-0test5b with jack support and using the jackd2 version 2:1.9.11+git20170722-1~xenial2 that comes with KXStudio and should be similar to what's available from https://github.com/jackaudio/jack2 , Pd segfaults.

**Comment by millerpuckette** [comment]
Tried with jackdmp 1.9.11-RC1 -- I get those 3 warning messages about locking memory, but no crash yet.  I'm pretty sure I was running off 1.9.11-RC1 since I erased the installed jack.  Could there be confusion between jack versions over there?  I.E. maybe Pd's compilation saw one set of Jack headers but the shared library is from a different version?  (Just grasping at straws here.)

**Comment by millerpuckette** [comment]
Aha... I think I can get it to segfault now after all...  stay tuned :)

**Comment by millerpuckette** [comment]
ok, fixed and pushed... can you give the new (git repo) version a try?

**Comment by mxa** [comment]
YES! It works, thank you so much Miller.
