### ISSUE TITLE
'font' message to canvas makes patch dirty

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1511]
The following patch sets the dirty flat of the patch when the message is clicked:

```
[namecanvas $0.font-test]

[font 16 100 100(
|
[s $0.font-test]
```

Up to 0.51-4, this message didn't render the patch dirty. Since 0.52, GOP abstractions using this message for dynamically changing the font size of datastructure labels (for instance) trigger a pop-up when the main patch is closed: "Do you want to save changes in ..." . 

Since other dynamic modifications of the patch (creating objects, clearing a subpatch) do not set the dirty flag, I consider this a regression.

**Comment by sebshader** [comment]
I believe I did that in cd2d7f712f31c0718f63e69ceb89cdd4cabb43c4. (I should have opened a separate pr or mentioned something probably, sorry)
But imo it does seem like font should trigger "dirty" since font size is saved in the canvas when the patch is saved. (Like when objects are placed non-dynamically)

Maybe somehow the font size change should trigger "dirty" if done from the dialog, but not if done dynamically with a message?
A workaround would be to explicitly unset "dirty"..

**Comment by Spacechild1** [comment]
> Maybe somehow the font size change should trigger "dirty" if done from the dialog, but not if done dynamically with a message?

Yes, I think so. Here's a similar case: If you send the `[color(` message to an IEM gui object, the color is saved when the patch is saved, but the patch is *not* marked dirty. On the other hand, when you change the color from the properties dialog, the canvas *is* marked dirty.

**Comment by sebshader** [comment]
I'm wondering if the easiest way is just to have the tcl dialog just send "dirty" over the pipe also

**Comment by reduzent** [comment]
Can we label this as a regression? I think we agree on making patch dirty when using the menu is a good thing. When used as a message to canvas, it can become quite troublesome to close patches with many instances of GOP abstractions because of the many pop-ups triggered.
