### ISSUE TITLE
error(const char *fmt, ...) removed from m_pd.h in 0.52-1?

### ISSUE THREAD

**Issue by shakfu** [pure-data/pure-data#1530]
The error logging function `EXTERN void error(const char *fmt, ...) ATTRIBUTE_FORMAT_PRINTF(1, 2)` was removed from `m_pd.h` in 0.52-1. Yet, there's no mention of this in the release notes.

Considering this is a c-api change, Shouldn't it be marked for deprecation before removal?

S

**Comment by Spacechild1** [comment]
Yes, it should have been mentioned in the release notes. And yes, we should first deprecate API functions before removing them. Actually, there's a proposal for this:  https://github.com/pure-data/pure-data/pull/825

Note that the function itself didn't go away, it is just removed from `m_pd.h` because it clashes with https://man7.org/linux/man-pages/man3/error.3.html. This means that externals using Pd's `error` function will still load, but if you compile such externals from source, you either have to change all `error` calls to `pd_error` (= recommended) or provide you own forward declaration.

I think the `error` function won't come back, but @millerpuckette might add a note to http://msp.ucsd.edu/Pd_documentation/x5.htm#s1

**Comment by shakfu** [comment]
Thanks for the explanation.

Incidentally, I have seen many cases where `error()` has been used with only one argument as in `error("this is an error")`. `pdlua` is one prominent example.

Now if one replaces the above with `pd_error("this is an error")` it turns out that this is not allowed:

```c
error: too few arguments to function call, expected at least 2,
      have 1
    pd_error("this is an error");
```

So the non-breaking change assumption does not hold in such cases.

**Comment by Spacechild1** [comment]
If you replace `error` with `pd_error`, the first argument (`void *object`) must be 0. In your case it would be `pd_error(0, "this is an error")`.

**Comment by umlaeute** [comment]
> This can be done with a simple search and replace.

it can.
but it is almost always better to manually check each occurence of `error()` as most often you can actually pass an object reference to `pd_error()` (instead of just NULL).

> I think the error function won't come back, but @millerpuckette might add a note to http://msp.ucsd.edu/Pd_documentation/x5.htm#s1

agreed.
i'm thus closing this issue.

**Comment by Spacechild1** [comment]
> but it is almost always better to manually check each occurence of error() as most often you can actually pass an object reference to pd_error() (instead of just NULL).

+1
