### ISSUE TITLE
add [file isabsolute] and/or [file isrelative]

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1535]
It would be very handy to have objects for determining whether a file path is relative or absolute, e.g. `[file isabsolute]` resp. `[file isrelative]`.

Strictly speaking, we would only really need one of the two, but I think it doesn't hurt to have both. After all, we also have `[file isfile]` *and* `[file isdirectory]`.

**Comment by umlaeute** [comment]
hmm, i'd rather only have one, and i'd go for `[file isabsolute]` (simply because it maps to `sys_isabsolutepath`).

alternatives:
- Tcl provides a [`file pathtype`](https://tcl.tk/man/tcl/TclCmd/file.htm#M27) which would output a symbol `absolute` or `relative` (or `volumerelative`, whatever that is)
- an alternative way in Tcl to check whether a path is absolute or not is to use [`file normalize`](https://tcl.tk/man/tcl/TclCmd/file.htm#M25) to normalize the pathname and then check if it changed (not a very good test; but `[file normalize]` might be interesting nevertheless)

and btw: `[file isfile]` is *not* simply the negation of `[file isdirectory]` (at least on systems that have more types of "files" than directories and ordinary files, e.g. devices, named pipes,...)

**Comment by Spacechild1** [comment]
> hmm, i'd rather only have one, and i'd go for [file isabsolute] (simply because it maps to sys_isabsolutepath).

Yes, `[file isabsolute]` is probably enough.

---

> [file normalize] might be interesting nevertheless)

I also thought about such an object.

Actually, "normalize" does not necessarily imply turning a path into an absolute path. In some libraries/platforms, "normalize" is just a string manipulation, removing redundant slashes or resolving double dots between path components. They have a different function for resolving relative paths. In C++, for example, `std::filesystem::path` normalizes and `std::filesystem::absolute` resolves relative paths. Another example: https://stackoverflow.com/a/10823859/6063908.

**Comment by umlaeute** [comment]
things have been implemented in https://git.iem.at/pd/file

i only need to create a PR (and review the sources :-)

iirc, the main reason for stalling this is that @porres was updating the help-patches (including that of `[file]`) and i dodn't want to get into some conflict, so I'd rather wait until the #1517 got merged. 

see also #1539
