### ISSUE TITLE
OSC TCP UDP

### ISSUE THREAD

**Issue by janpanis** [pure-data/pure-data#1548]
Being a newby with PD (I'm a MAX user), I find it complex to use OSC in PD. I installed a number of libs (OSC and iemnet libs) and when I start their helpfiles they seem to work properly. Saving the patch and restart leaves me every time with unfound externals (can't load OSC lib is the message). Paths point to the right spot though. So only by copying an object from the helpfiles makes it happen. Are these libraries too old and therefore unsupported?

**Comment by reduzent** [comment]
When you open the help-files, they find their respective objectes because they reside in the some directory. When you use objects from those libraries in your patch, you need to tell Pd where they are by adding them to Pd's search path. You can do so by putting an object [declare -path iemnet] into your patch. The libraries you mentioned aren't too old nor unsupported. 

BTW: This is a good place for reporting issue and not such a good place for asking user questions. I recommend to use the Pure Data mailing list for such questions. 

https://lists.puredata.info/listinfo/pd-list

**Comment by reduzent** [comment]
Let me also add that you don't need any external libraries at all for sending and receiving OSC. Checkout those objects:
  * [netsend]
  * [netreceive]
  * [oscformat]
  * [oscparse]

**Comment by janpanis** [comment]
thanks for the fast reply and sorry for being on the wrong platform. Your tips work, but what’s the use of pointing to libs in preferences then?


Jan






     Panis Musical Engineering
     Jan Panis
     Cees de Jongstraat 2
     6523 RG Nijmegen NL
     gsm.: +31654378869
     email:  ***@***.***

**Comment by reduzent** [comment]
> Your tips work, but what’s the use of pointing to libs in preferences then? 

Adding the libraries in the preferences is specific to your local Pd installation. Using [declare] in your patch is specific to your patch. The latter is considered good practice since when you distribute your patch, users will immediately see what dependencies your patch has.
