### ISSUE TITLE
iemgui-merge bug with coords message

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1654]
this bug manifests for me when using the build for the https://github.com/pure-data/pure-data/pull/1633 PR, here's a screenshot and test patch.
[bug-test.pd.zip](https://github.com/pure-data/pure-data/files/8559797/bug-test.pd.zip)

![Screen Shot 2022-04-26 at 01 25 41](https://user-images.githubusercontent.com/5360142/165221087-f5e24815-09d2-431a-ba9a-e232b42da277.png)

basically, setting 'coords' message makes the label print on the top left of parent patch.

WEIRD

**Comment by umlaeute** [comment]
thanks for spotting this.

i think the underlying issue is with abusing `coords` as described by @Spacechild1 in #627:
> `[goprect(` redraws the parent canvas to avoid graphical artifacts ("ghost objects"). With `[coords(` and `[donecanvasdialog(`, you need to do `[map 0, map 1(` to achieve the same thing.

(and indeed sending a `[map 0, coords ..., map 1(` doesn't expose the problem; you could also do `[coords ..., map 0, map 1(` but the former should be faster)

however, since deleting iemguis has become much faster, a quick fix is to just delete the object before creating them anew...
