### ISSUE TITLE
Bug: numbers in message box turn into scientific notation after undo

### ISSUE THREAD

**Issue by timothyschoen** [pure-data/pure-data#1662]
To reproduce:

1. Create a message box
2. Set a message to a really large number like 100000000, close editor
3. Reopen editor, add an extra 0 at the end.
4. Undo.
5. Number has now turned into scientific notation.

I think it should at least be consistent with this, either always convert to scientific notation or never do it, don't reveal it to the user as a surprise at a later point.

Found in pd-0.52-2 on Mac.

**Comment by umlaeute** [comment]
that's the same behaviour as when reloading a patch (or just copying the msgbox around).

the underlying issue is, that Pd parses all input, and uses a normalized representation for storing the data (and Saving/Copying/Undoing uses that parsed data).
other programming languages (that have a strict separation between the editor and the runtime) do not have this issue.

so i understand that this is somewhat confusing, but it's not really related to <kbd>Undo</kbd>.

(as such i'm inclined to close *this* report; but a more general feature request for keeping a literal representation of an object's/msgbox's arguments might make sense)

**Comment by timothyschoen** [comment]
I understand, I'll close this report, it's only a small issue after all. I agree that storing the real value and the visual representation separately would be nice to have at some point.
