### ISSUE TITLE
Feature suggestion for savestate - Save/load savestate content to/from a .txt file

### ISSUE THREAD

**Issue by jaffasplaffa** [pure-data/pure-data#1666]
Hello :) 

I really like savestate, it's a great new addition to PD that makes present handling and recalling abstraction settings a bit easier.

But I'd like to suggest an addition to savestate.

I think it would be great to be able to save content from savestate to a .txt files. And also load a .txt file to savestate.

An example of where it could be useful:
Say you have the same abstraction loaded 2 times and for the first of them you have some nice settings that you want to copy to the second abstraction. If you could save/load savestate's content to .txt file, that would be pretty simple to do. But as it is now, it get a bit complicated.

Best wishes, 
Jaffa

**Comment by umlaeute** [comment]
how would you imagine to use that in practice (as in: how would a patch look like that wants to use that feature?)


otoh, it's really super-simple to add some logic to your patch that does just that:
- use `[textfile]` (or `[text]`) to store the list you would send to `[savestate]` (for saving the current state) into a textfile
- use another `[textfile]` (or `[text]`) to read that file and send it to the same objects that are connected to the first outlet of `[savestate]`

you could actually become adventurous and instead of using a file, just use `[send]` and `[receive]` to share the data between abstractions.

the tedious work is to arrange all relevant data in messages/lists so they can be sent readily to `[savestate]`, and then do the logic to restore the state from these messages.
you already have that (otherwise you wouldn't be able to use `[savestate]`).
the rest is simple.

**Comment by porres** [comment]
what you seem to want is a preset manager and being able to save your settings as a .txt, maybe load different settings into the same abstraction.

a proper preset manager for vanilla would be nice, [savestate] is not that but maybe it could be expanded for such, not a trivial thing to happen though.

What I did was create a preset manager with [savestate] and [text], check [else/presets]. Not all vanilla, but you can check it out.

**Comment by jaffasplaffa** [comment]
Thanks guys :) 

I also already made a preset system, using savestate and some tables:
https://github.com/jaffasplaffa/Pure-data-patches/tree/master/Savestate-Preset-System

Yeah I think now that you put it in perspective, it doesn't seem like it will do alot of difference to do that.
