### ISSUE TITLE
request; inserting and removing outlets in order for pack, unpack and trigger

### ISSUE THREAD

**Issue by ulioidle** [pure-data/pure-data#1673]
This would be a very useful feature. I made abstractions for this which use upper case letters to insert and - to remove, but they have failings and will never be ideal. Here is a gif of my abstraction for trigger to demonstrate what I am referring too. 
![tt](https://user-images.githubusercontent.com/8304564/170489616-1889b11d-081f-4433-a0db-698b13903885.gif)

**Comment by umlaeute** [comment]
do you know you can use triggerize (<kbd>Ctrl</kbd>+<kbd>t</kbd>) on `[trigger]` to:
- remove any unused outlet
- replace fan-outs with new outlets (of the same type)
- add a new left-most outlet
?

**Comment by ulioidle** [comment]
I did not know about these and I just did some quick searching and can find no mention of them in the manual, the reference, the change log or the three intelligent patching videos which I could find. Are these documented somewhere? I may have just missed them in my quick search. I prefer my solution as it provides a visual reference of the changes to be done and saves the extra step of deleting wires and changing types, but having control-t work for these functions on [pack] and [unpack] would be almost as good. 

Any other tricks like these which are not in the intelligent patching videos or is there a full list of these somewhere?

**Comment by porres** [comment]
I have it in my to do list to document intelligent patching and stuff like this... just opened an issue at https://github.com/pure-data/pddp/issues/92

**Comment by umlaeute** [comment]
while thinking about this, i'm not sure whether we should apply the triggerize logic to `[pack]` and `[unpack]`.

e.g. if i have a [trigger] object with a fan-out, then triggerizing it won't change the functionality of the patch.
however if we have an `[unpack]` object with a fan-out, then just adding a new outlet will change the logic of the patch.

i understand the desire, just am not sure how to properly deal with it.

**Comment by ulioidle** [comment]
I would guess by skipping the fan-in/out expansion for [pack] and [unpack] and limiting it too inserting at the beginning and removing unused, not ideal but better than nothing. Would need some other method for inserting.

**Comment by umlaeute** [comment]
the problem is, that an "unused" outlet of e.g. a `[pack 0 0 0]` object isn't just *unused*.

this gives you the 1st and the 3rd number of a list:
```
|
[unpack 0 0 0]
|            |
```

whereas this gives you the 1st and the 2nd number
```
|
[unpack 0 0]
|          |
```

but i guess you already know this :-)

so from a workflow perspective, i think we can rule out overloading <kbd>Ctrl</kbd>+<kbd>t</kbd> with an expand/contract for `[pack]`/`[unpack]` - simply because the *promise* of triggerize is to not alter the functionality of the patch.

otoh, i think we should stop adding keyboard-shortcuts for this and that (there's already too many). i possible solution to the shortcut problem might be a user-definable shortcut mapping (basically allowing the user to assign random shortcuts to any many action). i vaguely remember creating a feature request for this a couple of years ago, but cannot find it any more.

and think the issue at hand would require a keyboard shortcut or similar, in order to make sense (if i had to navigate the menu first, i could as well manually recreate/reconnect a `[pack]` object)

**Comment by umlaeute** [comment]
so in the spirit of intelligent patching, i wonder whether it wouldn't make more sense to just be able to shift groups of connections to the next/previous inlet resp outlet

![iolet-shit](https://user-images.githubusercontent.com/214034/171277947-29ad3e77-4985-42bd-9839-e0e605a014f8.gif)


with this, one could simply change `[pack 0 0]` to `[pack 0 0 0]` and then shift the incoming connections to the right to mimick an insert of a left-most inlet.
the fun part is, that this would be usable for all objects (not just a few hardcoded ones, like `[pack]`, `[unpack]` or `[trigger]`)

**Comment by ulioidle** [comment]
That would be pretty handy, Perhaps we can also shift only selected wires with the same command? So we could shift select that [pack], [unpack] and the first and shift it over as needed. This would also suggest having the selection rectangle include wires, perhaps the wires connect to just the inlets/outlets the rectangle envelopes to keep things sane, but that might be a bit too much as far as far as the code end goes?

**Comment by umlaeute** [comment]
yes something like this. (it was too comlicated for my simple mockup :-))

making multiple lines selectable would be nice, but is somewhat complicated without breaking ABI compatibility...

**Comment by umlaeute** [comment]
again, your suggestions will change the patch in a breaking way, which i don't think is a good idea.

but more importantly, i don't really like the idea of special-handling (more) objects.
why would you stop at `[pack]` & `[unpack]`? Why not add `[route]` & `[select]`? What about `[pak]`, `[zexy/unpack]`, `[readsf~]`, `[sfwrite]` and `[thrak]`?
