### ISSUE TITLE
There are 2 'preferences' in the 'Pd' menu

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1692]
Someone was confused by the fact that there were 2 'preferences' in the Pd menu. The 2nd one is actually 'Audio Settings' and should be called like that.

![Screen Shot 2022-06-10 at 16 32 41](https://user-images.githubusercontent.com/5360142/173137320-44b2cd4e-8b3d-4e56-800a-d0bfab463cbe.png)

**Comment by umlaeute** [comment]
this is a known problem with macOS automatic menu entries: the `Preferences...` entry is automatically created by your system; the only thing we can do about it is to assign some action to it (which we already do).

Pd doesn't have a single "Preferences" panel (as dictated by apple's enforced guidelines), but multiple entries, so there's not much we can do about it.

otoh, once #1397 get's merged this should be taken care of (or at leaset: it becomes simple to take care of this)

**Comment by danomatika** [comment]
>this is a known problem with macOS automatic menu entries: 

I wouldn't call it a problem, just a UI consistency enforced by the OS and implemented by the underlying TK Wish app. The same could be said of the About Pd menu item.

This has been mentioned before and IOhannes is correct: the Preferences menu item is always created by a Tk and there is *no way* to make it a menu list instead of a single entry, hence assigning it to a default action for and having a separate list for the dialogs. You can blame me for setting it to open the audio dialog, but that made the most sense at the time since that was the dialog I feel people need to open the most and you can do it with the Preferences shortcut: `CMD+,`.

The true fix, as IOhannes also mentions, is to provide a unified dialog which the Preferences menu item can then open.

**Comment by porres** [comment]
well, with the new changes, not anymore, cool
