### ISSUE TITLE
ggee/shell not working

### ISSUE THREAD

**Issue by rolfmeesters** [pure-data/pure-data#1697]
Windows 10, Pd 0.52.2

currently i get this error:

load_object: Symbol "shell_setup" not found
 shell
... couldn't create

(i must say it's quite some time ago i used this object)

rolf

**Comment by reduzent** [comment]
It is my understanding that this issue is totally unrelated to puredata. The proper place for opening an issue would probably be:

https://github.com/pd-externals/ggee/issues

On a related note, I was unhappy with [shell]'s implementation and created [command]:

https://github.com/pd-externals/command

which is also available in Deken.

**Comment by umlaeute** [comment]
seems that on github it's not possible to transfer issues to repositories in other "organisations" (like [pure-data](https://github.com/pure-data) and [pd-externals](https://github.com/pd-externals).

i'm therefore closing this as off-topic.
