### ISSUE TITLE
strange vulnerability [moses]

### ISSUE THREAD

**Issue by rolfmeesters** [pure-data/pure-data#1699]
![moses2](https://user-images.githubusercontent.com/4803897/174443065-35f7c3a4-a6be-4478-961e-d8279788007c.png)

doing a CTRL-1 in this canvas will change the cut-off of the [moses 80].
in my case most of the times it became 111( "o").

with 125 instead of 80 as original value ,  the 'new' cut-off became mostly 115 ("s").

a save of the patch does not contain the 'new' cut-off.

rolf

**Comment by umlaeute** [comment]
this is expected behaviour.
most (but not all) objects that have multiple inlets where each inlet expects a single float (or symbol), will *also* accept `list` messages and then automatically distribute the list atoms over the inlets.

this is documented in `2.control.examples/04.messages.pd` and in the [manual](http://msp.ucsd.edu/Pd_documentation/x2.htm#s6.4).

i'm therefore closing this as "not-a-bug"

**Comment by porres** [comment]
I have plans to also include this information in an abstraction for all help files, see https://github.com/pure-data/pddp/issues/96

**Comment by umlaeute** [comment]
i really think that adding the same same information to all (or: a large number of) help patches is adding noise and reducing the usability of the help-patches.
e.g. i find the "Dealing with $0" subpatches very annoying.


i think the tips-of-the-day would be a much better place for such common information. feel free to submit patches.

(the real place is of course `2.control.examples` where both the "spreading lists over outlets" and "using $0 for local names" are already covered in depth; but I guess people tend to not read this patches often enough, that's why i came up with tips-of-the-day in the first place)

**Comment by rolfmeesters** [comment]
umläute schreef op 18-06-2022 16:54:

> this is expected behaviour.
> most (but not all) objects that have multiple inlets where each inlet expects a single float (or symbol), will _also_ accept list messages and then automatically distribute the list atoms over the inlets. 
> 
> this is documented in 2.control.examples/04.messages.pd and in the manual [1]. 
> 
> i'm therefore closing this as "not-a-bug" 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

if this should be expected behaviour then the same should happen with 

[list fromsymbol] - [sel 100] 

and 

[list fromsymbol] - [+ 75] 

this is not the case. 

a.f.a.i.k. i only experience this with [list fromsymbol]. 

rolf 

Links:
------
[1] http://msp.ucsd.edu/Pd_documentation/x2.htm#s6.4
[2]
https://github.com/pure-data/pure-data/issues/1699#issuecomment-1159478421
[3]
