### ISSUE TITLE
metro unintuitive behaviour, change it or document it?

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1769]
I would assume and expect that below the first time I turn the [metro] on it would first wait 10 seconds after firing 500 ms, but it stars with the first period at 500 ms

![Screen Shot 2022-10-16 at 01 02 07](https://user-images.githubusercontent.com/5360142/196017371-6671bca1-674c-48c5-9104-f84d18944c24.png)

I guess I can see why it happens so I am reluctant to call this a bug, but it feels like it. If not, it's something to clarify in the documentation.

[test.pd.zip](https://github.com/pure-data/pure-data/files/9793561/test.pd.zip)

**Comment by fdch** [comment]
I would not call this behavior unintuitive. You can start the metro object at time _now_ with a `bang` which ideally triggers the metro at the same _now_ time, and after which following outputs are sent at the provided rate. So, starting the metro with a `1` at time _now_ should also trigger its first output at the same time.

**Comment by porres** [comment]
I guess my new documentation update takes care of this ambiguity

**Comment by sebshader** [comment]
Iirc this kind of thing can happen in some other similar situations as well, but I can't think of them exactly rn. Basically bc the ```outlet_bang``` in ```metro_tick``` happens before the clock delays, and so the bang triggers the timing to change before the delay occurs based on the current time.

Personally I do think that it is somewhat counter-intuitive because a ```[metro]``` will 'wait' to change the time until the next bang in any other scenario.

An easy 'fix' would be to change the order in ```metro_tick```

**Comment by Lucarda** [comment]
I think as @fdch. this is not "unintuitive behaviour" for me.

**Comment by umlaeute** [comment]
> overall I guess it's simplest just to use `[trigger]` at this point

how?

```
             _
|           /
[metro 10000]
|
[t b b]
      |
      [500(
      \_
```

```
             _
|           /
[metro 10000]
|
[t b b]
|
[500(
\_
```

...?


i personally don't really know whether it's good or not (so i summon the "it probably will break patches to change this" knock-out argument)

**Comment by porres** [comment]
> overall I guess it's simplest just to use [trigger] at this point

it doesn't really work. What does work is having [del 0] after metro.

> i personally don't really know whether it's good or not (so i summon the "it probably will break patches to change this" knock-out argument)

yeah, I see that. It is unintuitive to me but I guess https://github.com/porres/pure-data/commit/4fc143c1e206ccc41c536238eaa0fd2722d65f2b takes care of this, what do you think?

**Comment by sebshader** [comment]
for what it's worth I guess I think that what a user would want/intuit would be:
- to be able to stop the metro or change the time when it bangs when the clock callback happens (before the next clock gets set)
- but when it is first started, the time gets set after the clock is set (so the time doesn't impact the first hit)

I guess that is also inconsistent, but doesn't matter anyway since we're keeping current behavior
but to get the 1st hit aspect of that I think you could just use a trigger before the metro, to set the time after the metro is triggered/the clock is set?

**Comment by umlaeute** [comment]
> to be able to stop the metro or change the time when it bangs when the clock callback happens (before the next clock gets set)

why would they care, whether the next clock got set or not, as long as it doesn't fire?

> but when it is first started, the bang happens/time gets set after the clock is set (so the time doesn't impact the first hit)

so if i parse this correctly (but honestly, i think its unparseable), you agree with @porres initial assumption (as explained in the top-post)?

> but to get the 1st hit aspect

what's the "1st hit"? the 1st bang when the `[metro]` is started (which happens immediately)? the 2nd one (zero-based indexing :-))?

ah, you mean like so:

```
|
[t b b]
|     |
[500( |
\     /
 \   /
  \ /
   X
 _/ \_
/      \
[metro ]
|
```

but that doesn't align with my interpretation of your 2nd item ("but when it is first started...")

:confused:

**Comment by sebshader** [comment]
well that's exactly what I mean by 'when it is first started'..
as contrasted with every subsequent 'bang' that comes out of the ```[metro]```...

**Comment by umlaeute** [comment]
i think an idiomatic way (at least that is how i frequently use it) of using the output of `[metro]` to set the metro time, is creating a random metronome:

[![randometro](https://pastie.iem.at/view/raw/d6bc234e.pd.svg)](https://pastie.iem.at/view/d6bc234e)

changing the current behavior would probably be unexpected in such a use-case...

**Comment by porres** [comment]
that random example is what I used now in the help file update
