### ISSUE TITLE
Wrong placement of obj via shortcut after vslider or vu

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#1781]
Usually when auto-patching and creating new objects via shortcuts we have the next object created below the currently placed one. 

This works well for most objects, except for IEMgui’s vu and vslider because these have larger heights.

The object created via shortcut after the vslider gets placed behind the slider, which makes it difficult to edit its text. As a consequence, the keyboard-based patching flow gets interrupted for 2 seconds (*) to mouse-select and relocate the object. 

It would be nice to have the next object placed right after (ie. below) the vslider. 

(*) Those 2 seconds add up after a while, so I estimate a total of 1.3 hours of having done patches like this one:

```
[vsl]
|
[dbtorms]
|
[pack f 10]
|
[line~]
|
…
```

**Comment by umlaeute** [comment]
not fixable without breaking the pixel-exact layout of many people (otherwise i would have done so a while ago)

**Comment by fdch** [comment]
Well, I just thought of adding this issue given  #1776 has been under discussion. 

Perhaps special-casing iemguis can circumvent the issue by not entering into next obj’s text editing right away, so the obj is still usable for arrow-key relocation. 

But, I don’t understand why a solution might break layouts since the obj placement in question is the _next_ one, which means it does not exist yet :)

**Comment by umlaeute** [comment]
> Well, I just thought of adding this issue given https://github.com/pure-data/pure-data/issues/1776 has been under discussion.

i totally understand this. 

> But, I don’t understand why a solution might break layouts since the obj placement in question is the next one, which means it does not exist yet :)

the problem is, that the slider (and VU) are always offset.

consider this patch:

```
#N canvas 0 0 450 300 12;
#X obj 90 61 f;
#X obj 90 86 hsl;
#X obj 90 111 f;
#X connect 0 0 1 0;
#X connect 1 0 2 0;
```

looking at the X-coordinates (the first number after the `obj`), all three objects should be aligned perfectly along the X-axis.

however, the slider is off:
![align](https://user-images.githubusercontent.com/214034/196461637-14aa9415-8fb0-4d88-bd9b-99ded4a2c41b.png)

(there's also an offset with the Y-coordinate, but this is usually not so annoying...)

the auto-placement of objects just uses the "correct" coordinates, but the sliders/VUs add that weirdo offset (for the sliders, the reason is for the offset is, that for $reasons the slider "knob" was meant to be at the "correct" coordinate (rather than the sliders's outline/iolets; i have no idea why the VU is offset, probably for some related obscure $reason).

**Comment by fdch** [comment]
Thanks for your clarifications. I was not thinking of the `hslider`, or the rest. So, just for completeness, here's a screenshot on how the offsets are looking on macos:

![obj-offsets](https://user-images.githubusercontent.com/13335792/196484699-1a373b40-a9bd-431e-b4dc-134fa62d168b.png)

For the objects on the right of the canvas, there is simply no issue here. The object offset works well, except perhaps arguably for `cnv`

As expected, both X and Y offsets in `autopatch` are the same every time (except for comments, which stick to the mouse pointer)

- The X-coord extra offset you mention appears both int `hslider` and `vu`, and oddly enough, not in `hradio`.
- The equally-spaced Y-offset affects the taller `vsl`, `vu`, `cnv`, and `vradio`, who are just met with the same offset and simply have to live with being in front of the rest and wait for the user to get the mouse.

It is not such an annoyance, though, and I get a sense of the historical logic here, so it can be merrily ignored :)

**Comment by umlaeute** [comment]
Ah, so you were actually only concerned with oversized objects, rather than those "off the grid"?

Then I was misreading the issue (as I'm so annoyed by the misalignment, that I'm happy to find a fellow soul).

I actually think that oversized objects should not be too hard to do (it basically requires to use the actual size of the object, rather than its origin to calculate the next position)

**Comment by fdch** [comment]
> Ah, so you were actually only concerned with oversized objects, rather than those "off the grid"?

Yes, specifically with vslider because I use it very often. 

> ... (as I'm so annoyed by the misalignment, that I'm happy to find a fellow soul).
I completely understand the sentiment, so you are not alone with that :)

**Comment by fdch** [comment]
>I actually think that oversized objects should not be too hard to do (it basically requires to use the actual size of the object, rather than its origin to calculate the next position)

Thanks for this. I agree that the actual size of the object should be added to the vertical offset at the moment of creation. 

Would you say this is where the fix should happen? https://github.com/pure-data/pure-data/blob/f22066b0313fffc37f2ede674898e17c9ef7b1b1/src/g_text.c#L169 

To be precise, here's the _exact_ sequence of shortcuts to reproduce without a mouse:

1. Press <kbd>Ctrl + 1</kbd>: begin to create an object and leave it empty.
2. Press <kbd>Ctrl + 1</kbd>: begin to create a second object.  It should appear 5 pixels below the previous empty object, and autopatched
4. Type in `vsl`, but dont create the object just yet, because it is an artifact of the next step... 
5. Press <kbd>Ctrl + 1</kbd>: 
    a) the slider from the previous step is created, 
    b) and the current empty object appears 5 pixels below the no-longer-empty object from step 2.

**Comment by fdch** [comment]
Thanks so much, @umlaeute, for this truly amazing fix 🥇: it is quite elegant and very much welcomed. The comments are very helpful, too. I wish the rest of the code were commented like that. I hope it gets merged for this upcoming release.
