### ISSUE TITLE
oscparse confuses the OSC address with the OSC arguments

### ISSUE THREAD

**Issue by thomasfredericks** [pure-data/pure-data#1858]
In PD 0.53, the following OSC messages are all identical which can lead to messages being wrongly routed:
```
/a/b/c 100 ->list a b c 100
/a b c 100 -> list a b c 100
/a/b c 100 -> list a b c 100

```
![image](https://user-images.githubusercontent.com/2685516/209181097-aff679d8-12d5-4a84-a704-0ae3046a55b9.png)

While this specific example can seem trivial, using numbers in the OSC address greatly increase possible issues. See #1299

There should be way of having receiving the index that specifies the split between the address and the arguments OR add a flag that does not split and remove the / symbols from the address.

**Comment by porres** [comment]
what about https://github.com/pure-data/pure-data/pull/1623 ?

**Comment by thomasfredericks** [comment]
For my use and to conform to the OSC standard, I would much rather prefer a flag (let's say `-/`) to allow the output of the addresses unmodified. 
![image](https://user-images.githubusercontent.com/2685516/209205834-59fbf60d-03eb-4515-9d19-f8509b79b725.png)
I also wish there was a flag (let's say `-t`) to automatically trim the outputted list. The [list trim] seems superfluous.
![image](https://user-images.githubusercontent.com/2685516/209206119-2441e79c-4ee8-43fc-aa93-41edcae80011.png)

As a teacher, it is very complex to teach student's about OSC and the use of the `/` symbol to then move to PD and the `/` symbol vanishes.

**Comment by sebshader** [comment]
@thomasfredericks have you tried using ```[list tosymbol]``` instead of ```[oscparse]```?

**Comment by thomasfredericks** [comment]
@sebshader `[list tosymbol]` cannot convert OSC data. It simply converts ASCII. It can convert the OSC address but not the arguments.
![image](https://user-images.githubusercontent.com/2685516/209212209-09092c55-dd92-41a4-88ef-42fb78d8eb83.png)

**Comment by porres** [comment]
@thomasfredericks you're right that in Pd Vanilla you get things treated differently, the "/" vanishes, but I think this is a design choice that makes sense, because dealing with "/" in Pd Vanilla would be hard. The idea is that it is much easier to deal with lists and what we need is some information of where the address length is, like you requested.

My PR takes care of that and solves your issue as I see it https://github.com/pure-data/pure-data/pull/1623

If you want the object to have a different design, then it's something else and there are externals in Pd that actually do that

**Comment by reduzent** [comment]
> There should be way of having receiving the index that specifies the split between the address and the arguments

:+1:
