### ISSUE TITLE
sqrt~/q8_sqrt~ and rsqrt~/q8_sqrt~ are actually the same objects

### ISSUE THREAD

**Issue by sebshader** [pure-data/pure-data#1906]
I mentioned this on the mailing list but it seems like releases have come and gone..
the documentation should be updated to reflect that the classes are actually the same, and/or the implementation of the objects should be changed so that they're different. (my personal preference)

**Comment by porres** [comment]
for reference, see --> https://github.com/pure-data/pddp/issues/125

specially --> https://github.com/pure-data/pddp/issues/125#issuecomment-1353459554

and I quote Miller: "It's broken! sqrt~ should call the true function (the q8 version is a fast approximation). This will indeed require keeping a "compatibility" version (setting compatibility to 0.53 or earlier shold give the stupid old behavior and 0.54 onward should call a true sqrt function."

**Comment by porres** [comment]
good you opened this as I had forgotten about it :) now we can bug and make sure @millerpuckette doesn't forget it either ;)

**Comment by millerpuckette** [comment]
Turns out q8_sqrt and sqrt are synonyms.  Like osc~, they're good to 18 bits or so (I think) i.e., OK as long as not abused.  Letting sleeping dogs lie for now.

**Comment by porres** [comment]
@millerpuckette any plans to finally tackle on this?

**Comment by umlaeute** [comment]
i think there is nothing to tackle really.

the way i see it is:
- both `[sqrt~]` and `[q8_sqrt~]` give you the (approximate) value of the square root of the incoming signal
- both of them have finite precision
- the precision of `[q8_sqrt~]` is **≤** the precision of `[sqrt~]`
- the actual precision of either is implementation dependent

(this is somewhat similar to how integer values are defined in the C standard; a `short int` is guaranteed to be no longer than an `int`, but it is totally valid if both are 16bit (that is: they cover the same range ("have the same prevision"), *and* `int` is smaller than most people would expect))

**Comment by sebshader** [comment]
afaict sqrt() is part of c89, why not just use that for the higher-precision version? I don't get why there shouldn't be 2 implementations

**Comment by umlaeute** [comment]
i'm not saying that we cannot use `sqrt()`.
i'm only saying that i do not consider the current behaviour a *bug*.

**Comment by porres** [comment]
let me quote @millerpuckette from another issue https://github.com/pure-data/pddp/issues/125

"Hmm.. there must never have been a real sqrt object! Bizarre, and certainly my fault.
I think I should fix this for the next "major" release 0.54 so as not to make incompatibilities between bugfix versions. Also can consider "fixing" the cosine table at that juncture since I'm making an incompatibility anyway :)" https://github.com/pure-data/pddp/issues/125#issuecomment-1351836015

"It's broken! sqrt~ should call the true function (the q8 version is a fast approximation). This will indeed require keeping a "compatibility" version (setting compatibility to 0.53 or earlier should give the stupid old behavior and 0.54 onward should call a true sqrt function." https://github.com/pure-data/pddp/issues/125#issuecomment-1353459554

**Comment by Spacechild1** [comment]
> Also can consider "fixing" the cosine table at that juncture since I'm making an incompatibility anyway :)

+1

**Comment by porres** [comment]
fixd with https://github.com/pure-data/pure-data/commit/4718be1fff64d84ee47f038eaedd63c1dc22c563
