### ISSUE TITLE
unintuitive and inconsistent behaviour of "feedback protection" in iemguis

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1916]
So, iemguis have feedback protection, where you can set the same send/receive name and use it in a way that you can interact with the iemgui and it won't give you "stack overflow".

I am trying to document this behaviour throughly and I found inconsistencies between the bang button and sliders. I am testing with current 0.53-2!

In the screenshot below and the attached example, I have [send]/[receive] objects that interact with the GUIs.

For the slider, when I use [send] to send it a number, it is the same as using a 'set' message, which means that the data doesn't go through. This is unintuitive to me, but it seems like something that needs to be done in order for feedback protection to work and we need to maybe just document it. The problem though is that the bang button doesn't work in the same way!

If I use [send] to send it a bang, the message goes through and also reaches the [receive] destination. I am aware that [bng] does not have a 'set' message, unlike sliders, but anyway, it works... and if the two behaviours are inconsistent, I think it makes more sense that the 'bang
 behaviour is the standard one.

Similarly, if we have messages connected to sliders or bangs with feedback protection, the message sent to sliders just set the object value and it doesn't output it, whereas in bangs it goes through (again inconsistent). In this case, both messages do not reach the [receive] destination, which might be unintuitive but, again, necessary for the feedback protection mechanism. I would also agree that the bang behaviour seems to make more sense. 

Nonetheless, I think both ways are unintuitive, as the message does not reach the destination.

Hence, I just think that the feedback protection mechanism is wrong, besides being inconsistent, and it's really hard for me to understand what is the use case and why people rely on it.

feedback protection is also something we're considering adding to gui boxes (number/symbol/list boxes) as a way to make them more "iemgui-ish" and take a further step into deprecating [nbx]. But I think the whole mechanism ought to be reconsidered.

I am tagging @Spacechild1 as he required feedback protection for the gui boxes.

![Screen Shot 2023-03-13 at 15 58 38](https://user-images.githubusercontent.com/5360142/224803508-19837d6f-2e96-466a-adee-e8a3bb0302c8.png)

[fb-test.pd.zip](https://github.com/pure-data/pure-data/files/10960856/fb-test.pd.zip)

**Comment by Spacechild1** [comment]
> For the slider, when I use [send] to send it a number, it is the same as using a 'set' message, which means that the data doesn't go through. This is unintuitive to me, but it seems like something that needs to be done in order for feedback protection to work and we need to maybe just document it. The problem though is that the bang button doesn't work in the same way!

You are right that they behave differently and I don't see a technical reason for this. Of course, we cannot change really this behavior, but it needs to be documented.

The general idea about feedback protection is this: if an object has a send and receive symbol with the same name and it receives a message, it should not send the message to its "send" symbol because this would create a feedback loop. There is no technical reason why it shouldn't send the message through its outlet, but it simplifies the implementation a lot.

If you look at the code for `slider` and `bng`, you will notice that `bng` is much more complicated. On a closer look, it turns out that it is actually broken! Try to send two bangs at an interval of 0.1 second and you will notice that it will only output the first one. The problem is that `bng` "locks" the object once it receives a message and only unlocks it after 2 ms. This is really just a brittle hack.

`slider`, on the other hand, does something very simple: if both symbols are equal, it simply does not forward the message at all. AFAICT, this is the only sane thing you can do because there is no way to distinguish between a message sent from the object itself or a message sent by another object.

Personally, I never noticed this discrepancy because when I set the same name for "send" and "receive" I typically don't use the outlet. Float/symbol/list atoms wouldn't even have this problem because the inlets and outlets are deactivated :-) If we would lift this restriction, they should probably behave the same way as `slider`.

I would suggest to treat `bng` as the broken outlier and document it as such.

**Comment by reduzent** [comment]
I never noticed this inconsistency, probably because I usually use _either_ the xlets _or_ the send/receive. Since the behavior probably doesn't get changed - as Christof pointed out - it might be less confusing to simply advise users to "use either or".

**Comment by Spacechild1** [comment]
> Similarly, there is no way to distinguish between a message sent to the inlet or a message sent to the "receive" symbol, so you cannot forward it to the outlet, either. The only sane thing you can do is not forward at all.

Actually, I guess you *could* still send it to the outlet. I think the code in `slider` is just a bit lazy:
```
static void slider_float(t_slider *x, t_floatarg f)
{
    slider_set(x, f);
    if(x->x_gui.x_fsf.x_put_in2out)
        slider_bang(x);
}
```
It could have been this instead:
```
static void slider_float(t_slider *x, t_floatarg f)
{
    slider_set(x, f);
    if(x->x_gui.x_fsf.x_put_in2out)
        slider_bang(x);
    else /* only send to the outlet */
    {
        double out;
        if (pd_compatibilitylevel < 46)
            out = slider_getfval(x);
        else out = x->x_fval;
            outlet_float(x->x_gui.x_obj.ob_outlet, out);
    }
}
```
However, that still leaves you with the strange situation that sending a float to the inlet would forward to the outlet, but not to the "receive" symbol... (Again, an object does not know whether it receives a message via its inlet or via a bound symbol.) In that respect I think the current behavior of `slider` is actually more coherent.

**Comment by porres** [comment]
The fact that the float input to slider is pointless and weird can be easily reasoned in this particular feedback scenario, we just say that in this case one should NOT send values directly to the inlet of the object... it's clearly a special case and it makes sense. So we just say that people should use the send symbol! Done! Well, actually, by extension, we also tell them to NOT use the outlet connection for the same reason. No problem...

This information is not there and should be added...

The bang behaviour is different, inconsistent, buggy and etcetera... but if we follow the same rules, it should equally be fine. Maybe not even worth mentioning its rogue behaviour...

I'd be tempted to fix it, but I get it that it feels like fixing something that ain't broken... or better yet, that'll stay broken... and potentially may break some patch and require the need of compatibility flags...

**Comment by porres** [comment]
btw, I updated the documentation already...

> Float/symbol/list atoms wouldn't even have this problem because the inlets and outlets are deactivated :-) If we would lift this restriction, they should probably behave the same way as slider.

keeping inlet/outlets active are on the same list as allow feedback protection :) I might give it a go for adding at least these 2 features. Hopefully colors too...
