### ISSUE TITLE
hslider bugs out - when right-clicking to go to Properties - error on console

### ISSUE THREAD

**Issue by esaruoho** [pure-data/pure-data#1921]
PD0.50-2
When I try to right-click and choose Properties, to modify this slider - it kicks out:

```
(Tcl) UNHANDLED ERROR: wrong # args: should be "pdtk_iemgui_dialog mytoplevel mainheader dim_header wdt min_wdt wdt_label hgt min_hgt hgt_label rng_header min_rng min_rng_label max_rng max_rng_label rng_sched lin0_log1 lilo0_label lilo1_label loadbang steady num_label num snd rcv gui_name gn_dx gn_dy gn_f gn_fs bcol fcol lcol"
    while executing
"pdtk_iemgui_dialog .gfxstub600000d42c40 |hsl|             --------dimensions(pix)(pix):-------- 64 2 width: 17 8 height:             -----------output..."
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
```
[brokenslider.pd.zip](https://github.com/pure-data/pure-data/files/11008769/brokenslider.pd.zip)

**Comment by porres** [comment]
works fine for me... in Pd 0.53-2! 

![Screen Shot 2023-03-18 at 11 40 23](https://user-images.githubusercontent.com/5360142/226112909-3371bde6-d54a-402d-8459-079d795d7328.png)

Do you really have 0.50 or was it a typo? There is no point in opening an issue for a 3 years old version of the software. You have to use the latest version to see if the bug is actually still there...

And if you have 0.5**3**-2, what is your setup? You should always tell us more about your setup (and I'm still waiting for the setup on that free.rev~ issue you opened btw).

I'm on 0.53-2, Mojave (macOS 10.14.6), mac intel, Pd 64 bits.

**Comment by porres** [comment]
Now, I can see your label is "transpose_", and this might be triggering the error on the old Pd version... I can also see this does not display in 0.53-2 (even though no error is given) and this might be an unknown issue I believe... 

Thing is iemguis don't like labels to finish with an underscore... I tested and the atom boxes don't have a problem with it.

**Comment by esaruoho** [comment]
> Now, I can see your label is "transpose_", and this might be triggering the error on the old Pd version... I can also see this does not display in 0.53-2 (even though no error is given) and this might be an unknown issue I believe...
> 
> Thing is iemguis don't like labels to finish with an underscore... I tested and the atom boxes don't have a problem with it.

the `transpose_` is there because i use makefilename to talk to the label. so actually, when i load the full script, the label is `transpose_-0.498051` for instance. 

i'm using dynamic label naming to display what the hslider is sending out. so if slider was 0...127 - the naming would be (somethinginformative)_number
<img width="142" alt="Screenshot 2023-03-18 at 23 50 09" src="https://user-images.githubusercontent.com/4966687/226142158-35682232-5674-459e-9dd9-e83e4c5b03c8.png">

**Comment by porres** [comment]
It is not important why you use something that ends with "_", this is not being debated, I just mentioned it because it is a fact that it is a problem for iemguis and this should be the relevant information on this bug report.

I did ask you though to confirm your Pd version. "0.50" is old, test with the latest one to confirm that the issue you reported is not present.

also note you can use spaces inside labels in newer versions of Pd, so no need for underscores.

**Comment by esaruoho** [comment]
unfortunately, newer versions of pd choke even worse when i start sending data to multiple sliders that change their BG + slider colour depending on the volume amount. and no, i still don't know how to troubleshoot this so that it'd reasonably get fixed.

**Comment by porres** [comment]
let's try to stick to the point and not digress and mention other unrelated issues, I just wanted to confirm this issue is not present, as we need to rename it.

We need objectivity here in order to not get lost in a sea of comments, digressions and unclear issues. The issue you open doesn't really exist. I'd say you should close this issue as it already became a bit too confusing and I can open a new one just to address that iemguis won't display labels if they end with "_"

**Comment by porres** [comment]
I have a new issue --> https://github.com/pure-data/pure-data/issues/1924

 please close this one

**Comment by umlaeute** [comment]
i think i found the issue with your file: the hsl as saved on disk is corrupt.

you have
```
#X obj 233 236 hsl 64 17 -36 36 0 0 pst pst-rec transpose_ 0 0 9 1
7 -232576 -1 -1 0 1;
```

but as of Pd-0.50-2 these arguments do not make sense.

that is: Pd-0.50-2 accepts either 17 or 18 arguments, but in your patch you have 19 arguments.
thus, Pd-0.50-2 rejects all arguments and assumes defaults (which is the reason why the label does not show up)

now the interesting question is, why are the label et al available in the properties if the arguments are rejected?
the answer is, that the iemguis just use their on-disk representation (well: their binbuf) to get an unescaped version of their symbols (e.g. the label). since the on-disk representation is *not* discarded (nor re-initialized), and the send/receive/label symbols happen to be at the expected position, they are sent to the properties.

this does not really explain why the OP gets an error when trying to open the properties.

@esaruoho could you please run Pd from the cmdline and add `-d 1` for debugging, so we can see the actual message that is sent to the GUI. capture the output and attach it to this issue.

something like the following line should produce a "pd.log" file which contains the interesting bits:
```
pd -d 1 brokenslider.pd 2>pd.log
```
(i would have been more specific, but unfortunately i cannot find where you put your OS-information)

**Comment by esaruoho** [comment]
> > unfortunately, newer versions of pd choke even worse
> this might be so, but i don't think it has been reported.

there was a request for the smallest possible case that causes it, but when i tried to reduce my script to the bare necessities, i ended up destroying the original script a bit. but if i ever come across a way to get the lagginess to happen, with say 1 or 2 abstractions, i'll definitely attach a zip to a new issue.

> in any case: even if we do find a bug and fix it, this bugfix will go into the next Pd release. chances are slim (practically _nil_) to get a Pd-0.50-3 that has this fix.

that's perfectly alright :) i'm currently happily using 0.53.2 - but suffering from the lag caused by "multiple sliders visually changing color when moving" issue. 

> i think i found the issue with your file: the hsl as saved on disk is corrupt.
> ```
> pd -d 1 brokenslider.pd 2>pd.log
> ```

interestingly, when i enable -d 1 and load the brokenslider.pd that "definitely broke" with 0.50-2, using 0.50-2, i don't  get an error when opening the Properties. i'll try to get it to happen again. am really confused by this, tbh.

**Comment by umlaeute** [comment]
> interestingly, when i enable -d 1 and load the brokenslider.pd that "definitely broke" with 0.50-2, using 0.50-2

and if you remove the `-d 1` again?

**Comment by porres** [comment]
@esaruoho can you help us a bit more?

**Comment by esaruoho** [comment]
> > interestingly, when i enable -d 1 and load the brokenslider.pd that "definitely broke" with 0.50-2, using 0.50-2
> 
> and if you remove the `-d 1` again?

it did not seem to have any effect. i'm not sure if i was doing it right, but i was following the commandline arguments and trying `-d 1` and without it. i did not seem to get any specific change.

**Comment by umlaeute** [comment]
> it did not seem to have any effect.

i'm not sure how to read this.
1. you get an error
2. adding `-d 1` [makes the error go away](https://github.com/pure-data/pure-data/issues/1921#issuecomment-1477041342)
3. removing `-d 1` has *no effect*?

so is the *no effect* that the error is still gone?

**Comment by esaruoho** [comment]
@millerpuckette i realize this is now closed, but how do i figure out which build / release version will have this supposed fix?

**Comment by millerpuckette** [comment]
As soon as I can get a proper release together :) - I'll put out a test release as soon as I've gone through the dozen or so PRs that look too urgent to wait any longer on.

**Comment by esaruoho** [comment]
> As soon as I can get a proper release together :) - I'll put out a test release as soon as I've gone through the dozen or so PRs that look too urgent to wait any longer on.

thank you, eagerly expecting and waiting to see how the sliders perform this time (since i use lots of visual gui processing to make them more dynamic and display data and the slider lines changing colour and background slider colors changing depending on how loud they are)

**Comment by umlaeute** [comment]
the fix for *this* issue was to forbid broken hslider invocation (as in your patch).
there is no reason to belief that the performance has changed for good or worse (at least not from the fix for this issue).
