### ISSUE TITLE
Ctrl+Q confirmation dialog

### ISSUE THREAD

**Issue by kubriel** [pure-data/pure-data#1956]
Hallo!
Sometimes happen to me to hit Ctrl+Q unintentionally, when i operate my computer in dark and/or chaotic environment. Its just next to Ctrl+W which i use often when navigating between patches and subpatches. If patch is not saved - good, because there will be confirmation dialog to save it. But during performance patch is often saved, and this can be dangerous. Is there reason why there is no "Are you sure to quit" dialog?

best

kubriel

**Comment by Spacechild1** [comment]
> Is there reason why there is no "Are you sure to quit" dialog?

I think because that's the way most apps work.

On the one hand, most users expect the app to quit immediately when they hit Ctrl+Q (and there is nothing to save). On the other hand, I can totally see how one can accidentally hit Ctrl+Q in a performance. It's a bit of a conundrum. A typical solution would be to show the confirmation dialog the first time and have a checkbox "Don't ask me again". (Of course, it should still show the dialog if there is unsaved state.)

**Comment by porres** [comment]
maybe you should rely on keyboard shortcuts for performance situations. I know I did that once as well and sice then it never happened again because I now don't rely on it...

But if you have to, in your performance patch you can just send a 'dirty 1' message to your canvas and it will save you. You can even make an abstraction/external if you wish

**Comment by fdch** [comment]
Slightly OT: I have patches in which I add a [quit( message to pd to use them without GUI so they quit pd after finishing. This is very useful for recording a performance in non real-time.  But, I often use those same patches for live performance! It happened to me more than once that I forgot about the quit message  and cut very nice endings. Now, I always have a spigot for those cases…

In any case, having a “disable quit” flag would be useful, but on second thought, it might be more useful to have customizable shortcuts.

**Comment by Spacechild1** [comment]
> but on second thought, it might be more useful to have customizable shortcuts.

+1

**Comment by umlaeute** [comment]
what's wrong with `[; pd perf 1(`

seems to be *exactly* what you are looking for.

**Comment by porres** [comment]
> what's wrong with [; pd perf 1(? 

where is that documented?

**Comment by umlaeute** [comment]
http://msp.ucsd.edu/Pd_documentation/x5.htm

**Comment by fdch** [comment]
I can’t believe I missed this “perf” message! Thanks for pointing that out!!

**Comment by Spacechild1** [comment]
I would not regard release notes as documentation. Do you think Pd users should read through all release notes of all Pd versions to learn about features?

Even as a longtime Pd user (and develper), I haven't been aware of this (very useful!) message. 

---

BTW, this is a general problem with message to "pd". Since the latter is invisible, you cannot do "right click -> help".

@porres IIRC, you have collected all "pd" messages in some kind of help patch, but I can't find it. Has this already been merged to master? Anyway, I think that help patch should be placed prominently, probably in `help-intro.pd` ("List of objects...").

**Comment by umlaeute** [comment]
i think it would be a good [tip-of-the-day](https://github.com/pd-externals/tipoftheday-plugin/issues/new/choose)

**Comment by Ant1r** [comment]
This is a job for the TipOfTheDay ;-)

**Comment by Spacechild1** [comment]
I really like the idea of tip-of-the-day, but it is not a replacement for actual documentation. I mean, how many times would you need to open Pd until that specific tip would be shown to you? ;-)

**Comment by umlaeute** [comment]
you know that you can get more than one tip at a time, don't you? (that probably should be another tip-of-the-day).

of course i'm not opposed to also document this in some `-help.pd` patch. but why would I go looking at `intro-help.pd`  if I want to keep Pd from quitting when i accidentally hit <kbd>Ctrl</kbd>+<kbd>q</kbd> (my point is that there are things for which it is impossible to find a place for the documentation where it's actually found; TipOfTheDay tries to solve this)

**Comment by Spacechild1** [comment]
> but why would I go looking at intro-help.pd if I want to keep Pd from quitting when i accidentally hit Ctrl+q

Ah, I was talking about "pd" messages in general and didn't realize that you were only talking about the Ctrl+Q issue in particular. Sorry for the confusion.

**Comment by porres** [comment]
I did document these pd messages in 'pd-messages.pd', it is referred to a few times, likeas a 'see also' in the help file of messages, where it fits better I guess. I checked the source code and missed this cause I didn't know what it was. I'll add it too now

**Comment by Spacechild1** [comment]
>  did document these pd messages in 'pd-messages.pd'

Ah, right! May I suggest also adding a (prominent) reference to `help-intro.pd`? 

>  I'll add it too now

🙏

**Comment by porres** [comment]
sure, I can do that... now, what I also need is to know what exactly this message does so I can document it :)

**Comment by Lucarda** [comment]
see https://github.com/pure-data/pure-data/blob/master/doc/1.manual/x5.htm#L715-L717

**Comment by porres** [comment]
any other message I should document that I'm missing in "m_glob.c"?
