### ISSUE TITLE
[clone] resize issue?

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1993]
sorry i can't be sure of whats going on but it seems that if I use the new 'resize' message to [clone] in this situation here I get errors and Pd crashes.

I am using an external [nchs~] to get the number of channels and resize [clone] and at first I thought that there could be something wrong with it, but now I don't believe it anymore. The object is really simple and in any case here's the code https://github.com/porres/pd-else/blob/master/Classes/Source/nchs~.c

I've been using this object nicely in other occasions and it only crashes here.

Now for a screenshot

![Screen Shot 2023-06-16 at 00 12 07](https://github.com/pure-data/pure-data/assets/5360142/55898bc5-c0cd-4066-b067-8f54fe8e5424)

I get Pd to output errors like 

consistency check failed: ugen_start;
consistency check failed: signal_dereference

When I try to connect the second oscillator into the right inlet of [snake~ in] and sometimes Pd crashes.

Now, one way I can prevent the issue from happening is disconnecting the output of the 'resize' message into [clone] so I suspect that it might be related to this new feature 

patch attached but you need to compile [nchs~]

[test.zip](https://github.com/pure-data/pure-data/files/11765749/test.zip)

ping @Spacechild1

**Comment by Spacechild1** [comment]
```
static void nchs_tilde_dsp(t_nchs *x, t_signal **sp){
    x->x_nchans = sp[0]->s_nchans;
    nchs_bang(x);
}
```
Never ever send a message directly from the "dsp" method - always use a clock!

In the patch above, `[else/nchans~] -> [resize( -> [clone]` causes a recursive call to `canvas_start_dsp` which is a recipe for chaos.

I'm closing this as "user error" :-) I will also push a fix to develop that detects such recursive DSP calls and prints an error message.

---

As a side note: I think `[else/nchans~]` should either have a "bang" method or send a bang in the "dsp" method - but not both! Personally, I would tend towards the former because it is more consistent with `[samplerate~]`. You can always emulate the latter with `[r pd-dsp-started] -> [else/nchans~]`.

**Comment by porres** [comment]
> Never ever send a message directly from the "dsp" method - always use a clock!

thanks, any example out there on how to use a clock in it?

**Comment by Spacechild1** [comment]
Use `clock_delay(x->x_clock, 0)`. Or just don't send a bang in the first place (which I would recommend).
