### ISSUE TITLE
get-message to [list store] always yields first value only

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pure-data#2013]
Tested on M2 Mac with the current build from http://msp.ucsd.edu/Software/pd-0.54-0test1.macos.zip

I don't know since when this behaviour occurs since i probably didn't use this functionality for a while - so not sure if it changed recently or in previous builds (and also not completely sure if i'm doing anything wrong). To reproduce (also visible in the [list store] help though):

* send message [1 2( to right inlet of [list store]
* send message [get 1 1( to its left inlet
* expected result: output of second list value (2).
* actual result: 1

The same happens with a [get 0 -1( message, which should output the whole list. A [bang( works in this case though.

**Comment by Spacechild1** [comment]
Thanks for the report! The problem was a wrong function prototype that would cause undefined behavior in double-precision Pd.

(IIRC, the macOS test build actual contains the double-precision version, for whatever reason.)

This should be fixed on develop with a721cbb9bf7e22a28fa6e899c0cfce879722f689.

---

@umlaeute, @millerpuckette: I did a quick check and I could not find any other offending methods in Pd itself, *but* there is a good chance that some externals just use `float` instead of `t_floatarg` - which can cause all kinds of weird behavior. Just something to be aware of!

**Comment by ben-wes** [comment]
thanks for the quick reaction! i admit i didn't even realize that i was working with a double precision version there (saw this only now when trying to load zexy).

confirming this fix with the double precision build from https://git.iem.at/pd/pure-data/-/jobs/52997
(switching back to single precision here for now though until some common libs are available through deken).

**Comment by Spacechild1** [comment]
Thanks for the confirmation!
