### ISSUE TITLE
missing .h files in 0.54-0

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2043]
Hi, tried compiling ELSE against the new release and I get 

Classes/Source/note.c:12:10: fatal error: 's_utf8.h' file not found
#include "s_utf8.h"

this header file used to be there in the 'src' folder of the Pd application in 0.53-2 and now that I look inside it I see many other header files missing in the new release if compared to the old one.

Just checking if this is intentional and what would it be the best practice for me now with this case.

thanks

**Comment by porres** [comment]
oj, "s_utf8.h" and "s_utf8.c" are still in the full source code of pd of course

**Comment by umlaeute** [comment]
it's fully intentional: this is a private header of Pd and should not be used by externals (besides: none of the symbols are exported and therefore not useable on Windows anyhow).

i did a casual check why ELSE is using it, and the `#include "s_utf8.h"` seems to be just a totally unnecessary copy-paste thing, so the proper fix is to cleanup ELSE.

**Comment by Spacechild1** [comment]
> besides: none of the symbols are exported and therefore not useable on Windows anyhow.

This is not true. With GCC/Clang `_declspec(dllexport)` is just a synonym for `__attribute__((dllexport))` and implies default visibility. Since GCC/Clang export all symbols by default, the behavior is the same on all platforms.

@porres Side note: you can always use private Pd functions without the headers, you just need to write your own forward declarations - and pray that the function signatures won't change. Needless to say, you really shouldn't use private functions in the first place :)

**Comment by umlaeute** [comment]
Well, of course I know nothin' about Windows, but I'm pretty sure that at least a Pd compiled with MSVC would not give you those symbols.
We currently do not build with MSVC (and thanks goodness for that), but I think the assumption that all the symbols are exported anyhow is invalid.

I think we should reduce symbol visibility anyhow, and will submit a PR (for 0.55) - at least, if I haven't done so yet...

**Comment by Spacechild1** [comment]
>  at least, if I haven't done so yet...

I don't see a PR, but you have opened an issue: https://github.com/pure-data/pure-data/issues/569

**Comment by porres** [comment]
> seems to be just a totally unnecessary copy-paste thing, so the proper fix is to cleanup ELSE.

I dont get it, should I just remove this header? 

I have to say I don't know why it is there actually... seems it had to be used for building on windows only. I see all I'm using is the 'u8_dec' function and i don't know why it is not needed to declare for mac and linux

**Comment by umlaeute** [comment]
> I dont get it, should I just remove this header?

yes.

> I have to say I don't know why it is there actually... seems it had to be used for building on windows only. I see all I'm using is the 'u8_dec' function and i don't know why it is not needed to declare for mac and linux


oh, there *is* a use in your sources (i thought otherwise).
that's gonna be a bit more problematic.

**Comment by Lucarda** [comment]
@porres i remember deleting this headers some time ago because on Pd-Windows-sources we never had the utf8 files so it refuses to compile. And it was working. the functions were correctly found in pd.dll

commit https://github.com/porres/pd-else/commit/1221849d60ea43320c8990420592d56f7be9bdc0

I don't kmow why or when they come back.

**Comment by umlaeute** [comment]
and I also found the source of *my* confusion.

Apparently I did *not* check `ELSE`, but I did check with `cyclone` (as the latter is packaged for Debian, and the former is not).
And while `cyclone` does include the header file, it does *not* use any its symbols, so the inclusion can be safely removed there.
- https://github.com/porres/pd-cyclone/issues/627

**Comment by Spacechild1** [comment]
>  i remember deleting this headers some time ago because on Pd-Windows-sources we never had the utf8 files so it refuses to compile. And it was working. the functions were correctly found in pd.dll

Again, *never* use functions without declarations. See https://github.com/pure-data/pure-data/issues/2043#issuecomment-1622353993

**Comment by carlthome** [comment]
Having the same issue when compiling cyclone. Should we just copy s_utf8.h into https://github.com/porres/pd-cyclone/tree/master/shared/control instead?

```sh
❯ nix build .#cyclone
error: builder for '/nix/store/212fa8d4bvm33wa2qk8zh719bhfrmn40-cyclone-0.7-0.drv' failed with exit code 2;
       last 10 log lines:
       >       |                            ^
       > ++++ info: linking objects in rminus~.pd_linux for lib cyclone
       > gcc -rdynamic -shared -fPIC -Wl,-rpath,"\$ORIGIN",--enable-new-dtags    -o rminus~.pd_linux cyclone_objects/binaries/audio/rminus.o  -lc -lm
       > ++++ info: making cyclone_objects/binaries/control/comment.o in lib cyclone
       > gcc -DPD -I "/nix/store/qx2ks8r4kcx5xggbk3yspqmblfyir2if-puredata-0.54-0/include/pd" -DUNIX  -fPIC -Ishared -DHAVE_STRUCT_TIMESPEC -Wall -Wextra -Wshadow -Winline -Wstrict-aliasing -O3 -ffast-math -funroll-loops -fomit-frame-pointer -march=core2 -mfpmath=sse -msse -msse2 -msse3 -o cyclone_objects/binaries/control/comment.o -c cyclone_objects/binaries/control/comment.c
       > cyclone_objects/binaries/control/comment.c:21:10: fatal error: s_utf8.h: No such file or directory
       >    21 | #include "s_utf8.h"
       >       |          ^~~~~~~~~~
       > compilation terminated.
       > make: *** [pd-lib-builder//Makefile.pdlibbuilder:949: cyclone_objects/binaries/control/comment.o] Error 1
       For full logs, run 'nix log /nix/store/212fa8d4bvm33wa2qk8zh719bhfrmn40-cyclone-0.7-0.drv'.
```

**Comment by umlaeute** [comment]
No

**Comment by porres** [comment]
that'd be a cyclone issue
