### ISSUE TITLE
add an object for MIDI "MPE"

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2117]
I don't really have a MPE aware controller or ever really used MPE. I only have a faint idea of what it is.

Nonetheless, it's been a while since this is part of the world and it seems to me that Pd should deal with it natively...

All I found in the wild was this external, oops, here it is https://github.com/DanielRudrich/pd_mpe not sure how good it is, I will probably look into it eventually, it's on my list now. I thought about maybe designing a new external for ELSE, but it really looks like Vanilla should handle this

**Comment by porres** [comment]
> All I found in the wild was this external

oops, here it is  https://github.com/DanielRudrich/pd_mpe

**Comment by porres** [comment]
as I wrote to the pd list, MPE uses noteoff messages, which aren't handled by vanilla objects such as [notein], hence, we can't fully deal with it with just abstractions. We either need a proper object or add a noteoff velocity option for [notein} (maybe a -release flag, where it'd only output note off messages).

**Comment by abreubacelar** [comment]
you can get noteoff velocity through [midiin] object

using [midiin] -> [print] with my roland juno-di, i get:print: 144
print: 60
print: 71
print: 128
print: 60
print: 120

120 was the release velocity

**Comment by porres** [comment]
>  I don't expect people to "easily" retrieve note off messages and build mpe abstractions with it and document it as such

let me elaborate on this over here. I mentioned in the Pd list that we could indeed maybe just use objects like [notein], [ctlin], etc, to handle MPE reasonably well, and that I could document this on the help file and leave it alone, but not having a good solution for noteoff ruins this idea.

**Comment by unclewayback** [comment]
Hello, further to email on the list, I have uploaded two abstractions to a new repository, in case you want to look at/reference them: https://github.com/unclewayback/knotty

There are only two abstractions there: midi-up.pd is a vanilla midi parser which handles note off velocity and other things. mpe-izer.pd uses else/voices because it was an easy way to change the amount of voices on the fly. It is designed to receive note, pitch, timbre and pressure messages, and to reroute them to cloned abstractions - the fiddly bit is to do with getting MPE on 16 channels but then perhaps routing to less clones... there might be simpler ways around it, it is a while since I played with this one but was working fine with cloned instances of [vstplugin~] 

I'm working on other things at the moment but just dropping these here in case useful!

**Comment by porres** [comment]
> I'm working on other things at the moment but just dropping these here in case useful!

This is nice, but I'd find it useful if it had at least a help file with examples on how it works, that'd be nice... :) I usually don't feel like testing stuff that don't make it quite clear how it , works by trying to guess and figure it out. midi-up seems straightforward, but doesn't really add anything to the discussion. It's like a vanilla version of else/midi.in, right?

cheers

**Comment by porres** [comment]
> (An mpe 'zone' is just a channel split - only two are provided for on my Linnstrument, and perhaps the spec in general: an upper and a lower - each split has its own 'master channel' (for things like cc7 volume) and a number of voice channels which it tends to round robin. So for instance split/zone 1 = master channel 1, voices 1-8; split/zone 2 = master channel 9, voices 9-16 ... a master channel is just to avoid sending redundant messages.)

how would you know in a pd patch wether something is coming in zone 1 or 2? I mean, if you don't know before hand how things are configured of course

**Comment by unclewayback** [comment]
Sorry for the delay, out of internet here since some storms, just borrowing a friend's to check in - yes midi-up is just like a vanilla version of your midi.in, I reckon. Plan to do help files and all that good example stuff when I'm a bit more together, thanks for the tip/prompt! 

Re: MPE zones, they are configured on the MPE instrument normally, and how it translates to the patch is through what midi channels it is listening for - in other words the user would set up a synth to be played midi-channel per-voice on say channels 9-16, and that would be zone 2 or hi-split, and 1-8 zone 1/low... basically a keyboard split, to play, sent as a midi channel split to the patch, which would have to be set up to listen on those channels via a message of some sort. Cheers!

**Comment by unclewayback** [comment]
you wouldn't know, at least not automatically/as it is... the user would have to somehow tell the patch to listen only on the midi channels corresponding to the split they want that patch to represent. I guess you could do something simple like with a keyboard split, where they could tell the patch where to split by telling the patch to listen and then hitting a key, which in this case would have to correspond to a midi channel... or you could specify that they send an nrpn or something like that to set the split point.

**Comment by porres** [comment]
> or you could specify that they send an nrpn or something like that to set the split point.

This is what I think it has to happen, and the one thing that requires a special external or something. Maybe it's what the object in MAX can do that we can't with vanilla objects

**Comment by unclewayback** [comment]
I was thinking the other night: MPE sends channels as round robin, therefore it would probably be possible to tell if a split is being used without being explicitly instructed? If the patch is keeping track and expecting a linear repetitive count through the channels, cycling 1-16/0-15, it could detect a break in this pattern which may indicate a split being used? This would be a pain in the arse to implement, and I don't think it would be fool proof/it would require checks because the pattern breaking isn't guaranteed to happen first time. So, I'm not sure it's worth bothering with, but perhaps it could be done somehow, due to the implementation of 'round robin'...

**Comment by porres** [comment]
I have added an external into my library and info on how to manage this in vanilla with the help file, so I'm closing this
