### ISSUE TITLE
cannot uninstall pd (0.53-2)

### ISSUE THREAD

**Issue by H-MLim** [pure-data/pure-data#2179]
![image](https://github.com/pure-data/pure-data/assets/68152553/3eebc392-cf56-4c2b-8179-d18193ea3dc7)

hi. I'm using now 0.54-1, but this old pd still remains in my computer after uninstall it. moreover, it outputs the error message "cannot find C:\Program Files\Pd\uninst.exe". how could I fix it?

**Comment by umlaeute** [comment]
ping @Lucarda

**Comment by Lucarda** [comment]
Hi,

Most likely this happened because you manually deleted `C:\Program Files\Pd` and this is not good. but of course it can be fixed. Please read all before doing anything.

you can manually delete the "dirty" registry or use the installer to fix everything for you.


## using regedit.exe

you can open `regedit.exe` and look for these keys:

- If Pd 0.53-2 was installed for all users: 

  - `Computer\HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\Pure Data`

  - `Computer\HKEY_LOCAL_MACHINE\Software\Pure Data`

- if installed for just for your user:

  - `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Pure Data`

  - `Computer\HKEY_CURRENT_USER\Software\Pure Data`

you can delete these keys by right-clicking in the left pane `Pure Data` folder and hit "delete"

## using Pd's installer

I'm not sure how you are using Pd-0.54-1, if you use the zip package or did an alternate installation or an user level installation but if you want to have 0.54-1 installed normally and a clean registry:

 - uninstall 0.54-1 (does not apply if it's not installed) but use the uninstaller and **do not** manually delete it's folder
 - run 0.54-1 installer.
   - here the installer will tell you that 0.53-2 is installed and will ask you to "run the uninstaller" but ignore it.
   - select "continue" and install Pd to the default `C:\Program Files\Pd` folder
     - voila, this will overwrite the registry with correct values and your pic above will only show the 0.54-1 installation.

**Comment by H-MLim** [comment]
hi. thank you for your help! but I'm afraid I couldn't find any folder named `Pure Data` from all regedit directory you suggested, nor installer showed me about 0.53-2. still 0.53-2 is remaining in my computer. other else is wrong?

**Comment by Lucarda** [comment]
i'm not sure if i can help. deleting the the reg keys was not what i recommended.

do you remember when you manually deleted the `C:\Program Files\Pd` folder?

**Comment by H-MLim** [comment]
I'm afraid I'm not...at least last year? I'm not sure.

**Comment by Lucarda** [comment]
i'm pretty sure you manually deleted `C:\Program Files\Pd`. if i'm incorrect there should be lots of users reporting that bug.

you can open `regedit.exe` and go to menu edit/find and search for `C:\Program Files\Pd`. there should be many matches that we are not interested. after a match you need to do edit/"find next".

you can also search for `C:\Program Files\Pd\uninst.exe`

but be careful with te `Windows registry`. you can easily mess things up. I recommend that you do the `using Pd's installer (recommended)` procedure mentioned above.

also at the point i said: "select "continue"" its the 4th radio button below "run the uninstaller". also make sure to first uninstall 0.54-1. it should appear right below the first pic you posted. there you should get to the "uninstall" option.

**Comment by H-MLim** [comment]
yeah I also tried the installer you mentioned. I uninstalled it once. but I can't see any texts like 

> -here the installer will tell you that 0.53-2 is installed and will ask you to "run the uninstaller" but ignore it. when I click Next several times, it just installs 54-1 without asking anything. maybe I'm doing wrong something?

![image](https://github.com/pure-data/pure-data/assets/68152553/484f4f7e-6767-4bc4-beb1-7e681a26ab0b)

**Comment by Lucarda** [comment]
ok,

uninstall Pd 0.54-1.

open `regedit.exe` and on the left pane click on the top `computer` folder. search for `0.53-2`. do `find next` until all the registry has been searched.

post a pic on every match. or delete all the folders at the left pane containing that match.

**Comment by H-MLim** [comment]
![image](https://github.com/pure-data/pure-data/assets/68152553/17a03029-6e3d-40d0-8426-22212b7635be)

ok...I found this match. can I delete whole Pure Data (64-bit) folder?

**Comment by H-MLim** [comment]
oh wait. I deleted it and finally it's gone. HURRAY! thank you so much for your help.

**Comment by Lucarda** [comment]
:)

**Comment by Lucarda** [comment]
also there might be a chance that you find it on other places. delete them all.

:)
