### ISSUE TITLE
Unexpected behavior for reblocked subpatch with multichannel-outlet

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pure-data#2192]
this report is based on the assumption that it's valid to combine a reblocked subpatch with a multichannel `[outlet~]` (so if that's not the case, this can be closed right away).

when i do this here, i get different (unexpected) signals though compared to the version with separate outlets.

here's a little patch with `[block~ 1]`ed subpatches to compare and illustrate both behaviors:
[compare-1sampleblock_mc-outlet.pd.zip](https://github.com/pure-data/pure-data/files/14195251/compare-1sampleblock_mc-outlet.pd.zip)

**Comment by Spacechild1** [comment]
Thanks for the report! This indeed a bug. Note that this only happens when reblocking to *smaller* blocksizes. I will investigate!

Just a small tip: when making a bug report, try to reduce the example to the absolute minimum that is necessary to demonstrate the problem. Here I just used simple `[phasor~]` objects and also made the blocksize settable:

[mc-outlet-reblock-bug.zip](https://github.com/pure-data/pure-data/files/14201426/mc-outlet-reblock-bug.zip)

If you try a blocksize of 32, it becomes more clear what's going on.

**Comment by ben-wes** [comment]
thanks! and noted - i'll try next time! was coming from a more complex patch that i reduced. should instead have created a new minimum patch showing the error without the previous one in mind (as you did - no need for the s~/r~ feedback obviously).

and i see that the signals are somehow alternating with slopes and offsets that correlate with the channel count. this looks kind of logical for channel counts of 2^n (also when reblocking to smaller block sizes). but for 3 channels or so, i really don't get it.

**Comment by Spacechild1** [comment]
Phew, this hasn't been easy to figure out (mostly because of the unnecessarily terse code and complete lack of comments). It should be fixed with 7a924ada4f286a66d4297a9715db305116b03eac on the latest develop branch!

**Comment by ben-wes** [comment]
confirming that it works as expected now for all the cases i tested (including other block sizes and channel counts). thanks a lot for the fix!

**Comment by Spacechild1** [comment]
thanks for double-checking!
