### ISSUE TITLE
class_addcreator() yields error on macOS/arm64

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pure-data#2199]
this is a minor issue. it looked to me like errors, but actually everything does work as expected nonetheless (meaning: the objects mentioned below are actually working).

i'm also not sure if this is an issue of the libraries that cause these error-level outputs or if it's related to unexpected behaviour through changes in Pd. i'm reporting this here since it doesn't happen with the official Pd0.54-1 build.

context:
* current develop-branch, macOS, arm64, sonoma 14.3.1
* Gem from Deken, ver: 0.94.git v0.94-843-gc6eff7f12 (2024-02-05)

simplest way to reproduce:
* add `declare -lib Gem` to new patch

outputs (error level):
~~~
class pix_texture2: sorry: only 5 creation args allowed
class pix_gray: sorry: only 5 creation args allowed
class pix_colourreduce: sorry: only 5 creation args allowed
class pix_colourmatrix: sorry: only 5 creation args allowed
class pix_colour: sorry: only 5 creation args allowed
class pix_colouralpha: sorry: only 5 creation args allowed
class pix_put: sorry: only 5 creation args allowed
class pix_get: sorry: only 5 creation args allowed
class pix_depot: sorry: only 5 creation args allowed
class pix_separator: sorry: only 5 creation args allowed
class pix_a_2gray: sorry: only 5 creation args allowed
class pix_2gray: sorry: only 5 creation args allowed
class colourRGB: sorry: only 5 creation args allowed
class colour: sorry: only 5 creation args allowed
class Gem: sorry: only 5 creation args allowed
~~~

(also seeing similar errors/warnings for pmpd externals)

**Comment by umlaeute** [comment]
i can reproduce this with Pd-0.54-1-22-gc863bbec (but not with Pd-0.54-1).

i think this is actually a problem with Gem, rather than Pd (I will move the ticket once i am more confident)

**Comment by umlaeute** [comment]
i've run some tests and the problem is indeed with Pd itself (rather than Gem).

the issue is that in `class_addcreator` the test for the terminating `0` type is never met: https://github.com/pure-data/pure-data/blob/0259d00373b9e6f3bc1d76eebc5b243283ca7063/src/m_class.c#L568-L577

i'm slightly puzzled by this, as printing out the value of `*vp` does show `0`, but it doesn't compare to `0`.
probably i need to get a real debugger...

**Comment by umlaeute** [comment]
it actually turns out, that Pd is throwing a number of similar errors for its  internal aliases (`my_canvas`, `my_numbox`, `inlet~`, `outlet~`, `template`, `drawcurve`, `filledpolygon`, `filledcurve`, `drawsymbol`, `drawnumber`, `i`, `f`, `s`, `r`, `select`, `sel`, `t`, `fswap`, `v`, `list`, `scalar`, `vd~` and `snake~`), we just don't see them because:
- the GUI is not there yet when they are printed (so run in a terminal)
- `pd_error()` is suppressed for whatever reasons at this stage (replace the `pd_error()` printout with `post()`)

**Comment by umlaeute** [comment]
interestingly enough, when compiling Pd-0.54-1 on macOS 12.5.1 "Monterey", i get the same errors. :shrug:

**Comment by ben-wes** [comment]
thanks for the fix (and the detailed checks and notes on the build context)! ... tested here with a local `Sonoma` build (clang version 17.0.6, target: arm64-apple-darwin23.3.0). looks good.

... so this means that with another official build on `Mojave`, this wouldn't have been an issue at all? seems more future-proof now, of course - but anyway: sorry for reporting a develop-only-problem then!
