### ISSUE TITLE
List creation argument as abstraction symbol argument (e.g. $2) not working

### ISSUE THREAD

**Issue by brianlindgren** [pure-data/pure-data#2204]
I'm trying to give a list a creation argument via an abstraction's creation argument (which is a symbol). "list" does not work but "list append" does. I was under the understanding that 'list' is a short version of 'list append'? Am I missing something?

<img width="277" alt="Screenshot 2024-03-06 at 3 43 49 PM" src="https://github.com/pure-data/pure-data/assets/92063518/1e7e44b3-8b4c-4463-af9d-972c04d499f2">

**Comment by porres** [comment]
you can't give the creator as an argument, the creator symbol is not an argument! And yes, just [list] is short for [list append], so what you have is [list append symbol] which is illegal and fails... 

I will just close this as it is not a real bug/issue but maybe we can discuss how this becomes clearer in the documentation

**Comment by porres** [comment]
> 'list' is a short version of 'list append'? Am I missing something?

without a creator symbol, it calls 'append' but what you're trying to create is [list whatever] which is not a valid creator.

I will just close this as it is not a real bug/issue but maybe we can discuss how this becomes clearer in the documentation

**Comment by Spacechild1** [comment]
Just to clarify: `[list]` is indeed a shortcut for `[list append]`, but it only works if the subsequent creation argument is not a symbol:

`[list 1 2 3]` -> ok
`[list foo bar baz]` -> error

The reason is that a symbol argument would ambiguous as it could be interpreted as a list method name ("append", "prepend", "lenght"). Note that we might add more list methods in the future, so we cannot just check against the existing set.

**Comment by Spacechild1** [comment]
The help patch only says "[list]: short for append". I think it could be more explicit.

**Comment by porres** [comment]
It's on my [list]

**Comment by brianlindgren** [comment]
I see, this makes sense - thank you for the clarification!
