### ISSUE TITLE
[pdcontrol] cannot browse page marks for local HTML files

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2231]
I'd like to use [pdcontrol] in the documentation to refer to an exact subsection of the manual, but a link such as https://msp.ucsd.edu/Pd_documentation/x4.htm#s1 doesn't work.

well, it does work for a link on the web, but not if I am specifying an htm file in the pd app, such as 
![Screen Shot 2024-03-26 at 15 32 26](https://github.com/pure-data/pure-data/assets/5360142/1f2fb023-0486-4691-8314-e0f8b39fb1ec)

I get an error instead

![Screen Shot 2024-03-26 at 15 35 05](https://github.com/pure-data/pure-data/assets/5360142/a02be636-e94f-42a5-9f6a-6b6aedcafee0)

**Comment by umlaeute** [comment]
that seems to be a problem with Apple's `open` wrapper, rather than with Pd.

(the following is pure conjecture, but i think it is about right):
- using an http-URI, `open` selects your default web-browser as the application to start, and then passes the entire string (including the `#`) to the application. the web-browser knows how to deal with page anchors.
- otoh, if you do not pass an URI which pre-selects the application to `open`, then there is little it can do to guess which application it should use to handle that string. usually it will try to interpret the string as a filename, check the type of the filename and then pick an application that can handle the given filetype.
- this works great if you pass an HTML-file, which is of mime-type `text/html`, which in turn is handled nicely by... a web-browser.
- it doesn't work if you add `#foo` to your string, because now the string you are passing is a valid filename (nothing keeps your from creating files like `/tmp/foo.html#bla` or `/Users/porres/###/#pdrules`) but it no longer refers to an existing file, so `open` cannot determine which program to use to open the string, and accordingly fails.

i'm afraid this is a `wontfix`.

see also: 
- https://apple.stackexchange.com/questions/194501

**Comment by umlaeute** [comment]
we could of course make the error a bit nicer.

also, hasn't this been reported/discussed before?

**Comment by Lucarda** [comment]
is there any possibility to treat the canonical `file:///` as if it was `http://` and not a `regular file` ?

so we do `[browse file:///$1/x2.htm#s2(`

**Comment by umlaeute** [comment]
I thought about suggesting that, but on writing I do not see any obvious way why this should actually work.

In the end, the "browse" method is a very thin wrapper around the system's "open this" functionality (and I don't think it would be a good idea to overload it with some special casing).

So the best fix would be to file bug reports against your system's "open this" functionality.

**Comment by Lucarda** [comment]
Ok. 

just to report on Windows when opening a local file:

- `[browse file:///$1#s2(` --> opens the file but ignores the anchor.

- `[browse $1#s2(` --> nothing happens. (not even the tcl error).

- `[browse $1(` --> works as expected.

**Comment by umlaeute** [comment]
thanks for actually trying it out!

so now i did the same on my linux system:

- `[browse $1(` --> works as expected (obviously no anchor)
- `[browse $1#s2(` --> opens an error dialog (with vanilla Pd, this is a system-specific error dialog; with Debian Pd (which has been patched to allow installation without the documentation) a Pd specific dialog opens up, telling me that the file could not be found, and i should probably install the `puredata-doc` package)
- `[browse file:///$1#s2(` --> opens the file and navigates to the anchor :tada:




so it seems @Lucarda 's inituition to use `file://` was right(y): either the anchor is followed or ignored (which is much better than just throwing an error). maybe macOS behaves similar?

**Comment by umlaeute** [comment]
just did a quick test on a macOS-10.12 ("Sierra") and using a ´file://`-URI, the anchor is ignored (just like on Windows, according to @Lucarda)

**Comment by Lucarda** [comment]
strange:

@umlaeute reports

- [browse file:///$1#s2( --> opens the file and navigates to the anchor 🎉

this does not work for me on latest Debian bookworm `lxqt`. (latest Pd, wish, compiled and started via `./pd`)

**Comment by umlaeute** [comment]
On Linux things are a bit complicated, as there is no standard way to just "open a string". So worth Pd we try a couple of options, and they might work differently on our systems (I haven't checked which path is taken in my case).

The point is, that the additional anchor does not get in the way (and in some cases even works)

**Comment by Lucarda** [comment]
I see. i remember an ugly hack for this that implements doing an dummy `.html` that redirects to the anchor. ugly but useful.

https://lists.puredata.info/pipermail/pd-list/2018-05/122535.html

**Comment by umlaeute** [comment]
Hmm, I'd rather not (create redirecting pages for each anchor)

I would just use `file://...#...`, even if most OSs don't resolve the anchors.


The documentation is still fully integrated, even if anchors don't work.

**Comment by Lucarda** [comment]
We are not planning many anchors see https://github.com/pure-data/pddp/issues/191#issuecomment-2025285272

i'll switch the PR to draft. We rather not include it?

**Comment by Lucarda** [comment]
> I would just use `file://...#...,`

some minor correction: it is with 3 slashes `file:///...#...`

**Comment by Ant1r** [comment]
> 3 slashes

I'm not sure, I believe the third slash is actually the first slash of the path, so it's really: `file://path`, with `path` starting with a slash because is an absolute path.

**Comment by Lucarda** [comment]
> 3 slashes

i think they are 3 `file:///F:/porres-puredata/pure-data/doc/1.manual/index.htm`  pasted from Windows Chrome. Path here starts `F:/`

**Comment by Lucarda** [comment]
it also works for me on Windows with 2 slashes. Probably 2 slashes is correct.
