### ISSUE TITLE
Pd seems to "remember" the -verbose option

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#2301]
Let's say I do `pd -verbose` and then open a patch that contains abstractions. When setting the loglevel to "All", I can see the verbose output in the console, as expected.

Now, if I do same again, but this time with just `pd`, I can still see the verbose output! It seems like Pd "remembers" the previous `-verbose` flag; I have to explicitly run `pd -noverbose` to "clear" it.

Is this expected behavior? For me this looks like a bug because command line options are typically not saved.

**Comment by umlaeute** [comment]
two remarks:

1. it's true that this is inconsistent with how `path` and `libraries` are handled. but it's also somehow consistent with how audio and MIDI settings are handled. i think the main issue is the user interface of the preferences. If you start Pd with `-verbose`, do you want to see (in the preferences) that Pd is in verbose mode or not? if the former, the GUI becomes a bit awkward. but then... we probably could live with the latter
2. i cannot reproduce the issue the way you describe it. in order to have `pd -verbose` persist the verbosity flag, you must save the preferences. now changing the loglevel does save *some* prefs (namely the loglevel on the Pd-GUI), but not the `verbose` flag. are you doing something else as well?
   (i take it i did not misread your question: the verbosity (a core setting) is orthogonal to the loglevel (a GUI setting). the latter takes effect immediately and is always save to the last used value. the former can only be set at startup)

**Comment by Spacechild1** [comment]
Hmmm... I cannot reproduce it anymore. I guess I must have accidentally save the settings... Nevermind.
