### ISSUE TITLE
Missing help: sorry, couldn't find help patch for "pbank"

### ISSUE THREAD

**Issue by nyponen** [pure-data/pure-data#2352]
I tried to get help on [pbank] in the patch I found here:
https://forum.pdpatchrepo.info/topic/12506/example-of-reading-a-text-file-line-by-line/3
but Pd issued the message: sorry, couldn't find help patch for "pbank"

**Comment by ben-wes** [comment]
which help patch would you expect to open in this case?
the zip file i see there doesn't contain a help patch. `[pbank]` is obviously an abstraction that is part of this zip and not a native Pd object. Pd will try to open the files `pbank-help.pd` and `help-pbank.pd` from the defined paths when you try to open its help (you can see that in the console with log level 4). but since none of these exist, you get the mentioned error message. this is expected.

**Comment by nyponen** [comment]
Sorry, I thought the post was saying that [pbank] was part of vanilla Pd.
