### ISSUE TITLE
couldn't find help patch for - all

### ISSUE THREAD

**Issue by clavisound** [pure-data/pure-data#2490]
Hello there.

With version 0.50 help.pd files are working (right click > help).
With version 0.55 help.pd files are not working.

In both cases help browser is working (ctrl + b)

Any idea what is wrong?

System slackware-15 both versions of pd created with https://slackbuilds.org/slackbuilds/15.0/audio/pd.tar.gz

In version 0.55 files help.pd are in place, but not found by pd with right click. `strace` was not helpful. I can't understand the paths that pd is looking. I tried to start `pd` with `-path /usr/lib64/pd/doc/5.reference/`. Again failure.

Thanks.

**Comment by umlaeute** [comment]
expects the help-patches to live in either `../doc/5.reference` or `../lib/pd/doc/5.reference` (relative to the `pd` binary itself).

if your distribution does not adhere to this scheme, it needs to fix the paths as well (aka: please report this as a bug to the slackware package, rather than here).

related:
- #2901
- #2095

**Comment by clavisound** [comment]
Thanks, it seems solved with a link `ln -s ../lib$LIBDIRSUFFIX/$PRGNAM/doc/5.reference ./` in `$PKG/usr/doc`
