### ISSUE TITLE
GUI properties and radiobutton interaction with enter key is inconsistent

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2493]
In GUI's properties, for the entry boxes, when you hit 'enter' it goes to the 'ok' button - and things get applied in macOS - but if you select the same entry box or another one instead, the focus from the 'ok' button is removed. In the case of the radio buttons this is not the case. You can hit enter and it'll focus the 'ok' button, but if you choose another radio button setting the 'ok' button keeps highlighted.

**Comment by porres** [comment]
I'd also like to refer to this another issue https://github.com/pure-data/pure-data/issues/1836 where I suggest we can use finer font sizes for patches and GUI boxes. This would change the design of the properties a bit but we could keep using radiobuttons for the main selections and add an entry box for other possibilties (kinda like the sample rate thing in audio settings)

**Comment by umlaeute** [comment]
how is the "finer font sizes" related to "radiobutton interaction with enter key"?

(i understand this ticket to be a reboot of #2484, trying to disentangle unrelated issues, but then you start entangling them again).
---
having that said, i still do not understand what your actual problem is (i just see various combinations of the words "ok", "other", "boxes", "same", "enter" and "radio"; it might be just me though.)

**Comment by porres** [comment]
I think I want to relate issues so they could be worked out together on the same PR or something. These two seem quite related for that.

Now let me break the issue and workflow problem to you on macOS

When changing the font size of a number box in the properties, I expect that the font size would change immediately, as this is the usual behaviour and does work like that for radio buttons in iemguis, for instance.

That doesn't happen, but that is another issue, see https://github.com/pure-data/pure-data/issues/2492 for reference. Nonetheless, this forces me to hit enter to apply things in macOS and that highlights the 'OK' button in properties. It actually selects the button, so I can hit enter again and it will close and act on the 'ok' button. That is expected behaviour and what we have to do in macOS!

Now say I don't actually like the setting I did, and I want to try another size. The thing now is that the change is not automatically applied and I have no way to apply it unless I hit enter. But since the 'ok' button is already 'selected', that closes  the properties window. It's just a bad and confusing workflow.

One way to 'fix' this is that when you choose another setting in the radio button, then the 'ok' button gets deselected. This is how things actually work for the entry boxes in the properties. You can type in something and hit ok to apply and check the result. If it is fine you can hit enter again to close the window and be done with. If you don't like you can click on the entry box again to try something else and that action deselects the ok button. 

This issue is about that, being able to click on the radiobuttons and deselect the 'ok' button when doing so.

The reason why I also brought this up with the other issue (radiobuttons aplpying changes automatically on macOS) is that I think this can be a sufficient stategy to fix this workflow. You can select the changes until you see what you are happy with and then hit enter twice, to select 'ok' and close the window.

This is why I think both this and https://github.com/pure-data/pure-data/issues/2492 are specially intertwined as both affect this workflow. But they are indeed separate issues that can be tackled independently. 

And now that I think of it, this would also make sense not only in GUI boxes but also iemguis... and thinking a bit more, could be quite complex and maybe not actually doable with tcl/tk. 

Seems like https://github.com/pure-data/pure-data/issues/2492 is simpler to deal with and would do the job.

Is this making any sense now?

**Comment by umlaeute** [comment]
> These two seem quite related for that.

then i would like to ask you to just do that, and don't add noise. e.g. a line that says `Probably related: #1836` would be enough (and just edit your original post if you forgot to mention it in the first round).
as it is (well: *was*), you created a bug-report of 80 words, and then took 60 words to explain another issue. this is just not a good S/N ratio :-)



> I think I want to relate issues so they could be worked out together on the same PR or something. 

in the end it is up to whoever creates a PR to fix whatever issues there seem fit. i do not think it is helpful to pre-empt their decisions into what they want to include in the PR.
if you already know that the two issues can be solved in a single go, then you probably know how to fix them in the first place - in which case i think you should actually submit a fix (rather than - or at least in addition to - a bug-report).

**Comment by porres** [comment]
> if you already know that the two issues can be solved in a single go, then you probably know how to fix them in the first place - in which case i think you should actually submit a fix (rather than - or at least in addition to - a bug-report).

I'm not yet comfortable in working with tcl/tk, but I'm actually looking into that :) trying to succeed in making externals with it first...

anyway, having a good thought about it, https://github.com/pure-data/pure-data/issues/2492 seems sufficient and I might be able to try and give it a shot soon. Hopefully I can include other issues and fixes and you can help me revising and approving them.
