### ISSUE TITLE
[WIP] usable mingw32 builds

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#25]
currently, Pd-for-windows is built with **both** `msvc` (to create a usable `pd.lib`) and `mingw32` (for the distributed binary).
it seems that the *pd.lib* as created by *mingw32* is not really usable, yet.

this should of course be fixed.

here's a few tests if the created binaries are usable (*new* means Pd-binaries/libs/externals created solely by mingw; *old* refers to the traditional double-compilation)

- [ ] the new `pd` loads
- [ ] the new `pd` can load *new* externals
- [ ] the new `pd` can load *old* externals
- [ ] an *old* `pd` can load *new* externals
- [ ] an existing external can be built (linked) against the *new* `pd.lib` using mingw (without modifications of the build-system)
- [ ] an existing external can be built (linked) against the *new* `pd.lib` using MSVC (without modifications of the build-system)

**Comment by danomatika** [comment]
+1 This is the main issue to solve for the autoools_updates branch.

**Comment by Spacechild1** [comment]
my configure-line for 
- disabling JACK (to avoid long wait times)
- making sure that ASIO and MMIO show up in the media menu:

         ./configure --enable-asio --disable-jack --enable-portmidi  --disable-locales --enable-mmio

**Comment by Spacechild1** [comment]
I did a pull and now compilation fails on the extra folder (it used to work before). the error is:

Making all in bob~
make[3]: Verzeichnis „/c/Github/pure-data/extra/bob~“ wird betreten
/bin/sh ../../libtool  --tag=CC   --mode=link gcc -mms-bitfields -g -O2 -ffast-math -funroll-loops -fomit-frame-pointer -module -avoid-version -shared -s -Wl,--enable-auto-import -no-undefined -lpd -shrext .dll -L../../src  -o bob~.la -rpath /usr/local/lib/pd/extra/bob~ bob~.lo  -lpthread
libtool: link: rm -fr  .libs/bob~.dll.a
libtool: link: gcc -shared  .libs/bob~.o   -lpd -L../../src -lpthread  -mms-bitfields -g -O2 -Wl,--enable-auto-import   -o .libs/bob~.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/bob~.dll.a
.libs/bob~.o: In function `bob_new':
C:\Github\pure-data\extra\bob~/bob~.c:191: undefined reference to `s_signal'
C:\Github\pure-data\extra\bob~/bob~.c:191: undefined reference to `s_signal'
C:\Github\pure-data\extra\bob~/bob~.c:192: undefined reference to `s_signal'
C:\Github\pure-data\extra\bob~/bob~.c:192: undefined reference to `s_signal'
collect2.exe: error: ld returned 1 exit status
GNUmakefile:429: die Regel für Ziel „bob~.la“ scheiterte

it worked just yesterday (before I pulled from Git)

**Comment by Spacechild1** [comment]
I tried to install anyway, hoping Pd itself would work. I copied the Tcl files into the bin, but when trying to run Pd I get the error:  "Can't find a sutable init.tcl in the following directories". Again, this worked just yesterday.

**Comment by Spacechild1** [comment]
Also, ASIO compilation doesn't work out of the box (after unzipping the ASIO SDK into /pure-data/asio/ASIOSDK2). I think the portaudio code expects the ASIO sources to be in ./src/hostapi/asio and doesn't try to look in pure-data/asio. For testing purposes I edited the offending includes in the portaudio and ASIO sources to use relative paths:

in asiothiscallresolver.h:
#include "../../../../asio/ASIOSDK2/common/asiodrvr.h"

in pa_asio.cpp:
#include "../../../../asio/ASIOSDK2/common/asiosys.h"
#include "../../../../asio/ASIOSDK2/common/asio.h"
#include "../../../../asio/ASIOSDK2/host/asiodrivers.h"

asiodrivers.h
#include "pc/asiolist.h"

it worked but it's not a good solution at all. I guess this should be rather fixed in the makefile, I just don't know how/where to do it. 
BTW, is there a reason why the ASIO SDK should live in pure-data/asio and not in portaudio/hostapi/asio?

furthermore, asio/readme.txt refers to ASIO SDK 2.2 but I couldn't find that version anymore. I used the recent 2.3 version instead and it seems to work fine.

**Comment by danomatika** [comment]
Thanks for the notes. I've been meaning to look into this but have been busy with a number of things.

**Comment by Spacechild1** [comment]
thanks for your answer! just leave a note in case there's something to test. I totally understand this is not top priority (how many Pd users on Windows actually want to compile Pd themselves with MinGW - except for me :-D ?).  

BTW, what do you think about the folder structure for the installation? usr/local/ obviously is very UNIX like. also, there are two pd.exe (usr/local/bin/pd.exe and usr/local/lib/pd/bin/pd.exe) which is kind of confusing, especially because the first one doesn't launch.

ideally, the structure would follow Millers Windows builds, that is:
./bin - containing pd.exe, wish85.exe and DLLs
./doc
./extra
[./portaudio]
[./portmidi]
./lib - for tcl8.5 and tk8.5 folders
[./src]
./tcl 

Anyway, I want to play around with the build system myself, probably after June... I'll send a pull request when I have some results. 

Christof

**Comment by danomatika** [comment]
The idea of the auto tools updates is that building Pd on *all* platforms should be easy, including on Windows. Your help in looking into this is very useful as most of us do not regularly use Windows.

**Comment by umlaeute** [comment]
i think the target directories (`/usr/local`) should not be meddled with (on the autotools-side)

autotools makes it easy to override these via cmdline arguments (either to `./configure` or `make`), so we could just provide a convenience shell-script that calls the build-process with the proper flags.

trying to come up with non-standard default values is more likely to break things.

**Comment by Spacechild1** [comment]
I wasn't so much about the target directory (/usr/local) but the folder structure underneath. for msys2 or similiar environments which create an emulation of the linux file system, the install process of splitting the app between folders is correct - but still the problem remains that bin/pd.exe doesn't work (btw, the error is "spawnl: no such file or directory") which also means I can't use the 'pd' command in the console and I have to do lib/pd/bin/pd.exe instead (also had to copy wish.exe there). 

however, if you want to install to some other location in the usual Windows way then the given folder structure doesn't make much sense. right now for a Windows user it's not obvious where to put the missing libs (I have to figure out the actual dependencies with a clean machine and add them to INSTALL.txt) and which pd.exe to run (there are 2 executables...). of course, I could provide all these instructions in INSTALL.txt but it wouldn't feel very 'native'. 

I just tried and restructered the installation folder the same way as Miller's Windows builds (see my post above) and now everything works as expected. you just have to copy the tcl libs and wish85.exe to the same places - and there's only one pd.exe to run :-).
so my suggestion is to provide this kind of 'Windows style' installation as an option. I'll try to find the right arguments to `./configure` so it can be a simple shell script, as you suggested.

**Comment by umlaeute** [comment]
with autotools you can also structure the filesystem layout (`/bin`, `/lib`,...) as options to `/.configure` resp. `make`).  so we can *still* just provide a convenience shell-script that calls the build-process with the proper flags.

**Comment by Spacechild1** [comment]
that's what I meant to say with my last sentence :-). anyway, starting from June I can have a look at the DLL issue.

**Comment by Spacechild1** [comment]
I wrote this on the list some time ago but I think it didn't get much attention: I managed to build a complete Pd (with ASIO support + externals) **using only MinGW.** 

I used the git pure-data master branch with a slightly modified makefile.mingw in /src.
The only changes I had to make were: 
pd_src = $(cvs_root_dir)/pure-data
ASIODIR = $(pd_src)/asio/ASIOSDK2.3

here's the makefile: 
https://drive.google.com/open?id=1LRuZMsxFwKavmtuNHAIWuOUgvJ4H2h8H

for compiling I had to put the ASIO SDK (https://www.steinberg.net/en/company/developers.html) in the /asio folder and manually create a /bin folder (where the executables would end up). then I unzipped and manually installed the resources from /msw/pdprototype.tgz (obviously I'm very bad with makefiles) to get a package with the same structure as Miller's Windows builds.

for compiling the extra externals I created my own makefiles with pd-lib-builder.

here's the complete package: 
https://drive.google.com/open?id=1NpYGtoVnnRt7c8cXA7M377cZNeHiEhZF

regarding IOhannes' list, I can tick all the checkboxes except for the last one because I don't have MSVC but I think it should work.

note that there's *no* pd.lib. I have the feeling that there's a misconception about what pd.lib does... pd.lib is a so called import library which is only needed for implicit linking (loading a dll automatically by the runtime).
https://en.wikipedia.org/wiki/Dynamic-link_library#Import_libraries
MSVC needs it to build pd.exe so that it automatically loads pd.dll. MinGW does not need it. 
externals only link against pd.dll with MinGW. the same is also true for MSVC I think (pd-lib-builder doesn't mention pd.lib at all). this kind of makes sense because when externals are loaded, pd.dll has already been loaded by pd.exe - no need for an import library. but maybe I'm wrong. someone (me?) should actually try with MSVC.

Anyway, I think this info could be used to fix the autotools branch. I don't know much about autotools but probably IOhannes can help me.

**Comment by umlaeute** [comment]
could you post a full build log?
something you get when doing:

     make -f makefile.mingw >make.log

(*attach* it to this issue; if necessary zip it beforehand)

**Comment by Spacechild1** [comment]
[log.zip](https://github.com/pure-data/pure-data/files/1500232/log.zip)

seems like this makefile actually builds its an import library called pd.a (see line 106: --out-implib=pd.a)
in line 108 s_entry.o is linked with pd.a so that pd.exe will automatically load pd.dll
usually MinGW can directly link against DLLs but in some cases it needs an import library (don't know if this is the case here?)

MSVC will need pd.lib to link externals against pd.dll - but you can create a pd.lib from a pd.def with the Microsoft lib tool:
http://www.mingw.org/wiki/msvc_and_mingw_dlls

I think we can ignore pd.lib for the MinGW autotools build system. If I want to build Pd with MinGW - why on earth would I want to build externals with MSVC? I guess it's enough to provide a pd.def and refer to MSVC lib tool in the readme.

**Comment by umlaeute** [comment]
usually `pd.a` is a static library, not an import library (in MSVC world, a `.lib` file can be either a static library or an import library; but not in ELF-land or gcc (e.g. mingw))

**Comment by umlaeute** [comment]
and to answer your question about why one would want to build externals with MSVC:

e.g. because you are only building an external (not Pd itself), and your external uses a proprietary C++ library which can only be used with an MSVC-compiler (because the C++-name mangling is different on g++ and MSVC).

or put otherwise: if you can boot your computer into CP/M, why on earth would you want to use DOS?

**Comment by Spacechild1** [comment]
good point regarding MSVC. but isn't this quite an edge case? 
if someone needs to compile externals with MSVC he can create his own pd.lib from pd.def with Visual Studio's LIB tool  (I want to actually try that). 
Miller can of course provide a pd.lib for his distributions, but for the autotools branch I think we can ignore it for now. 
Anyway, the biggest issue with the autotools branch is not pd.lib but the missing pd.dll. everything's linked statically with pd.exe so externals don't have anything they can link back to.
The mingw makefile I used does the right thing, though.

**Comment by Spacechild1** [comment]
Anyway, I think I know what to do. I just have to figure out how to modify the autotools files. Maybe you can give me some hints on Monday :-)

**Comment by danomatika** [comment]
Main places to look for this:

* [configure.ac](https://github.com/pure-data/pure-data/blob/master/configure.ac#L106): used by autoconf to generate configure script, stuff in here helps detect system, libraries, build options, etc
* [src/Makefile.am](https://github.com/pure-data/pure-data/blob/master/src/Makefile.am#L299): used by automake when running the configure script to generate the src/Makefile, stuff in here carries out the actual build details based on configuration info

Note: When making changes to configure.ac, autoconf will need to be rerun to regenerate the configure script. Use ./autogen.sh for this. When making changes to a Makefile.am, usually running make will force it to be rebuilt. Sometimes you can run into stale makefiles or errors (make sure to use TABS in makefile rules!) which will cause makes to fail overtime, it that cause you can manually delete the file and rerun autopen.sh, then configure, etc...

**Comment by umlaeute** [comment]
hmm, actually when making changes to `configure.ac`, this should be picked up automatically by `make` and trigger a re-ru nof the necessary tools (`autoconf`).

`autogen.sh` should only be needed for the initial bootstrap.

**Comment by danomatika** [comment]
>hmm, actually when making changes to configure.ac, this should be picked up automatically by make and trigger a re-ru nof the necessary tools (autoconf).

In theory yes, in practice ... sometimes not. (At least for me, but I have been making more drastic changes...)

**Comment by Spacechild1** [comment]
I just installed Visual Studio. Surprisingly, the import library created by MinGW with --out-implib,pd.lib can also be used by MSVC :-). I successfully compiled the test externals in /doc/6.externs with VC and loaded them in my MinGW Pd (both old and new). All boxes are checked now, I guess?
I'll now fix the install part of the makefile so you get a complete and self-contained Pd package from the GitHub repo.

**Comment by danomatika** [comment]
As far as I can tell from skimming this thread, the main Pd sources should be built into the pd.lib and only s_entry.c is required for pd.exe?

**Comment by Spacechild1** [comment]
not quite. the pd sources should be built into a *pd.dll*. *pd.lib* is just an import library, automatically created with --out-implib,pd.lib.
pd.exe is built by linking s_entry.o with pd.lib (the import library) and some other libraries. 
actually, MinGW could also directly link against pd.dll, pd.lib is only needed by MSVC for linking externals.

**Comment by Spacechild1** [comment]
let's continue here:

I'm willing to dig furhter but I need some hints. In Makefile.am:
309: why is pd.exe a prerequisite for pd.lib and pd.def?
310: why is pd.lib a prerequisite for libpd.a
311: what is LN_S ?
and why are pd.lib and pd.def targets? they should be automatically produced through pd_LDFLAGS when building pd.dll.
but more importantly, where do I see the actual recipes for the targets pd.exe and pd.dll?

**Comment by Spacechild1** [comment]
[log.zip](https://github.com/pure-data/pure-data/files/1522408/log.zip)

here's a build log from the autotools build.
I think the problem really lies in lines 254 and 255.
I'm not really familiar with libtool. why does it build pd.exe twice? the first pd.exe (which ends up in /src) has about the right size (40 KB), but the second one (which goes to /src/.libs) has 5.5 MB. could it be that here everything is statically linked? anyway, no pd.dll is created.

why do we need libtool in the first place? why not `g++ -shared` ?

also, what's the point of copying/renaming pd.lib to libpd.a in 264?

**Comment by danomatika** [comment]
The short answer is that most of the steps that are currently there are indeed wrong. I'm working on an update but a baby got in the way and I'm away from my Windows install at work. I can pus this out in a PR and see what happens to the Appveyer build.

>311: what is LN_S ?

It's an alias for the platform-specific link command which is determined when configuring. On Windows, for instance, I believe it refers to `cp` while on Unixes it creates a soft link using `ln -s`. This is equivalent to using $(CC) in a makefile instead of gcc as it allows overriding the compiler command with something else if you're not using gcc.

>why do we need libtool in the first place? why not g++ -shared ?

Because libtool exists to handle weird platform differences for us. IN fact that is what the auto tools are  for: handling lots of makefile boiler plate.

**Comment by Spacechild1** [comment]
I crudely hacked the Makefile.am and got a pd.dll + pd.exe, but the pd.dll doesn't work yet (turns out it's actually an executable). I think the crucial point is figuring out how to get libtool to make proper DLLs.

**Comment by Spacechild1** [comment]
[Makefile.am.zip](https://github.com/pure-data/pure-data/files/1522812/Makefile.am.zip)

ok, this is really crude and I hardcoded some stuff but it produces working pd.dll, pd.lib + pd.exe. however, it uses g++ instead of libtool (I have to --disable-portaudio and --disable-portmidi because those are built with libtool and can't be used by g++). 

the question is: is it really worth to use libtool for Windows if g++ is so easy? isn't the relevant platform specific stuff handled by configure anyway? this is really just a question... I'm a total autotools noob.

**Comment by danomatika** [comment]
>is it really worth to use libtool for Windows if g++ is so easy? isn't the relevant platform specific stuff handled by configure anyway?

Yes it is. The idea with automake, etc is not to write *any* of the actual build targets directly and only specify the build types, sources, flags, libs, etc. It then does the rest *for you*. You only need to resort to custom targets for things it doesn't do already.

Makefiles are definitely *easier* but the complexity comes with trying to handle so many systems and details reliably... https://stackoverflow.com/questions/719057/why-use-build-tools-like-autotools-when-we-can-just-write-our-own-makefiles

I think the best solution is to rework src/Makefile.am to build the main sources into a convenience library first and then link it into the final pd binary. On Windows, this lib can then be left as the dll while the other platforms statically link it into pd. What do you think @umlaeute? I can probably do this next week on my Windows work machine.

**Comment by Spacechild1** [comment]
thanks for the links, this is very helpful! I will check it out! Sorry for whining around, I'm finally beginning to understand how autotools work.

> I think the best solution is to rework src/Makefile.am to build the main sources into a convenience 
> library first and then link it into the final pd binary. On Windows, this lib can then be left as the dll while > the other platforms statically link it into pd. 

from what I understand this is the key to the solution!

**Comment by Spacechild1** [comment]
[mingw.zip](https://github.com/pure-data/pure-data/files/1524150/mingw.zip)

hey, I managed to get automake/libtool working for MinGW, also with ASIO support. 
pd.exe, pd.dll and pd.lib all end up in /src/.libs
I could load exisisting externals and also build/load new externals against pd.dll/pd.lib with both MinGW and MSVC.
the install is still a big mess (haven't dared to touch it yet), I tested by throwing the three files in an existing Pd package.
some notes:
1) I hardcoded some things which really should be variables. and I'm sure I did some stupid things.
2) I couldn't find a way to strip both pd.exe and pd.dll, they are much larger then they need to be (see STRIP in the mingw makefile). how is this done with autotools?
3) a minor annoyance: when I build with ASIO support (which forces libtool to link with g++), Pd will complain about an entry point not found in libstdc++-6.dll - most likely because of conflicting versions (DLL hell...). this can be ressolved by copying the MinGW version of libstc++-6 into Pd's bin folder.
-static-libstdc++ should actually solve that issue and it works with my MinGW makefiles but not with autotools...

can you take my messy solution and integrate it somehow (maybe in a new branch)? I will then continue working on it. I also want to write a nice install script on top of autotools to get a self contained Windows package (like with my MinGW makefile).

**Comment by danomatika** [comment]
>the install is still a big mess (haven't dared to touch it yet)

Install handling should already be done. What probably needs to be added is to specify the pd dll should be installed on Windows.

>I couldn't find a way to strip both pd.exe and pd.dll, they are much larger then they need to be (see STRIP in the mingw makefile). how is this done with autotools?

It can be added via an [automake local target](rule of thumb: never use it for anything but passing data to perform-routines), maybe to all-local. 

>-static-libstdc++ should actually solve that issue and it works with my MinGW makefiles but not with autotools

Automake basically generates a makefile that is then used to build the program, so there really shouldn't be a difference between a "MinGW makefile" and a generated makefile. It's mainly down to requiring some compiler flag we just need to set in the Makefile.am.

**Comment by danomatika** [comment]
>can you take my messy solution and integrate it somehow (maybe in a new branch)? I will then continue working on it.

Will do! Thanks. It may take a couple days.

>I also want to write a nice install script on top of autotools to get a self contained Windows package (like with my MinGW makefile).

Simplest option is to specify the install prefix when configuring and then ru the install step, which I believe is what you're referring to...

**Comment by Spacechild1** [comment]
sure, but the resulting directory tree is a mess. Pd won't run unless you shift some folders around. We need a script which calls ./configure with the correct paths for all the folders so Pd will run out of the box, as IOhannes suggested:

> with autotools you can also structure the filesystem layout (/bin, /lib,...) as options to /.configure resp. 
> make). so we can still just provide a convenience shell-script that calls the build-process with the proper > flags.

**Comment by danomatika** [comment]
Can you list what the layout needs to be somewhere? ala:

    bin/pd
    lib/tcl...
    ...

**Comment by Spacechild1** [comment]
here's the structure:
`bin` (pd.exe, pd.dll, pd.lib, (pd.com), pdreceive.exe, pdsend.exe, + stuff*)
`doc`
`extra`
`include` (for headers, in case we don't install the sources)
`lib` (tcl8.5* + tk8.5*)
`po`
`tcl`

* these can be found in /msw/pdprototype.tgz in the Github repo.
in my makefile.mingw I unpack it and copy the necessary stuff over.

you can also have look at Miller's distribution: msp.ucsd.edu/Software/pd-0.48-0.msw.zip
Miller also includes the portaudio, portmidi and src folders, but I think this isn't necessary for building from the Github repo because you have the sources anyway.

this is obviously totally different from the Unix like structure which is only supposed to work if you install Pd within Msys2 (which I never do and I've never tried, honestly).

**Comment by danomatika** [comment]
>this is obviously totally different from the Unix like structure which is only supposed to work if you install Pd within Msys2 (which I never do and I've never tried, honestly).

It's not really different, just to a different place ie. not the system. On macOS, Pd is copied into a specific structure to create the .app bundle. Some people like to be able to install it, others don't, so the best option is to support both.

**Comment by Spacechild1** [comment]
the biggest difference between Windows and Linux is that in Windows you have most/all of the ressources in a single folder while on Linux it's spread across bin, lib, share etc.
for MinGW, autotools attempts a Linux style install, which is fine but not what all users always want. an extra install script is the cleanest solution I think.

**Comment by danomatika** [comment]
>for MinGW, autotools attempts a Linux style install, which is fine but not what all users always want. an extra install script is the cleanest solution I think.

I fully understand that. I think what I meant to say (and said it badly), is that the install step simply copies the files from the build folder to some location. We can do that but just do it in a different structure.

**Comment by Spacechild1** [comment]
`We can do that but just do it in a different structure.`

you mean without a script but with a configure option? would be nice if it's not too much of a hassle.

**Comment by danomatika** [comment]
Probably a combination or simply a script. The makefile is simply a set of targets that run scripts anyway, so conceptually it's not all that different. In the case of building the mac app, I found making a separate shell script to be much easier to read and maintain, so I imagine this could be best doe in a similar way.

**Comment by Spacechild1** [comment]
sounds cool!

**Comment by umlaeute** [comment]
@Spacechild1 great. would you mind doing a PR instead of attaching the diffs? (or at least append diff files generated with `git format-patch`) - much easier to review/discuss/apply :-)

**Comment by Spacechild1** [comment]
here you go: https://github.com/pure-data/pure-data/pull/262 :-)

**Comment by umlaeute** [comment]
i think this can be closed (given that #299 was merged).

there's is still one problem, that legacy builds of `Gem` don't seem to work with the so-produced Pd.
this might be an issue with C++ in general (confirm: flext) or some quirks of Gem.

it also seems that a newly build Gem doesn't have this problem.
(Gem builds were traditionally done with MSVC; newer Gem builds might have been done with mingw; so it could be a problem with MSVC++)
