### ISSUE TITLE
MacOS: delayed mouse cursor change on switching edit/play mode

### ISSUE THREAD

**Issue by grrrr** [pure-data/pure-data#267]
Maybe it has become a "feature" over the decades but with newcomers to Pd, this is a constant source of irritation.
The issue is the following:
At least on a Mac, switching play/edit mode (cmd-e on Mac) does not change the mouse cursor appearance immediately, but only on moving the mouse.

**Comment by umlaeute** [comment]
this "feature" is only on macOS

**Comment by danomatika** [comment]
I know I've talked about this on the list, but there is no real way to do this. The cursor is changed but the actual icon doesn't update until the mouse is moved. This is something inside of Tk and we have no way to fix it unless it's fixed in Tk. I usually tell people to move the mouse first before looking at the cursor if they are not sure what made they are in.

**Comment by danomatika** [comment]
I am closing this as *wontfix* for now as, noted above, this is no way to force a cursor update through Tk without moving the mouse, at least that I've seen.

When introducing Pd, I always say to move the mouse first if you are unsure which mode you are in. Also, this less of an issue since newer versions add an `[edit]` to the patch window titlebar.
