### ISSUE TITLE
[Improvements] - package managers - pure-data/puredate - updating debian package manager with the latest stable version of pure-data

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [pure-data/pure-data#279]
#### **[Improvements] - package managers - pure-data/puredate - updating debian package manager with the latest stable version of pure-data**

**Greetings**

The current version of **pd** featured in _debian package manager_ is **0.47**. **IMHO**, we should feature the last stable version of _puredata_, _puredata vanilla,_ and _pd-2lork_ in **most of linux package managers**.

**looking forward, kind regards**

**Comment by umlaeute** [comment]
Debian currently ships Pd-0.48-0, which is the latest stable Pd.

You can get an up-to-date list of which packages Debian ships at https://packages.debian.org/search?keywords=puredata

(any given Debian release will not update any package after Debian was released; e.g. *Debian/3.0 (codename woody)* which was released in 2002 comes with `Pd-0.32.1` and if you want to stay with *woody*, you will never get a newer package of Pd.
otoh, since *Debian 9 ("stretch")* (as of today the current release - released 2017) you can enable the [backports archive](https://backports.debian.org) to get a current Pd package on your *stable* Debian)
