### ISSUE TITLE
Abstractions named "anything"

### ISSUE THREAD

**Issue by HenriAugusto** [pure-data/pure-data#372]
If you try creating an abstraction named "anything" it will not be instantiated. Also after trying to create an [anything] PD won't instantiate other valid abstractions!

It seems that after the failed [anything] PD **will** instantiate previously used abstractions but **will not** instantiate others.

**edit:** I could not find the reason in the source code so i don't know if this happens by design. If its not by design then it's a bug. If it is by design there should be some kind of file documenting that reserved name.

**Comment by porres** [comment]
seems you cannot have a compiled object called anything as well...


<img width="805" alt="screen shot 2018-05-31 at 13 00 37" src="https://user-images.githubusercontent.com/5360142/40793434-bf11c872-64d2-11e8-938b-8efe94db54fd.png">

**Comment by Spacechild1** [comment]
that is actually a pretty funny bug! here's what's going on:

when you type something in an object box you're actually sending a message to pd_objectmaker with the selector being bound to a "new method" (for externals) or "do_create_abstraction" (for abstractions). 
generally, if a message can't be found in a class (for pd_objectmaker this means object/abstraction hasn't been loaded yet), pd_typedmess falls back to the anything method - in the case of pd_objectmaker that's "new_anything" (see m_class.pd), which is responsible for loading unknown objects.
now when you do [anything ...], you basically override pd_objectmaker's anything method, preventing it from loading any new abstractions/externals.

for why the [anything] abstraction itself doesn't load, I'm not quite sure yet...

anyway, the fix is easy: add a check in "new_anything" that `s != &s_anything`. 
I'll put it my list and make a PR.

**Comment by porres** [comment]
awesome, cause now I wanna make an object called [anything] :)

**Comment by Spacechild1** [comment]
can be closed

**Comment by HenriAugusto** [comment]
okay

**Comment by porres** [comment]
have you tested this? cause I still can't create an abstraction called anything, or is this not in 0.48-2? just in the next release?

**Comment by Spacechild1** [comment]
> cause I still can't create an abstraction called anything

yes, but don't you get a warning: "object name anything not allowed"? creating such an object breaks Pd by design, so we explicitly disallow it.

**Comment by porres** [comment]
oh... i didn't realize the idea was that you now can;t do it, haha
