### ISSUE TITLE
 -maxsize no bigger than 2.14748e+09 in [soundfiler] on windows

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#380]
In windows, `[soundfiler]` won't accept a `-maxsize` flag bigger than *2.14748e+09* or something (I got that with trial and error) for some reason.

the console shows a typical syntax error for `[soundfiler]`:

```
usage: read [flags] filename tablename...
flags: -skip <n> -resize -maxsize <n> ...
-raw <headerbytes> <channels> <bytespersamp> <endian (b, l, or n)>.
```

**Comment by porres** [comment]
I see this is related, huh? https://github.com/pure-data/pure-data/pull/366

**Comment by Spacechild1** [comment]
it's related in the sense that users usually do "-maxsize HUGENUMBER" to circumvent the small default maxsize. Miller already said he is willing to remove the default value which is a relict from the old times. nevertheless, there should be a check in soundfiler_read to prevent integer overflow.

**Comment by porres** [comment]
hi, what changed?

**Comment by porres** [comment]
I mean, I see it has a new maximum of 0x7fffffff - but can you really resize it with the -maxsize flag  to something bigger than 2.14748e+09? 

just wanna be sure

**Comment by Spacechild1** [comment]
> but can you really resize it with the -maxsize flag to something bigger than 2.14748e+09?

no, because the point is to *limit* maxsize to LONG_MAX to avoid overflow (where the number wraps around). Miller has already merged my fix.

**Comment by porres** [comment]
yeah, I meant if it's safe to set "-maxsize" to some very large number bigger than 2.14748e+09 (say 4e+09).

if I get this correctly, now it's not, because it's clipped to 2.14748e+09? sorry, I don't get it... and no details have been documented about this

**Comment by Spacechild1** [comment]
what do you mean? you can't really resize to sizes larger than LONG_MAX because Pd's internal resize function takes a long... the problem is rather that in Windows, `long` is 32bit, so even if you're on a 64bit Pd and you would have enough memory, you can't resize arrays larger than N > 2^31.

the problem is, `garray_resize_long` is a public function, and if I'm correct, changing `long `to `long long` in the signature would break ABI compatibility. one solution could be to internally have a new version which takes a `long long` - which gets called by both `garray_resize` and `garray_resize_long`. since the [resize( method calls the float version, we could at least make huge arrays on the patch level.

**Comment by Spacechild1** [comment]
so again, "-maxsize HUGENUMBER" is perfectly safe now, it will simply set maxsize to the actual limit Pd can handle.

**Comment by porres** [comment]
ok, thanks for the details, and I assume it does initialize with such actual limit it can handle, right?
