### ISSUE TITLE
[savepanel] interrupts normal order of operations behaviour

### ISSUE THREAD

**Issue by LGoodacre** [pure-data/pure-data#405]
![savepanel](https://user-images.githubusercontent.com/22167643/43568769-1fe1e2ca-9653-11e8-9b42-31d507cbd91f.png)
If you send a bang to [savepanel], any further events stemming from that bang are suspended until [savepanel] has finished selecting a file.
Is this intentional? I can't think of any other situation where a downstream object affects operations upstream.

**Comment by umlaeute** [comment]
afaict, it's intentional:
the `[savepanel]` doesn't interact at all with the upstream `[bang(`.
however, it is a modal dialog that blocks interaction with the entire GUI (including clicking on the canvas, which in turn would activate the `[bang(`)

**Comment by LGoodacre** [comment]
Blocking interaction with the canvas is one thing, but this is blocking the normal operation of the patch. I can't think of any other instance where a message is suspended like this in the data flow, and I can't think why it would be desirable. If you want to bang something once the file has been selected, you can put a trigger on the outlet.

**Comment by umlaeute** [comment]
it really is not.

if you run Pd with `-stderr`, you will see that the print is triggered immediately after raising the `[savepanel]` (and that it is not delayed until you close dialog).
alternatively, you could trigger some sound:
![savepanel + sound](https://user-images.githubusercontent.com/214034/44006117-e09bb5d0-9e7e-11e8-98f7-08a0f9b98fb7.png)

so what you experience is that the GUI blocks all GUI-events until the modal dialog is handled.
afaict, this is the behaviour of tcl/tk's modal dialogs. i'm not sure it can be changed (and I don't think much harm is being done)

**Comment by danomatika** [comment]
As IOhannes says, it's a modal dialog. It takes over all focus of the GUI but the pd core running the patch is not blocked.

I tested the patch shown above and, for me, the svaepanel appears *after* the osc~ peep. Does this mean savepanel is breaking the order of operations? No, it's just a perception of timing between the slow GUI and the fast DSP. Also, macOS loves it's animations, so the savepanel takes longer for me since it has to zoom up form the center of the screen.
