### ISSUE TITLE
Redo/Undo doesn't work for changing gui objects's properties

### ISSUE THREAD

**Issue by HenriAugusto** [pure-data/pure-data#471]
Redo/Undo doesn't work for changing gui objects's properties

For example: changing the size of sliders, canvases colors, etc. Not a big problem but somewhat unexpected behavior.

**Comment by umlaeute** [comment]
yes. this is known and unlikely to change.

`undo/redo` works on everything the *canvas* (aks "window") knows about (aka "is actively involved").
the properties of GUI objects are at the sole discretion of the GUI-properties themselves.
since `undo/redo` doesn't work on the internal state of objects, the properties of GUI-objects are not part of the game.

(afaict, adding undo/redo to GUI object properties would require a major redesign of all GUI objects - which miht warrant a separate feature-request)
