### ISSUE TITLE
$@ syntax addition

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#503]
according to https://github.com/pure-data/pure-data/issues/273#issuecomment-415195064 the $@ syntax from Purr Data originated in the development of Vanilla, but never got into Extended and was never included in Vanilla. I wonder why it didn't make it, and if it has been already decided not be a good idea and rejected before, we can just close this issue. 

cheers

**Comment by porres** [comment]
seems the relevant code in extended is in m_atom and m_binbuf only...

**Comment by porres** [comment]
my main motivation for this was getting the arguments of an abstraction, which now can be done with [pdcontrol].

so only motivation now would be to be the same as pd extended 0.43, which purra data inherited, and that doesn't seem to be much of a cause to me, personally

**Comment by HenriAugusto** [comment]
I still think it's a neat syntax.

Imagine you have an abstraction [listFoo] that deals with lists. You want the user to be able to initialize the internal list using arguments [listFoo a b c d].

Inside of [listFoo] you could just write 

`[listFoo $@]`

instead of

```
     [loadbang]
     |
     |args 0(
     |
     [pdcontrol]
     |
[list]
```

Also you can use it to "pass objects" to abstractions.

Example: i have a [elem-op] object that performs element-wise operations on lists.

Insite [elem-op] i have have a [$1] object in order to be able to pass the operator i want to use as an argument: [elem-op +], [elem-op -], [elem-op *], [elem-op &&], etc

But let's say i also have an unrelated object [doSomething] that takes two elements and process them in some specific way i want to use. [doSomething] takes up to 3 argument flags (-x -f -c) to control it's behaviour plus a number.

We want to be able to write [elem-op doSomething -x -f 32] so our [elem-op] will be able to process two lits element-wise using the [doSomething -x -f 32] abstraction. 

But we can't use [$1] for that because it would expand only to [doSomething]. 

We can't also use [$1 $2 $3 $4 $5] because we would be passing zeroes as arguments to [doSomething] in case the user don't supply all three flags and a number. 

But we would be able to do it if we had [$@].

**Comment by porres** [comment]
it might feel nicer to do it that way instead with [pdcontrol], but once we have this new object, there's a way to do it and no need for another.

**Comment by porres** [comment]
the other case feels like an edge case that I don't know exactly if I get it, but feels like there's an alternative as well...

anyway, I just don't care about this anymore, but I won't close the request. Maybe I would try to propose a PR for it one day, but I'm not doing this anymore. Nothing stops you from working on a PR and propose it yourself? :)

**Comment by porres** [comment]
quoting miller here: "Adding features is how software inflates and eventually dies of bloat. One wants a valid use case before just adding stuff. And even then, if there's already a way to do the same thing, one should think twice."

So @HenriAugusto about this:

> the other case feels like an edge case that I don't know exactly if I get it, but feels like there's an alternative as well...

I'm still not sure of what you need, can you try to be more specific with a very simple patch, and then I'll see if I could see a way of actually doing this?

**Comment by porres** [comment]
I don't really care for this anymore, so I'm closing it, now that we have [pdcontrol], I don't think this is needed. If @HenriAugusto or somebody else still thinks this is important, it can be brought back....
