### ISSUE TITLE
cords not aligned with box outline on 0.49-1

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#515]
On OSX 10.11.6 El Capitan, using Pd-0.49-1 from msp.ucsd.edu, cords are not exactly aligned with box outlines. It is not a huge deal but it may not be the wanted behavior, and I think it looks a bit messy.

Here's a screenshot:

![screen shot 2018-10-19 at 1 45 18 pm](https://user-images.githubusercontent.com/13335792/47239240-0898c000-d3e5-11e8-883c-d3f39e362a9a.png)

And another screenshot with signal cords:

![screen shot 2018-10-19 at 1 48 05 pm](https://user-images.githubusercontent.com/13335792/47239249-0df60a80-d3e5-11e8-851f-62c56a0e79d8.png)

I believe this issue relates to https://github.com/pure-data/pure-data/pull/420

**Comment by umlaeute** [comment]
thanks for reporting this.

i noticed it too (on Debian) and find it slightly irritating (much more than the ugly look of protruding end-of-lines which #420 attempted to fix; but this probably is just a matter of patching habits).

i'm pretty sure that #420 is the culprit here, @danomatika

**Comment by danomatika** [comment]
I updated the coord y position to be in the middle of the inlet to outlet box to facilitate better alignment in zoom mode. I suppose the fix is not to shift the y pos down when drawing at zoom level 1.

**Comment by danomatika** [comment]
> It is not a huge deal but it may not be the wanted behavior, and I think it looks a bit messy.

The problem with how the canvas looks seems to be this on a continual basis: I/we change something that annoys 1 person and another person finds the change annoying.

In any case, this is something I can fix as it was an unintended side-effect for the original problem.

**Comment by danomatika** [comment]
Using `-capstyle projecting` without a y offset helps but exacerbates the problem #420 was trying to fix for signal cords at large angles:

<img width="562" alt="no-offset-projecting-caps" src="https://user-images.githubusercontent.com/480637/55759735-7780d880-5a5a-11e9-87ad-b4f9ad9ffe7d.png">

And the current default butted cap style with the y offset looks good for signal cords but not for message cords, as noted:

<img width="562" alt="offset-butted-caps" src="https://user-images.githubusercontent.com/480637/55759850-c29aeb80-5a5a-11e9-9419-6b144afe02b6.png">

A possible solution is then to apply the offset for signal coords only:

<img width="562" alt="signal-offset-only-utted-caps" src="https://user-images.githubusercontent.com/480637/55760428-5c16cd00-5a5c-11e9-82e1-8f97b0cc3660.png">

but this means those who relied on aligning the signal cords as horse lines with not see horse lines. However, since the signal cords are thicker already, that might need be as big of a deal.

Two other options:
- Only apply the offset to signal coords when the zoom level > 1 and the line ends are most pronounced, however this could lead to slight line drawing dissimilarities between zoom levels. I did *alot* of work to make zoomed drawing work well and I would not like to see this.
- Revert #420 and hold my nose at bad signal line ends.

**Comment by danomatika** [comment]
For completeness, no offset with `-capstyle round` is not much different than `-capstyle projecting`:

<img width="562" alt="no-offset-round-caps" src="https://user-images.githubusercontent.com/480637/55760861-b3696d00-5a5d-11e9-8e05-a891c629d4f3.png">

**Comment by danomatika** [comment]
...and here's the original behavior with no offset and default butted caps:

<img width="562" alt="no-offset-butted-caps" src="https://user-images.githubusercontent.com/480637/55761356-4ce54e80-5a5f-11e9-9641-0fd2b35b3fb0.png">

**Comment by danomatika** [comment]
Anyone have any opinion on this? @porres @mxa @Spacechild1 @katjav :)

**Comment by porres** [comment]
Hi, not sure what kind of opinion you're expecting. I don't notice anything weird in my patches, but I usually suffer from OCD and always have pretty neat and nice patches that are aligned and connections are from top to bottom.

What really irritates me is patches that are designed in a way where a horizontal line connects objects and you just can't know which outlet connects to which inlet. I have a strong opinion that is a bad habit that should be avoided. But it's cool, cause I don't have to deal much with patches from others :)

**Comment by danomatika** [comment]
I'm just looking for some opinions on what to do next. At this point, I'm leaving towards reverting the offset to the pre-0.49 behavior.

**Comment by Spacechild1** [comment]
on Windows, the pre-0.49 is quite fine, only horizontal signal connections sit a bit too low. to be honest, I've never noticed any issues with the patch cord drawing before reading this thread :-) I guess because I very rarely use horizontal connections. I 've now noticed one issue in the current behavior, though:
1) move the objects so that the connection is horizontal
2) disconnect and connect again -> the connection is slightly skewed
3) move one object 1 pixel up and down -> the connection is horizontal again

**Comment by danomatika** [comment]
I went ahead and reverted it for now with 1c65e99c4132138d9a33ae97fbe9d40af3c0c3ff. I'd rather not try and come up with more and more tricks for edge cases like this.

**Comment by katjav** [comment]
With Pd 0.49.0 I had already noticed 'broken horizontalness'. Lines patched horizontally in 0.48.0 are now two pixels diagonal. On Linux this is especially noticeable because patch cords and object outlines are not anti-aliased here, they go clumsily stepwise. Maybe related: object / message box height is 17 pixels in Pd 0.49.0 and 18 in Pd 0.48.0.

I'd be happy with the earlier behavior, 'protruding patch cords'. Annoyances like these always remind me that dsp programming is about frequencies, not pixels. As Miller stated in a lecture in Nantes, 'Pd est moche; c'est pour vous liberer.' An unforgettable lesson.

**Comment by danomatika** [comment]
This has been fixed by reverting to previous behavior in 0.50.
