### ISSUE TITLE
PD import not working

### ISSUE THREAD

**Issue by quintendewilde** [pure-data/pure-data#532]
I get following errors with pd-0.49 on osx mojave
when importing al things. I already rebooted, reinstalled etc..
```
 tcpreceive
... couldn't create
 tcpsend
... couldn't create
 tcpserver
... couldn't create
 tcpclient
... couldn't create
 mrpeach/slipdec 65536
... couldn't create
 tcpreceive 9995
... couldn't create
 mrpeach/slipenc 65536
... couldn't create
 import mrpeach
... couldn't create
```

**Comment by porres** [comment]
import is not part of Pure Data Vanilla. Use [declare] instead to load libraries

**Comment by umlaeute** [comment]
also: all the externals you want to load used to be part of Pd-extended. but Pd-extended has been dead for the last 6 years.
Pd (aka Pd-vanilla) - while still live and kicking -  comes with (almost) no externals.

in order to use the libraries you try to with Pd-vanilla, you have to *install* them first (e.g. go to <kbd>Help</kbd>-><kbd>Find externals</kbd, search for the externals you want and install them).
