### ISSUE TITLE
is biquad~ correct?

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#541]
[biquad-test.pd.zip](https://github.com/pure-data/pure-data/files/2775574/biquad-test.pd.zip)

I'm assuming both outputs in this example should be the same. Am I wrong or is it [biquad~]? 

<img width="1066" alt="screen shot 2019-01-19 at 02 18 12" src="https://user-images.githubusercontent.com/5360142/51422137-a93b7f00-1b90-11e9-9751-3f2b184fdd9d.png">

**Comment by umlaeute** [comment]
please post the patch so people don't have to re-type it,

**Comment by porres** [comment]
edited the original post and posted it

**Comment by umlaeute** [comment]
[biquad~] does some checking whether the filter is stable.
if it is not stable, the coefficients are set to zero (that's why you get all 0 as output).

https://github.com/pure-data/pure-data/blob/master/src/d_filter.c#L458

this should probably be mentioned in the help-file (and there might be a special message that allows overriding the check)
