### ISSUE TITLE
[array define -k foo] does not keep 'size' when size is not an argument

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#567]
Say you create an array with `[array define -k array2]`.

Then pass, for example, a `sinesum 64 1` message, and everything is working fine: array is resized to 64+3, as expected. Saving the patch does write 64+3 values (`#A 0 -0.0980171 0 0.0980171 ...`).

But, if you close and re open the patch, then the array is resized back to default, ignoring the new size, which looks like this:

![array_size_not_kept](https://user-images.githubusercontent.com/13335792/53813679-77268680-3f5e-11e9-92ee-f788ce4a7e1f.jpg)

This would be a problem when doing things dynamically, or when the new array size is greater than 100..., otherwise if you have your tabreads fit for the first 64 values, you won't notice it I guess....

**Comment by fdch** [comment]
Can this be closed as completed?

**Comment by porres** [comment]
I dunno, has it been completed? :)

**Comment by fdch** [comment]
See the [draft PR](https://github.com/pure-data/pure-data/pull/655) and a comment by [Miller](https://github.com/pure-data/pure-data/pull/621#issuecomment-881788405) so I think it has a fix, but I'm not sure. That's why I asked :)

**Comment by umlaeute** [comment]
i haven't looked at the draft PR nor at miller's comments, but in general we close issues once they are fixed in `master`.
This means that the mere existence of a PR is not enough to close the issue (esp. if it is a "draft PR"), but once it's merged into `master`, it can be closed. usually PRs should have a `Closes: https://github.com/pure-data/pure-data/issues/567` line (either in the top-level posting of the PR, or somewhere in the commit message of the relevant commit), to automatically close the issues once merged...

**Comment by umlaeute** [comment]
apart from that: the issue appears to be fixed for good in current Pd(and documented in the array help-patch).

closing for good :-)
