### ISSUE TITLE
Pasting and abstractions weirdness

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#643]
To reproduce, follow these steps:

1. make a patch main.pd and an abstraction abst.pd have some other objects in each
2. put [abst] in main.pd 2 times
3. copy something in main.pd
4. open first instance of [abst], manipulate it save it, close window.
5. open second instance of [abst], paste.
6. it will paste [abst] itself, not what you thought was in the clipboard.

**Comment by Spacechild1** [comment]
this is an implementation detail of Pd. if you save an abstraction, all other abstractions are updated. internally, this is done by simply cutting them and then undo. by cutting an abstraction you implicitly copy it and there you go.

`canvas_cut` could have an additional argument to tell whether we want to copy (e.g. Ctrl+X) or not (e.g. canvas remaking). 

actually, we only need this hack for the case when the number of inlets/outlets change, otherwise we could just swap the old object with the new one...

**Comment by mxa** [comment]
Thanks for the explanation. I think this should be fixed. It's confusing, (feels) buggy and in the above case creates infinitively recusive patch structures.

**Comment by umlaeute** [comment]
this is strongly related to #644
