### ISSUE TITLE
convert bang to symbol with [trigger]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#684]
a bang input into `[trigger symbol]` outputs `[symbol symbol(`, but I think it makes sense to output "`[symbol bang(`" (by the way, purr data does that).

**Comment by Spacechild1** [comment]
I think we all agree that the current behavior is bogus. But I think it should rather print an *error*. Sending a bang to `[t s]` is an error and the very fact that the user wrote `[t s]` and not `[t a]` tells that they want the input to be really a symbol. I am very much against more implicit conversions because it defeats type safety. See also the discussion in https://github.com/pure-data/pure-data/issues/1478

**Comment by porres** [comment]
yeah, I agree this idea doesn't make sense anymore and I thought I had closed this issue, and I am  in favour of https://github.com/pure-data/pure-data/issues/1480
