### ISSUE TITLE
different blocks delay (documentation and error)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#697]
Delays with different block sizes (or also different overlaps/oversampling). More specifically, they should be under the same block tree to avoid any issue. 

We should document this in the help file and maybe give an error in the code, like in https://github.com/pure-data/pure-data/blob/master/src/d_delay.c#L230

Now, I see there's a suppressed error when checking for different block sizes, maybe we could do something like that it https://github.com/pure-data/pure-data/blob/master/src/d_delay.c#L74

**Comment by Spacechild1** [comment]
> More specifically, they should be under the same block tree

what do you mean by that?

> maybe give an error in the code

certainly not! delread~ and delwrite~ *do* work with different block sizes, overlap and upsampling. the result is well-defined, although it's not always immediately obvious. some algorithms require this behavior. making it an error is not necessary and will break existing patches. I would say it's a feature for expert users :-)

> We should document this in the help file

I agree this should be documented, maybe something in the line of: "usually, delread~ should have the same block size, overlap and upsampling factors as the corresponding delwrite~. otherwise you might get unexpected results."

**Comment by porres** [comment]
>  "usually, delread~ should have the same block size, overlap and upsampling factors as the corresponding delwrite~. otherwise you might get unexpected results."

sounds good.

> some algorithms require this behavior. making it an error is not necessary and will break existing patches. I would say it's a feature for expert users :-)

hey, I like to think I'm an expert, but I don't understand how this works :( 

how about an advanced tutorial for experts to understand and make sense of this? :)

**Comment by Spacechild1** [comment]
> hey, I like to think I'm an expert, but I don't understand how this works :(

as a consolation, I keep forgetting the details myself all the time... 

overlap itself doesn't do anything special, but it goes hand in hand with reblocking. reblocking only leads to troubles if the [delwrite~] has a larger blocksize than the [delread~], e.g.:

[delwrite~] with blocksize 256
[delread~] with blocksize 64

[delwrite~] will update the phase of the ringbuffer every 256 samples, but [delread~] reads from the buffer every 64 samples, so it will always read the same 64 samples 4 times in a row (assuming that the delay time doesn't change).

On the other hand, a [vd~]/[delread~] with a *larger* blocksize than [delwrite~] is needed for certain FFT patches, e.g. live pitch shifting. If [vd~] is in a FFT subpatch with [block~ 1024 4], the [delread~] must *not* operate at 1024 samples. To be exact: it must not operate at more than 256 samples (= hopsize), otherwise the ring buffer is not advanced between every FFT window.

> how about an advanced tutorial for experts to understand and make sense of this? :)

we might add some examples in the help patch to show what happens for differing blocksizes.

**Comment by porres** [comment]
> On the other hand, a [vd~]/[delread~] with a larger blocksize than [delwrite~] is needed for certain FFT patches, e.g. live pitch shifting. If [vd~] is in a FFT subpatch with [block~ 1024 4], the [delwrite~] must not operate at 1024 samples. To be exact: it must not operate at more than 256 samples (= hopsize), otherwise the ring buffer is not advanced between every FFT window.

This is why I'm not being able to design a spectral processor that relies on [delread4~] if I have both [delwrite~]/[delread4~] in the same subpatch where the FFT action goes.

Now, my problem with the delay size limit is also in respect to this very same patch. The problem is that it would cut a considerable chunk of the delay line when you have a window size of 2048/4096, for instance.

The problem is that I still can see the same issues with the update in the code, now that it uses a proper delay line size. Maybe it is because they both have a different block size?

So, my question is, how do make sure that a [delwrite~ $0-x 1000] will have a length of 1 second when reading it with a [delread4~] with, say, [block~ 2048 4]?

**Comment by Spacechild1** [comment]
> This is why I'm not being able to design a spectral processor that relies on [delread4~] if I have both [delwrite~]/[delread4~] in the same subpatch where the FFT action goes.

if both objects are in the same subpatch, there shouldn't be any problem...

> So, my question is, how do make sure that a [delwrite~ $0-x 1000] will have a length of 1 second when reading it with a [delread4~] with, say, [block~ 2048 4]?

personally, I simply allocate some extra space in the delay line (depending on the max. blocksize). but your PR would make this obsolete.

**Comment by porres** [comment]
> if both objects are in the same subpatch, there shouldn't be any problem...

well, I agree, but I'm getting it...

and I guess you missed this email to the Pd list :) https://lists.puredata.info/pipermail/pd-list/2019-08/125699.html

here's the attached patch

[del-fft.pd.zip](https://github.com/pure-data/pure-data/files/3464333/del-fft.pd.zip)

**Comment by Spacechild1** [comment]
ah yes, this has to do with the way [delwrite~] behaves in overlapped subpatches. I've answered to the list!

**Comment by porres** [comment]
thanks, ok, then, the issue is that I need them to be in separate block sizes, but the problem is that I still can see the same issues with the update in the code, where it seems it fails to read the full length of the delay line.

I'd have to perform further tests though to make things sure.

**Comment by Spacechild1** [comment]
> thanks, ok, then, the issue is that I need them to be in separate block sizes

why? what do you want to achieve?

> where it seems it fails to read the full length of the delay line.

for now, just increase the size of the delay line. I only removed the glitches.

**Comment by Spacechild1** [comment]
you can send me the patch you're working on with a description of what you're trying to do.

**Comment by porres** [comment]
Here it is, it's a live input phase vocoder that misbehaves in the same way as before, even by using this PR. If I increase the delwrite~ line length, it works. So it's as if it didn't really fix the issue for this one yet.

I have other tests though that shows how this PR actually handles well the delay length issue...

[live-pvoc-test.zip](https://github.com/pure-data/pure-data/files/3464419/live-pvoc-test.zip)

**Comment by porres** [comment]
Oh, the above test patch needs the else library :)

**Comment by Spacechild1** [comment]
> even by using this PR.

can you try to incorporate my suggestions? especially this one: https://github.com/pure-data/pure-data/pull/698/commits/3b6a44ab940ed46dd7b010745d9c0b593b6db937#r310365921

in your commit, you always take the blocksize from the [delwrite~] object, but in your patch you actually want the blocksize from [vd~]. My solution is to always take the *largest* blocksize of all objects involved.

**Comment by porres** [comment]
> can you try to incorporate my suggestions? especially this one: #698 (comment)

seems it didn't make it :/
