### ISSUE TITLE
compiling error on macos Mojave: unknown type name 't_classfreefn'

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#712]
I keep getting this error trying to compile the latest master (my [fork](https://github.com/fdch/pure-data), which seems to be even with master as of [this commit](https://github.com/pure-data/pure-data/commit/b396788007bce87336106ba995011684509f00ad)) on macOS Mojave 10.14.5

```
./autogen.sh
./configure
make
...
In file included from pdsched.c:15:
../../src/m_imp.h:60:5: error: unknown type name 't_classfreefn'
    t_classfreefn c_classfreefn;    /* function to call before freeing class */
    ^
1 error generated.
make[3]: *** [pdsched.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by porres** [comment]
I compiled it just fine on 10.14.5 here on master with the latest commit!

**Comment by fdch** [comment]
So I guess there's something wrong with my fork. I will look into it. 

Just to be sure, did you configure/make in any other way than what I show above?

Also, any hints as to why `t_classfreefn` would not be defined will be appreciated :))

**Comment by porres** [comment]
./autogen.sh
./configure
make
make app

**Comment by umlaeute** [comment]
in the commit you referenced, `t_classfreefn` is declared in https://github.com/pure-data/pure-data/blob/b396788007bce87336106ba995011684509f00ad/src/m_pd.h#L514

and `m_pd.h` is included before `m_imp.h` by *pdsched.c* in https://github.com/pure-data/pure-data/blob/b396788007bce87336106ba995011684509f00ad/extra/pd%7E/pdsched.c#L13-L15

which should prevent the error you are seeing.

i'm therefore closing this issue, as it seems that the problem was triggered by some modifications of the sources on your side.

**Comment by fdch** [comment]
Thanks for looking into this. I am not sure that I have changed the source code.I honestly have never even opened  `pdsched.c` ... Anyway, thanks again.  I managed to compile successfully. Just for the record, here is what I had to do:

- I synced my fork with upstream/master as explained [here](https://help.github.com/en/articles/syncing-a-fork)
- Upgraded Homebrew with `brew upgrade`
- I always have an issue with `m4` which prevents me to run `autogen.sh`, but I work around it as explained [here](https://lists.puredata.info/pipermail/pd-dev/2019-01/021821.html)
