### ISSUE TITLE
[pd control]'s 'browse' command is misbehaving when the directory has a space

### ISSUE THREAD

**Issue by tremblap** [pure-data/pure-data#734]
As discussed on the list, the (very convenient and amazing) call to [dir] yields the right path, but when this is passed to [pdcontrol] via a [browse] message there are strange errors reported.

```
(Tcl) UNHANDLED ERROR: wrong # args: should be "::pd_menucommands::menu_openfile filename"
   while executing
"::pd_menucommands::menu_openfile /ze_path..."
   ("uplevel" body line 7)
   invoked from within
"uplevel #0 $docmds???
```

According to @millerpuckette and confirmed with the attached patch, this "looks to me as if I neglected to escape spaces in the file path or something like that."

To reproduce, save the file in a folder, and try to load a file (here named 'file.jpg) in a parallel folder (same depth) called website. The patch should be cristal clear and is provided just as a convenience.

[ze_browser.pd.txt](https://github.com/pure-data/pure-data/files/3533490/ze_browser.pd.txt)

**Comment by umlaeute** [comment]
fixed in b4a9cc631a71fa9ca68276ab8953ed3b8fb225e7

### for the record
your test-patch doesn't trigger the problem (or rather: only in very specific circumstances).
if you want to demonstrate problems with files in directories with spaces, you better provide a zip-file that contains a directory with such a name..., e.g.:

    foo bar/
    foo bar/ze_path/ze_browser.pd
    foo bar/website/file.jpg
