### ISSUE TITLE
Windows: calling installer multiple times changes target path

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#763]
When calling the [0.50-1 installer for Win64](http://msp.ucsd.edu/Software/pd-0.50-1.windows-installer.exe) the first time, it suggests to install Pd into `%ProgramFiles%\Pd` (e.g. "C:\Program Files\Pd"). Accepting this suggestion, we end up with `%ProgramFiles%\Pd\bin\pd.exe` (which is the proper location).

Now, when calling the installer a second time (without having uninstalled Pd), it will now suggest to install Pd into `%ProgramFiles%\Pd\bin`. Accepting this suggestion, we end up with `%ProgramFiles%\Pd\bin\bin\pd.exe`.

Calling the installer a third time (without having uninstalled Pd), it will now suggest to install Pd into `%ProgramFiles%\Pd\bin\bin`. Accepting this suggestion, we end up with `%ProgramFiles%\Pd\bin\bin\bin\pd.exe`.

Running the uninstaller (and thus wiping the registry), will reset the installation path, and the next time I run the installer I'm back to the good `%ProgramFiles%\Pd` suggestion.

The path seems to be taken from the `${ARCHI}` field of the `Software\Microsoft\Windows\CurrentVersion\App Paths\pd.exe` key (the installer just [strips the filename](https://nsis.sourceforge.io/Reference/InstallDirRegKey) away).

Shouldn't https://github.com/pure-data/pure-data/blob/7c71e91d3734d1907d6060deaf996849b62c429c/msw/pd.nsi#L134 just read:

~~~nsis
WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "${ARCHI}" "$INSTDIR"
~~~

i guess @Lucarda is the one to answer this

**Comment by Lucarda** [comment]
@umlaeute, right.
Here's an [installer](http://lucarda.com.ar/x/pd-0.50-0.windows-installer-issues-763and759.exe) with the above changes ( it also includes the fix for #759 and other goods as **pdfontloader for wish86 64bit** and  **DejaVuSansMono-Bold.ttf** both missing in the current installer)

I was expecting this installer to prompt to overwrite files if run without uninstalling but it didn't. Also with this changes I couldn't find anything broken (shortcuts, file association, etc)

I'll add this changes to PR #761.
