### ISSUE TITLE
add possiblity to read binary files in Vanilla

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#792]
Hi,

At the moment it's not possible to read binary files using [text]. It would be great to have this in place to for example deal with sysex files.

Interesting thread here: https://lists.puredata.info/pipermail/pd-list/2019-01/124364.html
where workarounds are discussed as well.

Cheers,
Mario

**Comment by Spacechild1** [comment]
Hey, I think Miller has expressed interest in adding support for reading/writing binary files to/from [array]. I think this would make more sense since a binary file is just a list of numbers (bytes).

**Comment by umlaeute** [comment]
in the meantime, why can't you use `[soundfiler]`?

i guess the reason is, because `[soundfiler]` doesn't accept 1-byte data.
until it does, it shouldn't be too hard to use `[soundfiler]` to read raw data in 2-byte chunks and then manually convert it to 1-byte data.

the only issue i can think of is that if your file as an odd number of bytes, you will lose the last one... (and you won't even get notified)

**Comment by Spacechild1** [comment]
> i guess the reason is, because [soundfiler] doesn't accept 1-byte data.

The default mode of [soundfiler] converts all data to the range [-1, -1], which is not what we want when we talk about reading binary files. Since Miller added the `-ascii` option to read ASCII text files, I'll just go ahead and propose a `-binary` option to read binary files.

**Comment by umlaeute** [comment]
sure.
although it's not so hard to multiply values by 127 :-)

**Comment by porres** [comment]
We can close this now that we have the [file] object, right?
