### ISSUE TITLE
symbol with spaces regression

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#824]
there is '(what I consider as) a serious regression between  0.49 and current master, related to how messages manage symbols containing space characters.

I will try to identify the responsible commits ASAP, but this is surely related to recent backslash escaping additions.

These screenshots illustrate the issue:
- current master (3c12b7694df6e4694aa57487fe8f7256a75677ca):
![pd-0 50 2](https://user-images.githubusercontent.com/3748246/70423843-95ca2880-1a6e-11ea-8d14-6d3d7152dfd5.png)

- pd-0.49.1
![pd-0 49 1](https://user-images.githubusercontent.com/3748246/70423845-9662bf00-1a6e-11ea-97ca-8f5720f6f70a.png)

(FYI: my specific problem is I cannot list anymore the content of a directory which name contains spaces; thus I cannot upgrade Pd for this particular project).

EDIT (@umlaeute): here's the test-patch (so you don't have to patch yourself)

~~~puredata
#N canvas 1204 378 450 535 12;
#X msg 71 130 a b;
#X obj 71 155 fudiformat -u;
#X obj 71 180 list tosymbol;
#X obj 71 205 t a a;
#X msg 71 230 symbol \$1_c;
#X obj 71 255 t a a;
#X msg 71 280 symbol \$1_d;
#X obj 71 305 t a a;
#X symbolatom 121 305 0 0 0 0 - - -;
#X symbolatom 121 255 0 0 0 0 - - -;
#X symbolatom 121 205 0 0 0 0 - - -;
#X connect 0 0 1 0;
#X connect 1 0 2 0;
#X connect 2 0 3 0;
#X connect 3 0 4 0;
#X connect 3 1 10 0;
#X connect 4 0 5 0;
#X connect 5 0 6 0;
#X connect 5 1 9 0;
#X connect 6 0 7 0;
#X connect 7 1 8 0;
~~~

i also took the liberty and replaced the (wrong) "*0.50-2*" version with a link to the "*current*" master

**Comment by Spacechild1** [comment]
Does this also happen with the Pd 0.50.2 *release*? This is not the same as current master. Miller recently pushed a commit about spaces in symbols and noted that he might have broken something

**Comment by Ant1r** [comment]
you were right! It doesn't happen with  (git tag) 0.50-2.

**Comment by millerpuckette** [comment]
almost certainly 2c174320d24e908feb36a22d62a8ed402e861566 did it.  I was worried that something would go wrong.  Will try to fix.

**Comment by millerpuckette** [comment]
OK an attempted fix is up.

**Comment by umlaeute** [comment]
@millerpuckette hmm well, this will still put a backslash before every space in symbolbox, messageboxes and printouts.

~~~pd
[32(
|
[makefilename %c]
|
[set a_$1_b(
|
[a_\ _b(
~~~

This is better than before (where `\` would accumulate backslashes whenever a new symbol was being generated), but still a regression, as right before 2c17432 they all printed nicely.

e.g. if i create a messagebox `[a\ b(` (with the first atom being literally <kbd>a</kbd>-<kbd>BackSlash</kbd>-<kbd>Space</kbd>-<kbd>b</kbd> and send that to a `[symbol]` a finally to a symbolbox, like the following...

~~~pd
[a\ b(
|
[symbol]
|
[symbolbox\
~~~

... then i get the following:

| commit | contents of symbolbox | notes|
|-----------|------------------------------|--------|
|b34090d| `a b` | the commit before 2c17432
|2c17432| `a\ b`
|a790096| `a\ b`



i do not fully understand what 2c17432 was trying to fix in the first place.

:thinking: 

most likely it has to do with persistency.
saving my above patch to disk, will leave out the backslashes. so when re-loading the patch the messagebox has become `[a b(` (selector `a`, first atom symbol:`b`), which is not the same as what we saved (selector `a b`).
i think the problem comes from Pd trying to use the same symbol-representation for both the GUI-communication (and display; which are not the same thing) and file persistency.

**Comment by Ant1r** [comment]
Thanks a lot! This fixes my specific use case anyway.

**Comment by millerpuckette** [comment]
> @millerpuckette hmm well, this will still put a backslash before every space in symbolbox, messageboxes and printouts.
[...]
> This is better than before (where `\` would accumulate backslashes whenever a new symbol was being generated), but still a regression, as right before [2c17432](https://github.com/pure-data/pure-data/commit/2c174320d24e908feb36a22d62a8ed402e861566) they all printed nicely.
> 
I think the previous behavior was wrong and this is a bug fix.  For instance, the symbol "foo foo"
and the two symbols "foo" and "foo" printed out the same way before.
> 
> most likely it has to do with persistency.
> saving my above patch to disk, will leave out the backslashes. so when re-loading the patch the messagebox has become `[a b(` (selector `a`, first atom symbol:`b`), which is not the same as what we saved (selector `a b`).
> i think the problem comes from Pd trying to use the same symbol-representation for both the GUI-communication (and display; which are not the same thing) and file persistency.
That is indeed what I first set out to fix - that was clearly a bug, regardkess of whether we regard symbol-box printing as one.

**Comment by reduzent** [comment]
Does that the fact that symbols containing spaces can now be safely saved in text files and in patches imply that the symbol atom _should_ display the backslashes?

Also, when it is indeed possible to keep symbols with spaces intact across save and load patch cycles, is there still a need to replace spaces by underscore in iemgui's labels? Would love to see real spaces in labels.

**Comment by umlaeute** [comment]
@reduzent i think the two points you raised are orthogonal.

- whether symbol boxes display backslashes before spaces is something i would consider a regression, but either @millerpuckette disagrees or we are talking about different things
- iemgui's are simply buggy when it comes to spaces (and i think this is  addressed in #953)

**Comment by reduzent** [comment]
> whether symbol boxes display backslashes before spaces is something i would consider a regression...

Me too.

**Comment by porres** [comment]
> either @millerpuckette disagrees or we are talking about different things

we might be, as I see it, a symbol box can print/display two symbols (aka a "list"), so if you have "foo foo" in a symbol box, it has to be a symbol with a space. Though I'm personally not annoyed by this, on the contrary, I guess. And things like "$0" would also expose the escape mechanism before.

**Comment by Spacechild1** [comment]
For me it is no question that this is a bug. Escaping characters are an implementation detail must only be displayed to the programmer (e.g. in message boxes, patch files), but *not* in user facing GUI objects like symbol atoms.

To give an example:
`[symbol foo\ bar(` should display the escape character (since the programmer wrote it or it has been restored from a patch file), but when I send this message to a symbol atom, the latter should simply display `foo bar`.

Another example: When you write `printf(stderr, "foo\nbar")`, would you expect the output in your console to be
```
foo\n
bar
```
or rather
```
foo
bar
```
?

**Comment by umlaeute** [comment]
i'd rather expect the output to be `foo\nbar` :stuck_out_tongue_winking_eye:

**Comment by reduzent** [comment]
>  Escaping characters are an implementation detail and must only be displayed to the programmer (e.g. in message boxes, patch files), but _not_ in user facing GUI objects like symbol atoms.

That's exactly my reasoning, I simply wasn't able to say it so well.

**Comment by Ant1r** [comment]
maybe this can be closed?

**Comment by Ant1r** [comment]
i take the liberty of closing, since the original issue  (backslash accumulation) is fixed.
