### ISSUE TITLE
PortAudio fails to detect audio devices

### ISSUE THREAD

**Issue by hjek** [pure-data/pure-data#847]
When starting Pd, audio devices are detected fine with ALSA:

```
$ ./bin/pd -alsa -listdev
audio input devices:
1. HDA Intel PCH (hardware)
2. HDA Intel PCH (plug-in)
audio output devices:
1. HDA Intel PCH (hardware)
2. HDA Intel PCH (plug-in)
API number 1

no MIDI input devices found
no MIDI output devices found
priority 8 scheduling failed.
^CPd: signal 2
```

Yet with PortAudio, no devices are found:

```
$ ./bin/pd -pa -listdev
no audio input devices found
no audio output devices found
API number 4

no MIDI input devices found
no MIDI output devices found
priority 8 scheduling failed.
^CPd: signal 2
```
This happens in Pd 0.50.2 on Fedora 31 x86_64.

**Comment by umlaeute** [comment]
not for me:

~~~sh
$ pd -pa -listdev
[...]
audio input devices:
1. (0) jack
2. (0) pulse
3. (0) default
4. (2) system
5. (2) PulseAudio JACK Sink
audio output devices:
1. (0) HDA Intel PCH: HDMI 0 (hw:0,3)
2. (0) HDA Intel PCH: HDMI 1 (hw:0,7)
3. (0) HDA Intel PCH: HDMI 2 (hw:0,8)
4. (0) HDA Intel PCH: HDMI 3 (hw:0,9)
5. (0) HDA Intel PCH: HDMI 4 (hw:0,10)
6. (0) hdmi
7. (0) jack
8. (0) pulse
9. (0) default
10. (2) system
11. (2) PulseAudio JACK Source
API number 4
[...]
~~~

note that i'm using the system-provided PortAudio, rather than the one that ships with Pd, as the latter never ever worked for me on my Debian systems. (also I never use PortAudio at all, if not for testing it for other people :-) using `JACK` is just superior on a pro-audio environment)

**Comment by hjek** [comment]
> note that i'm using the system-provided PortAudio, rather than the one that ships with Pd,

I still get the same result, even when I compile with `./configure  --enable-jack --without-local-portaudio`. I'll just use Jack but this may or may not still be considered a bug of some sorts.

**Comment by user706** [comment]
I can confirm this.
I cannot get the pulseaudio to list any devices.

> note that i'm using the system-provided PortAudio, rather than the one that ships with Pd, as the latter never ever worked for me on my Debian systems. (also I never use PortAudio at all, if not for testing it for other people :-) 

Really? It works?
How do you compile?

Because I have the same problem that hjek points out, which is:
> I still get the same result, even when I compile with `./configure --enable-jack --without-local-portaudio`.

i.e. no devices show up

**Comment by user706** [comment]
Ah here's the solution:
```bash
apt install portaudio19-dev
```

`apt source puredata` is my friend: [ref](https://sources.debian.org/src/puredata/0.50.2-3/debian/control/#L14)

**Comment by umlaeute** [comment]
yes.
when  i say that "I compile", i do this with my Debian Developer hat on...

mfg.igj.fjf
IOhannes
