### ISSUE TITLE
Possible regression issue with 0.51

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#848]
Hi, I'm testing an external with both current state of this repository (future 0.51) and Pd 0.50-2

it's a keyboard GUI, see in line 108 that I do this: https://github.com/porres/pd-else/blob/master/Classes/Source/keyboard.c#L108

```
static void keyboard_mousepress(t_keyboard* x, t_float xpix, t_float ypix, t_float id){
    if((int)x != (int)id) // Check if it's the right instance to receive this message
```

This is used to detect mouse clicks on the right instance. All [keyboard] objects will get this message, but only the one it's supposed to react gets called. Now, the thing is that in 0.51 sometimes this check gets messed up and the result is different where it shouldn't be. This never happens in 0.50-2

Anyway, I didn't write this code, this external was first developed by a collaborator. So, I'm thinking if there's a better way to manage this and if we shouldn't really have done this the way it is now. Nonetheless, it seems like a possible regression issue for 0.51

**Comment by umlaeute** [comment]
could you be more specific on the actual problem?

**Comment by porres** [comment]
In 0.51 I usually (but not always) get different numbers for "x" and "id" when they should be the same - therefore I get wrong numbers. But 0.50-2 always get them right.

**Comment by umlaeute** [comment]
that would be a fine opportunity to learn `git bisect` to find the commit that introduced the problem (just do a web search for the term - its in the git book; i'm afk right now so cannot help much)

**Comment by umlaeute** [comment]
and please use a descriptivr title...

**Comment by umlaeute** [comment]
I checked the sources of `[keyboard]`, and I see that Pd is only involved minimally here (if at all).
both the C-functions and the Tcl/Tk-procedures are defined in in the external.
Pd does the transmission between GUI and core, and transforms the string into a binbuf, but that's about it.

you might want to check the actual bytes that are transmitted, and see whether you are losing precision somewhere (there's a good reason that Pd uses `symbol` comparision rather than `int` comparision internally, to check for identity of a canvas).

i'm tempted to close this as "off topic"

**Comment by porres** [comment]
> there's a good reason that Pd uses symbol comparison rather than int comparison internally, to check for identity of a canvas

And what about "object ID" rather than "canvas id"? Cause this is what's going on here. Well, I guess I can give it a try. It's funny how it always works on 0.50-2 anyway.

**Comment by porres** [comment]
> and please use a descriptivr title...

I knew this was very broad, but couldn't figure out how to give a better title :/

**Comment by umlaeute** [comment]
> And what about "object ID" rather than "canvas id"? Cause this is what's going on here. Well, I guess I can give it a try. 

no real difference here...

> It's funny how it always works on 0.50-2 anyway.

that could have numerous reasons, e.g. a slightly different memory layout in the 0.51 builds that exposes a problem that was always in the external but just happened to not show up (but that's pure guesswork)

**Comment by porres** [comment]
So, Pd 0.51-0test1 is out and I downloaded it from Miller, and this actually works! It seems the problem happens when I build it...

I built 0.50-2 as a test, and this object didn't work either... I also built 0.51-0test1, same problem...

crazy, huh?

anyway, thanks for your input, and I wonder if you have any insight of what might be the problem and how I could make this work when I build Pd - Thanks!

**Comment by Spacechild1** [comment]
```
static void keyboard_mousemotion(t_keyboard* x, t_float xpix, t_float ypix, t_float id){
    if((int)x != (int)id) // Check if it's the right instance to receive this message
        return;
```
This code is code is bad in two ways:
1) you cast a pointer to a 32-bit `int`, but in a 64-bit app, pointers are 64-bit wide
2) you pass the object pointer from Tcl to Pd back as a float, possibly losing precision again

As @umlaeute already mentioned, convert the object pointer to a string, so gets passed from Tcl to Pd as a symbol. You can then use pass it between Tcl and Pd as a symbol. Just look how Pd creates canvas IDs with `.x%lx.c`.

Since this is a problem with your code, we can keep this issue closed. If you need more help, open an issue at your repo.

**Comment by Spacechild1** [comment]
https://github.com/porres/pd-else/blob/bb2a0ca9d270f4d7be1e65a2b74dd7be4f47078f/Classes/Source/keyboard.c#L588

Instead of binding all keyboard instances to a single symbol "keyboard" and then filter and each method, bind each instance to a unique symbol created from the object pointer (similarly to canvas identifiers) and pass that between Pd und Tcl. This way, each message from Tcl always gets delivered to the correct `t_keyboard` instance.

See for example https://github.com/pure-data/pure-data/blob/15761e59cdea4d654d6cae6f2b6960ea2b7dfab2/src/g_editor.c#L1913.

**Comment by porres** [comment]
Awesome, me and the original author of this object are looking into it and we'll change it, thanks again.

What still bothers me though is that the issue only happens when I build Pd. What's the catch here? Not that I wanna fix a build issue now, but I'm really curious and would like to understand how that affects and breaks the object.

**Comment by Spacechild1** [comment]
The cast from `t_keyboard *` to `int` can cause signed integer overflow, which is undefined behavior. This means, the compiler can do anything it wants, like unleashing a zombie apocalypse. Judging from your other issue, clang luckily just decides to return a *constant* negative number. Other compilers might wrap around based on 2s compliment, which is what most people would expect.

Note that *unsigned* integer overflow is well defined (the number wraps around).

**Comment by porres** [comment]
> Since this is a problem with your code, we can keep this issue closed. If you need more help, open an issue at your repo.

@Spacechild1 ,  did it, it's here and I am just hitting walls, hopefully you can fix it pretty fast so I'd appreciate your help, thanks!

**Comment by porres** [comment]
> Since this is a problem with your code, we can keep this issue closed. If you need more help, open an issue at your repo.

@Spacechild1  ,  did it, it's here and I am just hitting walls, hopefully you can fix it pretty fast so I'd appreciate your help, thanks!

here it is: https://github.com/porres/pd-else/issues/710

**Comment by umlaeute** [comment]
@porres seriously? you can reach out to @Spacechild1 via the mailinglist, or private mail or ping him from within porres/pd-else#710, but i think *this* ticket is not the place.
