### ISSUE TITLE
Add peak calculation to env~ as a second outlet

### ISSUE THREAD

**Issue by musger** [pure-data/pure-data#885]
As this has been discussed quite a bit on the mailing list in the past, a second outlet should be added to the env~ object reporting the rms value of the largest sample in env~'s analysis block for conversion to dbFS and subsequent display with Pd's internal VU meter.

**Comment by porres** [comment]
yup, I've requested that once or twice... I actually wrote an external based on [env~] that reports peak amplitude and might be what the second outlet should give, see else/peak~

**Comment by musger** [comment]
I just wrote an abstraction based on [array max] that serves my needs
(but not the needs of others or newcomers).

* porres <notifications@github.com> [2020-02-04 21:04]:

**Comment by porres** [comment]
I'm not proposing to use my external, just saying it could be a start point to implement this functionality into env~

**Comment by Spacechild1** [comment]
Note that for the second inlet of `[vu]` it's not enough to just get the peak value, you rather want an actual peak envelope follower, i.e. an envelope follower with instant rise and slow decay. This is possible with the new `[slop~]` object and the help patch even contains an example! It should probably added to the `[vu]`'s help patch as well. I find it odd, that `[vu]` has this second inlet, but doesn't show how to actually use it :-) *) Maybe we could even provide an abstraction?

*) The reason is probably that the GUI objects have been written by Thomas Musil. He also wrote iemlib - which contains peak envelope follower objects (`[pvu~]` and `[prvu~]`)

**Comment by porres** [comment]
>  i.e. an envelope follower with instant rise and slow decay

yeah, I actually have an abstraction that does that.

**Comment by porres** [comment]
can we close this and just agree to add an example to the documentation with slop~? As pointed in https://github.com/pure-data/pure-data/issues/977 ?
