### ISSUE TITLE
[Feature request] new file extension for double-precision externals.

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pure-data#902]
There is some discussion on #900 about how to implement FAT externals (single binaries that can work on single and double precision). While this can be cool for advanced developers I think there should also be a special file extension for double-precision externals so that existing and unmaintained libraries can be compiled for Pd-double without any or very few code modifications.

There are some suggestions like `<name>.float64.l_amd64`

Since Pd-double is something many of us are interested and is almost ready, there should be an easy way for us to compile existing code and use it. It could become hard if we have to insert something into many .c files.

Also it can be a nice option for active developers to simply supply non-FAT binaries.

**Comment by umlaeute** [comment]
> Also it can be a nice option for active developers to simply supply non-FAT binaries.

esp. since most likely there are externals that cannot be compiled as PHAT-binaries (shared internal functions that deal with `t_float`, where it would just be too burdensome to mangle all their names)

**Comment by umlaeute** [comment]
here's another idea:

#### use the deken-specifier together with the native extension for dynamic-link libraries.

To keep things simple (and reduce the noise with `-verbose`), i would suggest to only allow *lower case* specifiers, and no arch variants (e.g. `i386` for all `x86_32` variants, and `amd64` or all `x86_64` variants)

e.g. `zexy.linux-amd64-32.so`, `zexy.darwin-arm64-32.so` (or `zexy.darwin-arm64-32.dylib`?), `zexy.windows-i386-32.dll`

##### pros
- using the system extension (as the last part of the full extension)
 - it gives quite predictable *final* extensions, which makes filtering (by filename) a lot easier
 - these extensions are *well known* (so we don't have to invent a new one for each and every platform)
 - system tools often use the file-extension to recognize 
- using the deken specifier (as part of the  full extension)
 - it full covers what we need right no (being able to distinguish by OS/binary-format, CPU instruction set and float-size
 - people can relate the files within a deken-package with the deken-package-filename
 - the problem space is the same for deken package files and externals. if we ever need to add a new parameter, the deken specifier and the externals are likely to be affected in a similar way, so we need to solve the problem only once.
- it gets rid of the super-cryptic `.<first-letter-of-the-os>_<cpu-arch>` specifier (`.o_ia64` anybody?)

##### cons
- it shares the same (final) extensions as any support libraries.
  e.g.:
  - `zexy.linux-amd64-32.so` + `libzexy.linux-amd64-32.so` (or even `libzexy.linux-amd64-32.so.so`, but I guess we [don't want *this*](https://github.com/pure-data/pd-lib-builder/pull/59#issuecomment-593085244))
- ...(?)

we might pick a general unified (final) extension, instead of the system ones, e.g. `.pdx` (but that is already taken) or `.pd_external`.
but i think the less we invent ourselves, the better.

**Comment by umlaeute** [comment]
search order would be something like:
1. `foolib.linux-amd64-32.so`
2. `foolib.linux-amd64.so`
3. `foolib.l_amd64`
4. `foolib.l_ia64`
5. `foolib.pd_linux`
6. `foolib.so`
7. `foolib.pd`


note the 2nd case (missing floatsize specifier, e.g. `.linux-amd64.so`), which allows for
- floatsize-agnostic externals (e.g. loaders typically do not use `t_float` at all)
- PHAT libraries

**Comment by umlaeute** [comment]
me neither. its just that the files are named all similar and it might confuse people who look at the directory.
