### ISSUE TITLE
[clone] misses [declare] -stdpath dependencies of main patch

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#929]
[clone] is supposed to work like a dynamic abstraction, it doesn't keep -stdpath dependencies from [declare].
But, it does accept -lib dependencies.
(tested on windows)

**Comment by umlaeute** [comment]
would it be possible to create separate tickets for separate issues?

unless you prefer to have your ticket closed because a subset was fixed (as in #965); this is basically a problem with github's ticket system that allows us to easily handle duplicate issues (by closing them), but doesn't allow us to close fractional issues.

since the original title was only about one issue ("find not working") and the reference in #965 is also about the "find" issue, i suggest to move the declare problem to a separate thread (and search the archives; iirc this has already been reported)

**Comment by jmmmp** [comment]
I did search for "clone" before posting this - #965 didn't came up in the search. Just did it now once more, it still doesn't show up.

I removed the find-section of the issue, and left only the dependency part.

**Comment by umlaeute** [comment]
#965 is a pull-request that fixes the problem, not a ticket that describes the problem (like this one).
also, #965 was created after *this* ticket (#929 < #965), so no wonder why you didn't find it :-)

anyhow, i cannot find a ticket describing the find-weirdness either, probably i just misremembered (did you by chance post the problem to the Pd-list?)

in any case, thanks for clearing up this issue to only contain a single problem.

**Comment by Ant1r** [comment]
I'd like we fix this issue (TLDR: I think I found the reason), which I find annoying, too. Also note that a parent's [declare -path] is not taken into account either.

Actually after doing some tests I noticed something weird:

- prerequisite:
  - the main directory contains 2 patches `master.pd` and `absA.pd`, and a subdirectory `subdir/`
  - `master.pd` contains a `[declare -path subdir]` and a `[clone absA 1]`
  - `subdir/` contains an (empty) patch `absB.pd`
- open the `master/absA` by clicking on the `[clone absA 1]`; add `[absB]` : Pd can't find the abstraction ("... couldn't create")
- save `absA`: the window stays opened (actually it reopens) and sometimes `[absB]` is now found, sometimes not...
- quit Pd, restart, open `master.pd`: now `[absB]` is correctly found inside of cloned `absA`.

The reason is the clone object clears the `gl_owner` reference from the newly created canvas instance, but only after the instance is fully created. Hence the parent canvas's search paths list is parsed at load time, but cannot be later. Obviously having the `gl_owner` pointing to the parent's canvas is not a problem, at least it's not a problem at boot time...

So IMO the fix is only to remove the line:
https://github.com/pure-data/pure-data/blob/80929213b540af1ba12c2c8abd7a58d0c1eb2204/src/g_clone.c#L213

I've just tried with the biggest patch I have, containing many clones, and I haven't had any bad surprises.

**Comment by Ant1r** [comment]
of course things aren't that simple...

for example, with the proposed change applied (not clearing gl_owner for a clone instance), interactively adding an inlet to a cloned canvas crashes Pd...

so this change would imply adding many `if (! x->gl_isclone)` checks.

**Comment by Ant1r** [comment]
Note this is strongly linked with issue #410 .
These can be fixed by PR #972 .
