### ISSUE TITLE
$0 expansion inconsistency between GUI's labels (iemguis/atom boxes) and other elements

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#958]
I consider this an inconsistency. Messages, comments and arrays don't expand "$0", but if you have that in labels of iemguis and atom boxes, it gets expanded. 

<img width="874" alt="Screen Shot 2020-04-20 at 00 04 00" src="https://user-images.githubusercontent.com/5360142/79710164-88357280-829a-11ea-8456-61f12cfd009b.png">

**Comment by umlaeute** [comment]
asked otherwise:
if i have a GOP-abstraction *blub.pd* that uses a number-box with a label `$1-bar` and I instantiate it as `[blub foo]` and `[blub juce]`, do i want to see **$1-bar** in both GOP-instances, or **foo-bar** and **juce-bar**?
if the latter, do i want to have an exception for `$0`? do i also want an exception for `$1`, `$5`, `$10`, `$20`, `$50` and `$100` (and what about `$2`, `$500`, `$1000`, `$5000`, `$10000`?)

**Comment by Spacechild1** [comment]
Messages don't belong in the same group. Of course they don't expand $0, just like they don't expand $1, $2, etc. Otherwise they would be useless.

Regarding comments: I don't know what the expected behavior should be... But I also don't think it's too important. I yet have to see a use case for expanded dollars in comments.

I think the real curious case are GOPs (like in garrays) where the name is shown in its unexpanded form. I think it *could* probably display the expanded form, like the canvas window title already does. Dunno...

Anyway, please update the issue title/description. "$0 gets expanded in iemguis and atom boxes" is certainly not a bug but expected behavior, the question is rather why dollarsymbols don't get expanded in GOP titles and comments.

**Comment by umlaeute** [comment]
hmm, well.
the thing is that an array `$0-x` is actually much easier to parse (for the human that looks at the patch) than `1003-x`.
the latter is just some weird name, whereas the former is telling me that "this is a local array".

so i guess the title is somewhat correct for the problem the OP wants to be addressed (although i think they really mean "$0 gets expanded in **labels** of iemguis and atom boxes")

**Comment by Spacechild1** [comment]
Ok, but what about $1, $2, $3 etc. expansion?

Let's say I have a GOP abstractioin with a name `/my/gop/$1`. If I instantiate it with creation argument `foo`, shouldn't the GOP title read `/my/gop/foo` VS `/my/gop/$1/`?

**Comment by Ant1r** [comment]
The problem is we can't assume that only $0 must be treated as a special case: e.g $1 can be the parent's $0, if it was passed as the abstraction's argument. In this case we would prefer to keep it unexpanded in labels.

 But sometimes $1 will be a signifiant word (e.g "foo") that DO want to see expanded in labels...

So I can't think of a way that would comply with both cases. 

Personally, after many years using $0 extensively (e.g for passing parent's reference to abstractions), now I think that it's much better to avoid it, so you can always access any canvas with an absolute explicit reference name (e.g foo1/child2).

That's why I'd prefer to keep existing behavior, which is expanding dollars in labels.

**Comment by Spacechild1** [comment]
@umlaeute 

> so i guess the title is somewhat correct for the problem the OP wants to be addressed

no, because the problem being addressed is not a problem at all.

**Comment by Spacechild1** [comment]
@Ant1r 

> But sometimes $1 will be a signifiant word (e.g "foo") that DO want to see expanded in labels...

Exactly! I would go so far and say that $1 is always significant. I don't see why someone would like to show the unexpanded dollarsym in a user facing label. That's why I was wondering about the current behavior of GOP titles, which don't expand dollarsyms, while the patch window titles *do*.

> That's why I'd prefer to keep existing behavior, which is expanding dollars in labels.

I would *very* much prefer to keep the existing behavior.

**Comment by porres** [comment]
> if i have a GOP-abstraction blub.pd that uses a number-box with a label $1-bar and I instantiate it as [blub foo] and [blub juce], do i want to see $1-bar in both GOP-instances, or foo-bar and juce-bar?
> if the latter, do i want to have an exception for $0?

What about array names then? Do you want them to expand it too? Why would you want an exception for arrays? Or doesn't it count as an exception and why?

The main point of my issue is that we currently have an inconsistency that I was hoping to deal with by properly standardising behaviour, not add more.

**Comment by Ant1r** [comment]
so let's expand $ for array names. I'll do it soon (in #953).

**Comment by Spacechild1** [comment]
> What about array names then? Do you want them to expand it too?

I think *this* is the actual interesting question we should debate. The fact that dollarsyms get expanded in GUI labels is expected and reasonable. Can you change your issue description or maybe even open a new issue?

> The main point of my issue is that we currently have an inconsistency

Ok, but please don't throw in unrelated things like Pd message boxes.

BTW, the case of comments is interesting as well.

**Comment by Spacechild1** [comment]
Something like: "$0 not expandend in GOP titles and comments"

**Comment by porres** [comment]
> Ok, but please don't throw in unrelated things like Pd message boxes.

Well, the arrays were following the same patterns as comments and objects, so I was just grouping it all together, even though I know it could be a separate group. And I just thought it made sense to not expand anyway.

And well, didn't array's names use to expand $0 and then it changed? Why did it change, do we want to change back?

> so let's expand $ for array names. I'll do it soon (in #953).

Anyway, I'm still trying to understand the desire and use case of wanting to expand "$0", and I don't know if there was this consensus already, let's wait a bit ;)

**Comment by Spacechild1** [comment]
> Anyway, I'm still trying to understand the desire and use case of wanting to expand "$0", and I don't know if there was this consensus already, let's wait a bit ;)

Agreed, but can we do this in a new issue and close that one? I think there's at least consensus (I hope) that dollarsymbols must expand in GUI labels and it really is only GOP titles (and maybe comments) which are the outliers.

**Comment by Spacechild1** [comment]
Sorry, I've seen you've updated the issue description again. It's much better now, but please remove the reference to Pd message boxes.

**Comment by Spacechild1** [comment]
and again: it's not only about arrays, it's about GOPs in general. So I'd actually prefer a new issue :-)

**Comment by porres** [comment]
yeah, I'll open a new one, give me some time to think

**Comment by porres** [comment]
> BTW, the case of comments is interesting as well.

Comments should not change the behaviour and expand "$1" or "$0" - it'd break and ruin the ability to document it, for one... and it'd ruin the tutorial I've been developing for over a decade now.

This would be the opposite outcome of my issue, as I thought labels in iemguis should be like comments, and not the other way around.

**Comment by umlaeute** [comment]
i'm quite intrigued by the idea to be able to replace words in comments via arguments (that is: expand $args in comments)

**Comment by Ant1r** [comment]
maybe comments can be considered as an exception?
there's no much use to expand comments, IMO.

**Comment by porres** [comment]
> i'm quite intrigued by the idea to be able to replace words in comments via arguments (that is: expand $args in comments)

Alternatives: A) Now labels are becoming basically comments, allowing spaces, commas and stuff... they could be used to load it. B) A new and fancier iemgui/comment object

**Comment by porres** [comment]
So, I'm closing this issue and opening a new one... https://github.com/pure-data/pure-data/issues/964
