### ISSUE TITLE
$n expansion inconsistency with arrays

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#964]
In Pd, we usually have an expansion of "$0" when it is displayed as messages. If you print [symbol $0-x], you get "number"-x, same goes for displaying this in an atom symbol  and other examples.

An exception is comments, and I think it should be like that.

What seems to be a quite inconsistent example is arrays that do not expand "$0"

see image below for more details, patch: 
[expansion.pd.zip](https://github.com/pure-data/pure-data/files/4505825/expansion.pd.zip)
 

<img width="498" alt="Screen Shot 2020-04-20 at 16 51 24" src="https://user-images.githubusercontent.com/5360142/79793735-70f09680-8327-11ea-9781-ba3fbbd250e7.png">

The deal with "$1" and "$2" is basically the same.

The difference is that they don't get expanded if such arguments are not provided.

This is specially confusing for arrays, cause it'll always be unexpanded, but it'll behave either by expanding it or not if inside a [table] or [array] object.

**Comment by Spacechild1** [comment]
> If you print [symbol $0-x], you get "number"-x

This is not related, you might remove it for the sake of clarity.

Also I want to point out again that this is not specifically about arrays but about graphs in general. I'm insisting on this because personally I often felt the need for dollarsym expansion in GOP abstractions, more so than in graphical arrays. Of course, they are both just graphs.

**Comment by Spacechild1** [comment]
Like if you have a GOP abstraction `[foo]` which takes a creation argument $1, and you create instances `[foo 1]`, `[foo 2]`, `[foo 3]`, it would be nice if the GOP label would say `/foo/1`, `/foo/2`, `/foo/3` and not `/foo/$1` for every instance.

**Comment by Spacechild1** [comment]
BTW, it's good that you're pointing out that the patch window titles *do* expand the dollarsym. I think this feature is crucial, otherwise you often don't know which instances is which. With GOPs, I currently have to always right click and open the window. My workaround has been to deactivate the GOP label and put a `[cnv]` inside which shows the expanded name.

To put it short: I find the current behavior of GOP labels regarding dollarsyms pretty useless.

**Comment by umlaeute** [comment]
i don't understand why @porres is so obsessed with `$0`. the thing (i'm reluctant to call it an "issue") also happens with any $args.
please update the patch description accordingly.

also, the example patch seems to be factually wrong.
a graphical array expands `$0` just fine (simply try to access its values via `[tabread $0-y]`), it's only the label that doesn't get expanded.

i'd like to re-iterate, that (while i see the inconsistency), i really think that a label `$0-y` is more meaningful than a label `1003-y` as it shows what the user meant (a local array) and doesn't hurt the eye.

@Spacechild1 with "gop label" you are referring to the "object name and arguments"?
because i really don't see how Pd should guess `/foo/3` from an instance `[foo 3]`

**Comment by porres** [comment]
> Also I want to point out again that this is not specifically about arrays but about graphs in general.

but it's the same for subpatches, as I pointed, wether with GOP or not... I didn't add the specific case of it being a GOP or not because I didn't feel it was relevant.

**Comment by porres** [comment]
> This is not related, because it is not a GUI object, so you might remove it for the sake of clarity.

My point is that what comes out of the object is the expanded message, it's not something that happens inside the GUI at all. In fact, you can't even type "$0-x" in the symbol atom box, what you get is the literal symbol "\$0-x"

**Comment by Spacechild1** [comment]
> with "gop label" you are referring to the "object name and arguments"?
because i really don't see how Pd should guess /foo/3 from an instance [foo 3]

Turns I out I was completely confused and what I had in mind was actually an edge case...

**Comment by umlaeute** [comment]
> My point is

i don't see any point here.

>  Turns I out I was completely confused

i'm confused as well.

this entire discussion revolves about nothing.
the issue tracker doesn't seem to be the right place to come to a consensus about what we actually want. let's move this to the mailinglist, the forum, the IRC.

**Comment by Spacechild1** [comment]
@porres: I understand that dollarsym expansion can be confusing. Let's first clear up the confusion and then continue with discussion of issues, otherwise we don't have a common base and get lost on side tracks. The list is a good place for such things and since it gets archived, other people can learn from it :-)

**Comment by porres** [comment]
well, my point is just a consistency issue, there seems to be a behaviour that doesn't correspond to the norm.

> i'd like to re-iterate, that (while i see the inconsistency), i really think that a label $0-y is more meaningful than a label 1003-y as it shows what the user meant (a local array) and doesn't hurt the eye.

well, it's good we agree there is an inconsistency then. It's more of a discussion wether this makes sense or not. I don't see a point in having this inconsistency. If displaying "$0" is important to let people know it's a locality variable, why not inside [table]/[array]? Why not in labels?

> the issue tracker doesn't seem to be the right place to come to a consensus about what we actually want. let's move this to the mailinglist, the forum, the IRC.

I agree that if it's hard to reach a consensus, we can move to the pd list and get more people involved. 

> i don't understand why @porres is so obsessed with $0.

I'm obsessed with documentation, actually, trying to find a rule/norm, and I often find inconsistencies I like to point out, so we can make sense and either 1) change the inconsistency or 2) document and explain the inconsistency.

$1 is a bit different and I'm also studying the case. For one, it gets expanded with a backlash, and to avoid yet more confusion and noise, I was sticking to "$0" first.

<img width="211" alt="Screen Shot 2020-04-20 at 18 54 01" src="https://user-images.githubusercontent.com/5360142/79803446-6094e780-8338-11ea-8bd5-60ac5d8d1700.png">

**Comment by Spacechild1** [comment]
> $1 is a bit different and I'm also studying the case. 

This only happens when you didn't provide a $1 argument, e.g. the object is on a root window or the abstraction doesn't have arguments. In fact, certain people *cough cough* have exploited this strange behavior to get the creation arguments as a list by iterating over something like `[list append $1 $2 $3 $4 $5 $6 $7 $8 $9 $10]` until they hit one of those strange symbols.

But this has nothing to do with dollarsyms in array labels. And the array label issue/question concerns *all* dollarsyms. There is no reason to be fixated on $0 here.

Generally, think like this:

something like `[symbol $0]` is a patch object, so it describes what it *does* (e.g. expand $0), but in a user-facing GUI object you want to show the actual value, i.e. the result and not the behavior.

Now array labels are somewhat inbetween and I'm not really sure anymore what the correct behavior should be. When in doubt, I'd say leave it as it is :-)

**Comment by Spacechild1** [comment]
But again, I have a strong deja vu feeling here...

**Comment by Ant1r** [comment]
I think array label is not expanded because... it is no label: it's the array name.
so it's not really an inconsistency.
> you can't even type "$0-x" in the symbol atom box, what you get is the literal symbol "$0-x"

this, perhaps, deserves some thought? even if it seems a bit edge case to me.

**Comment by porres** [comment]
> I think array label is not expanded because... it is no label: it's the array name.
> so it's not really an inconsistency.

But as I've shown, if you load [table $0-x] and/or [array define $0-y], you get the expanded name for the array when you click on those objects and open the subpatch. It can't get more inconsistent than that

**Comment by porres** [comment]
> this, perhaps, deserves some thought? even if it seems a bit edge case to me.

Not that much of an edge case. In the other issue I opened and closed, I was trying to use a symbol atom to define an expanded dollarsym (such as "$0-x") to set a [send] address.

Anyway, now that you mention and I think about it. This is an old behaviour from a time we couldn't type or use "\". So it'd generate automatically. But now we can. So maybe we can think about letting the user choose whether the literal symbol is desired or not!

**Comment by porres** [comment]
> This only happens when you didn't provide a $1 argument 

well, it's a different case nonetheless

> But this has nothing to do with dollarsyms in array labels. And the array label issue/question concerns all dollarsyms.

ok, we can expand the discussion and include the "$1" cases, but it increases complexity in the discussion, and I can point how the confusion and inconsistency increases as well.

An array will show "$1" regardless if there's such an argument or not, while a label and other elements will react differently. Hence, we can't know what's happening much if we look at the array. Moreover, again, arrays inside [table]/[array] will expand and have a completely different behaviour (either expanding or not).

Now, I can't see why it's so important you know if arrays (if inserted via the put menu) and only them need to show the unexpanded symbol. Isn't it obvious that a name such as "1003-x" is extremely likely to be an expanded "$0-x"? Specially if it is like inside an abstraction?

And if you have a name that depends on the argument you give the abstraction, regardless of the abstraction you open, you always get "$1-x" as the name.

> But again, I have a strong deja vu feeling here... 

me too :)

> Maybe think some more about it, write it down and make a nice chapter in your tutorial? ;-)

yup, that's the idea, but first I think we need to try and make sense of this together. By giving it some thought, I'm building a strong opinion "$n" should be expanded in arrays for consistency purposes.

**Comment by porres** [comment]
> the issue tracker doesn't seem to be the right place to come to a consensus about what we actually want. let's move this to the mailinglist, the forum, the IRC.

well, it seems nobody cared when I presented this in the Pd-list (it's been over 2 weeks) :) 

and this became a long discussion in the tracker that I think I'd rather reboot into a new, more consice and more objective issue.
